#!/bin/bash

# Copyright 2008, 2009, 2010, 2011, 2013, 2015, 2018, 2019, 2022  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=iputils
VERSION=${VERSION:-$(echo $PKGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
BUILD=${BUILD:-1}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i686 ;;
    arm*) export ARCH=arm ;;
    loongarch64) export ARCH=loong64 ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$(echo $VERSION | tr -d 's')-$ARCH-$BUILD.txz"
  exit 0
fi

if [ "$ARCH" = "i686" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "loong64" ]; then
  LIBDIRSUFFIX="64"
else
  LIBDIRSUFFIX=""
fi

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}

TMP=${TMP:-/tmp}
PKG=$TMP/package-iputils

rm -rf $PKG
mkdir -p $TMP $PKG

cd $TMP
rm -rf iputils-$VERSION
tar xvf $CWD/iputils-$VERSION.tar.?z || exit 1
cd iputils-$VERSION || exit 1

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+

zcat $CWD/iputils.docbook.revert.diff.gz | patch -p1 --verbose || exit 1

# Configure and build:
export CFLAGS="$SLKCFLAGS"
export CXXFLAGS="$SLKCFLAGS"
mkdir meson-build
cd meson-build
meson setup \
  --prefix=/usr \
  --libdir=lib${LIBDIRSUFFIX} \
  --libexecdir=/usr/libexec \
  --bindir=/usr/bin \
  --sbindir=/usr/sbin \
  --includedir=/usr/include \
  --datadir=/usr/share \
  --mandir=/usr/man \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --buildtype=release \
  .. || exit 1
  "${NINJA:=ninja}" $NUMJOBS || exit 1
cd ..

cd meson-build
strip arping clockdiff ping/ping tracepath
mkdir -p $PKG/sbin
cat arping > $PKG/sbin/arping
chmod 755 $PKG/sbin/arping
mkdir -p $PKG/usr/sbin
cat clockdiff > $PKG/usr/sbin/clockdiff
chmod 755 $PKG/usr/sbin/clockdiff
mkdir -p $PKG/bin
cat ping/ping > $PKG/bin/ping
chmod 4711 $PKG/bin/ping
( cd $PKG/bin ; ln -sf ping ping6 )
mkdir -p $PKG/usr/bin
cat tracepath > $PKG/usr/bin/tracepath
( cd $PKG/usr/bin ; ln -sf tracepath tracepath6 )
chmod 755 $PKG/usr/bin/tracepath*

mkdir -p $PKG/usr/man/man8
( cd doc
  for file in arping clockdiff ping tracepath ; do
    cat $file.8 | gzip -9c > $PKG/usr/man/man8/$file.8.gz
  done
  cd $PKG/usr/man/man8
  ln -sf ping.8.gz ping6.8.gz
  ln -sf tracepath.8.gz tracepath6.8.gz
)

cd ..
mkdir -p $PKG/usr/doc/iputils-$VERSION
cp -a \
  CHANGES* INSTALL* LICENSE* README* RELNOTES* \
  $PKG/usr/doc/iputils-$VERSION
chmod 644 $PKG/usr/doc/iputils-$VERSION/*

# Finish up the package:
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
/sbin/makepkg -l y -c n $TMP/iputils-$(echo $VERSION | tr -d 's')-$ARCH-$BUILD.txz
