.\" -*- nroff -*-
.ds g \" empty
.ds G \" empty
.\" Like TP, but if specified indent is more than half
.\" the current line-length - indent, use the default indent.
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.lu-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH IMCONFIG 1 "01 June 2022" "Slackware Version 15.1.0"
.SH NAME
imconfig \- choose a default input method for X/Wayland.
.SH SYNOPSIS
.B imconfig
.SH DESCRIPTION
.B imconfig
provides a menu of the input methods available on the machine so that you
may choose one of them to use within an XDG compliant desktop environment.

imconfig writes out $HOME/.profile.d/input-method.{sh,csh} files, allowing
the user to choose their own default input method (possibly overriding the
one chosen as a system default).
.SH AUTHOR
Patrick J. Volkerding <volkerdi@slackware.com>
Heinz Wiesinger <pprkut@slackware.com>
