#!/bin/bash

# Copyright 2025  Patrick J. Volkerding, Sebeka, Minnesota, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=openblas
SRCNAM=OpenBLAS
VERSION=${VERSION:-$(echo $SRCNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
BUILD=${BUILD:-3}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$(uname -m)" in
    i?86) ARCH=i686 ;;
    arm*) readelf /usr/bin/file -A | egrep -q "Tag_CPU.*[4,5]" && ARCH=arm || ARCH=armv7hl ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
    *) ARCH=$(uname -m) ;;
  esac
  export ARCH
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

# Don't include -j for this package.
NUMJOBS=${NUMJOBS:-"$(expr $(nproc) + 1)"}

# If you passed in a NUMJOBS with the -j, we're just going to use 4 jobs.
# I've observed the compile hanging when run massively parallel with icecream.
# This is a safer bet.
if echo $NUMJOBS | grep -q j ; then
  NUMJOBS=4
fi

if [ "$ARCH" = "i686" ]; then
  LIBDIRSUFFIX=""
  # Use NORTHWOOD CPU target as the default to avoid SSE3 and AVX.
  # We also use DYNAMIC_ARCH=1, so you can select a different CPU at runtime:
  # export OPENBLAS_CORETYPE=Prescott
  TARGET=${TARGET:-NORTHWOOD}
elif [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
  # Use OPTERON CPU target as the default to avoid SSE3 and AVX.
  # We also use DYNAMIC_ARCH=1, so you can select a different CPU at runtime:
  # export OPENBLAS_CORETYPE=Prescott
  TARGET=${TARGET:-OPTERON}
else
  LIBDIRSUFFIX=""
  # Use GENERIC CPU target as the default:
  TARGET=${TARGET:-GENERIC}
fi

TMP=${TMP:-/tmp}
PKG=$TMP/package-$PKGNAM

rm -rf $PKG
mkdir -p $TMP $PKG

cd $TMP
rm -rf $SRCNAM-$VERSION
echo "Extracting $CWD/$SRCNAM-$VERSION.tar.?z..."
tar xf $CWD/$SRCNAM-$VERSION.tar.?z || exit 1
cd $SRCNAM-$VERSION || exit 1

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+

# Determine the lapack version:
LAPACKMAJ=$(grep 'set(OpenBLAS_MAJOR_VERSION ' CMakeLists.txt  |tr -s '()' ' '  |cut -d' ' -f3)
LAPACKMIN=$(grep 'set(OpenBLAS_MINOR_VERSION ' CMakeLists.txt  |tr -s '()' ' '  |cut -d' ' -f3)
LAPACKPAT=$(grep 'set(OpenBLAS_PATCH_VERSION ' CMakeLists.txt  |tr -s '()' ' '  |cut -d' ' -f3)
LAPACK="${LAPACKMAJ}.${LAPACKMIN}.${LAPACKPAT}"

# Build:
make \
  PREFIX=/usr \
  MAKE_NB_JOBS=${NUMJOBS} \
  OPENBLAS_LIBRARY_DIR=/usr/lib$LIBDIRSUFFIX \
  TARGET=$TARGET \
  DYNAMIC_ARCH=1 \
  NO_STATIC=1 \
  USE_THREAD=1 \
  NUM_THREADS=64 \
  USE_OPENMP=1 \
  USE_TLS=1 \
  NO_LAPACK=0 \
  BUILD_LAPACK_DEPRECATED=1 \
  NO_AFFINITY=1 \
  BUILD_RELAPACK=1 || exit 1

# Install:
make \
  PREFIX=/usr \
  MAKE_NB_JOBS=${NUMJOBS} \
  OPENBLAS_LIBRARY_DIR=/usr/lib$LIBDIRSUFFIX \
  TARGET=$TARGET \
  DYNAMIC_ARCH=1 \
  NO_STATIC=1 \
  USE_THREAD=1 \
  NUM_THREADS=64 \
  USE_OPENMP=1 \
  USE_TLS=1 \
  NO_LAPACK=0 \
  BUILD_LAPACK_DEPRECATED=1 \
  BUILD_RELAPACK=1 \
  NO_AFFINITY=1 \
  DESTDIR=$PKG \
  install || exit 1

# Install compatibility symlinks:
# For BLAS:
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/libblas.so
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/libblas.so.${LAPACKMAJ}
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/libblas.so.${LAPACK}
ln -s openblas.pc $PKG/usr/lib$LIBDIRSUFFIX/pkgconfig/blas.pc
# For CBLAS:
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/libcblas.so
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/libcblas.so.${LAPACKMAJ}
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/libcblas.so.${LAPACK}
ln -s openblas.pc $PKG/usr/lib$LIBDIRSUFFIX/pkgconfig/cblas.pc
# For LAPACK:
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/liblapack.so
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/liblapack.so.${LAPACKMAJ}
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/liblapack.so.${LAPACK}
ln -s openblas.pc $PKG/usr/lib$LIBDIRSUFFIX/pkgconfig/lapack.pc
# For LAPACKE:
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/liblapacke.so
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/liblapacke.so.${LAPACKMAJ}
ln -s libopenblasp-r${VERSION}.so $PKG/usr/lib$LIBDIRSUFFIX/liblapacke.so.${LAPACK}
ln -s openblas.pc $PKG/usr/lib$LIBDIRSUFFIX/pkgconfig/lapacke.pc

# Usually empty:
rmdir $PKG/usr/bin

# Strip binaries:
find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# Add a documentation directory:
mkdir -p $PKG/usr/doc/${PKGNAM}-$VERSION
cp -a \
  BACKERS* CONTRIBUTORS* Changelog.txt GotoBLAS* LICENSE* README* SECURITY* USAGE* \
  $PKG/usr/doc/${PKGNAM}-$VERSION

# If there's a ChangeLog.txt, installing at least part of the recent history
# is useful, but don't let it get totally out of control:
if [ -r ChangeLog.txt ]; then
  DOCSDIR=$(echo $PKG/usr/doc/${PKGNAM}-$VERSION)
  cat ChangeLog.txt | head -n 1000 > $DOCSDIR/ChangeLog.txt
  touch -r ChangeLog.txt $DOCSDIR/ChangeLog.txt
fi

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $TMP/$PKGNAM-$VERSION-$ARCH-$BUILD.txz
