#!/bin/sh
#
# Run this script in the root directory of the repository to re-compress
# all patches and scripts that were un-compressed to make a better git commit:
#
gzip ./extra/source/emacspeak/emacspeak.tcl8.5.diff
gzip ./extra/source/pam/patches/pam-1.1.0-notally.patch
gzip ./extra/source/pam/patches/pam-1.1.3-limits-nosetreuid.patch
gzip ./extra/source/pam/patches/pam-1.1.3-securetty-console.patch
gzip ./extra/source/pam/patches/pam-1.1.3-limits-range.patch
gzip ./extra/source/pam/patches/pam-1.1.3-pwhistory-incomplete.patch
gzip ./extra/source/pam/patches/pam-1.1.1-faillock.patch
gzip ./extra/source/pam/patches/pam-1.1.3-faillock-screensaver.patch
gzip ./extra/source/pam/patches/pam-1.0.91-std-noclose.patch
gzip ./extra/source/pam/patches/pam-1.1.3-nouserenv.patch
gzip ./extra/source/pam/patches/pam-1.0.90-redhat-modules.patch
gzip ./extra/source/pam/patches/pam-1.1.2-noflex.patch
gzip ./extra/source/grub/grub-0.97-x86_64.patch
gzip ./extra/source/grub/grub_support_256byte_inode.patch
gzip ./extra/source/grub/grubconfig_localefix.patch
gzip ./extra/source/bittorrent/doinst.sh
gzip ./extra/source/bittorrent/bittorrent-xterm.sh
gzip ./extra/source/partitionmanager/doinst.sh
gzip ./extra/source/fvwm-2.6.1/xinitrc.fvwm2
gzip ./extra/source/fvwm-2.6.1/doinst.sh
gzip ./extra/source/wicd/wicd-1.7.0-fix_script_bug.diff
gzip ./extra/source/wicd/wicd-1.7.0-fix_EAP_fast_typo.diff
gzip ./extra/source/wicd/doinst.sh
gzip ./extra/source/bash-completion/bash_completion.sh
gzip ./extra/source/bash-completion/fixup-sh-script-completions.diff
gzip ./extra/source/bittornado/btdownloadxterm.sh
gzip ./extra/source/bittornado/doinst.sh
gzip ./extra/source/tightvnc/doinst.sh
gzip ./extra/source/tightvnc/tightvnc.paths-and-perms.diff
gzip ./extra/source/GConf/doinst.sh
gzip ./testing/source/mesa/patches/i915_fragment_shader_disable.patch
gzip ./testing/source/mesa/patches/mesa-7.9-libdrm-2.4.23-nouveau-api.patch
gzip ./source/a/mcelog/doinst.sh
gzip ./source/a/mcelog/mcelog.init.diff
gzip ./source/a/kbd/sources/kbd-1.15-unicode_start.patch
gzip ./source/a/kbd/sources/speakupmap.map
gzip ./source/a/kbd/sources/kbd-1.15-keycodes-man.patch
gzip ./source/a/kbd/sources/kbd-1.15.2-po.patch
gzip ./source/a/kbd/sources/kbd-1.15-resizecon-x86_64.patch
gzip ./source/a/kbd/sources/nl.euro.diff
gzip ./source/a/pcmciautils/doinst.sh
gzip ./source/a/dialog/dialog.smaller.min.height.diff
gzip ./source/a/splitvt/splitvt_1.6.5-9.diff
gzip ./source/a/bin/scripts/xx
gzip ./source/a/bin/scripts/diskcopy
gzip ./source/a/acl/acl.destdir.diff
gzip ./source/a/lha/lha_1.14i-10.1.diff
gzip ./source/a/bash/doinst.sh
gzip ./source/a/tcsh/tcsh.nobuiltincolorls.diff
gzip ./source/a/tcsh/doinst.sh
gzip ./source/a/elvis/elvis.ref.c.getline.diff
gzip ./source/a/dbus/dbus-1.4.x-allow_root_globally.diff
gzip ./source/a/dbus/rc.messagebus
gzip ./source/a/dbus/doinst.sh
gzip ./source/a/usb_modeswitch/device_reference.txt
gzip ./source/a/usb_modeswitch/doinst.sh
gzip ./source/a/minicom/minicom.users
gzip ./source/a/minicom/lrzsz_0.12.21-5.diff
gzip ./source/a/minicom/config.sub-x86_64.diff
gzip ./source/a/minicom/doinst.sh
gzip ./source/a/sysvinit-scripts/doinst.sh
gzip ./source/a/acpid/rc.acpid
gzip ./source/a/acpid/default
gzip ./source/a/acpid/doinst.sh
gzip ./source/a/acpid/acpi_handler.sh
gzip ./source/a/utempter/doinst.sh
gzip ./source/a/lvm2/doinst.sh
gzip ./source/a/lvm2/build_with_udev_165_and_later.diff
gzip ./source/a/sysvinit-functions/doinst.sh
gzip ./source/a/logrotate/logrotate.conf
gzip ./source/a/logrotate/logrotate.cron
gzip ./source/a/logrotate/doinst.sh
gzip ./source/a/logrotate/logrotate.slackware.diff
gzip ./source/a/etc/nsswitch.conf
gzip ./source/a/etc/termcap-BSD
gzip ./source/a/file/file.short.diff
gzip ./source/a/file/file.crdaregbin.magic
gzip ./source/a/file/file.zisofs.magic
gzip ./source/a/file/file.quiet.diff
gzip ./source/a/file/file.etc.file.diff
gzip ./source/a/file/file.xz.magic
gzip ./source/a/pciutils/pciutils.ids.dest.diff
gzip ./source/a/tar/tar-1.2x.support_txz.diff
gzip ./source/a/tar/tar.nolonezero.diff
gzip ./source/a/tar/tar.norecordsizespam.diff
gzip ./source/a/tar/rmt.8
gzip ./source/a/tar/tar.1
gzip ./source/a/tar/tar-1.13.bzip2.diff
gzip ./source/a/less/less.sysconfdir.diff
gzip ./source/a/less/lesspipe.sh
gzip ./source/a/lrzip/doinst.sh
gzip ./source/a/util-linux/setserial-undef_TIOCGHAYESESP.diff
gzip ./source/a/util-linux/util-linux.fdisk-no-solaris.diff
gzip ./source/a/util-linux/adjtimex_1.23-1.diff
gzip ./source/a/util-linux/setserial-rc.serial.diff
gzip ./source/a/util-linux/ziptool-fix_build.patch
gzip ./source/a/util-linux/doinst.sh
gzip ./source/a/util-linux/net-tools.diff
gzip ./source/a/util-linux/net-tools_1.60-19.diff
gzip ./source/a/floppy/fdutils-5.4-20020222.diff
gzip ./source/a/floppy/fdutils.mediaprm.diff
gzip ./source/a/gpm/inputattach.c
gzip ./source/a/gpm/gpm-1.20.1-math.patch
gzip ./source/a/gpm/gpm-evdev-cumulative.patch
gzip ./source/a/gpm/gpm-1.20.1-no-console-error.patch
gzip ./source/a/gpm/mouseconfig
gzip ./source/a/gpm/gpm-1.20.1-input-defines.diff
gzip ./source/a/gpm/setup.mouse
gzip ./source/a/gpm/gpm-1.20.1-gpmopen.patch
gzip ./source/a/gpm/gpm-1.20.1.send-noise-to-syslogs.diff
gzip ./source/a/gpm/gpm-1.20.1-multilib.patch
gzip ./source/a/gpm/gpm-1.20.1-idie.patch
gzip ./source/a/gpm/gpm.evdevmakefile.patch
gzip ./source/a/gpm/gpm-1.20.1-consolename.patch
gzip ./source/a/gpm/gpm-1.20.1-lib-silent.patch
gzip ./source/a/gpm/gpm-1.20.1-weak-wgetch.patch
gzip ./source/a/gpm/gpm-1.20.1-nodebug.patch
gzip ./source/a/gpm/gpm-1.20.1-input.patch
gzip ./source/a/gpm/gpm-1.20.1-subscript.patch
gzip ./source/a/shadow/patches/r3160.diff
gzip ./source/a/shadow/patches/r3055.diff
gzip ./source/a/shadow/patches/r3299.diff
gzip ./source/a/shadow/patches/r3062.diff
gzip ./source/a/shadow/patches/r3054.diff
gzip ./source/a/shadow/patches/r3060.diff
gzip ./source/a/shadow/patches/r3096.diff
gzip ./source/a/shadow/patches/r3194.diff
gzip ./source/a/shadow/useradd
gzip ./source/a/shadow/login.defs
gzip ./source/a/shadow/doinst.sh
gzip ./source/a/libcgroup/libcgroup.conf.diff
gzip ./source/a/libcgroup/libcgroup.init.diff
gzip ./source/a/libcgroup/doinst.sh
gzip ./source/a/bzip2/bzip2.saneso.diff
gzip ./source/a/e2fsprogs/doinst.sh
gzip ./source/a/smartmontools/doinst.sh
gzip ./source/a/usbutils/usbutils.ids.dest
gzip ./source/a/dcron/defs.h.TMPDIR.diff
gzip ./source/a/dcron/run-parts.8
gzip ./source/a/dcron/crontab.c.O_EXCL.diff
gzip ./source/a/dcron/dcron.manpage.paths.diff
gzip ./source/a/dcron/crontab.root
gzip ./source/a/dcron/doinst.sh
gzip ./source/a/dcron/run-parts
gzip ./source/a/getty-ps/getty.bugfixes.diff
gzip ./source/a/sysvinit/sysvinit.pidof.rhforkseverything.diff
gzip ./source/a/sysvinit/doinst.sh
gzip ./source/a/sysvinit/sysvinit.diff
gzip ./source/a/sysvinit/sysvinit-2.86-timeval.patch
gzip ./source/a/dosfstools/dosfstools.paths.diff
gzip ./source/a/sysklogd/use_memmove_not_strcpy.diff
gzip ./source/a/sysklogd/doinst.sh
gzip ./source/a/udev/rule_generator.diff
gzip ./source/a/udev/udev.git-560de575148b7efda3b34a7f7073abd483c5f08e.patch
gzip ./source/a/udev/doinst.sh
gzip ./source/a/eject/eject.spaces.diff
gzip ./source/a/genpower/genpower.halt.diff
gzip ./source/a/genpower/genpower.var.diff
gzip ./source/a/lilo/lilo.use_major_minor_instead_lvm_name.diff
gzip ./source/a/procps/procps-3.2.7-ps-cgroup.patch
gzip ./source/a/procps/procinfo.gcc3.diff
gzip ./source/a/procps/procps.nowarning.diff
gzip ./source/a/procps/procps-3.2.8-ps-cgroup-suppress-root-group.patch
gzip ./source/a/procps/procps-3.2.8.unknown.hz.value.diff
gzip ./source/a/procps/procps.w.showfrom.diff
gzip ./source/a/procps/procps-3.2.7-ps-eip64.diff
gzip ./source/a/coreutils/DIR_COLORS
gzip ./source/a/coreutils/coreutils-dircolors.csh
gzip ./source/a/coreutils/coreutils.uname.diff
gzip ./source/a/coreutils/doinst.sh
gzip ./source/a/coreutils/coreutils-dircolors.sh
gzip ./source/a/mt-st/mt-st.man.diff
gzip ./source/a/mt-st/mt-st.config.diff
gzip ./source/a/mt-st/mt-st.sdlt.diff
gzip ./source/a/cups/usb-backend-both-usblp-and-libusb.dpatch
gzip ./source/a/cups/cups.fix_broken_locking.diff
gzip ./source/a/cups/doinst.sh
gzip ./source/a/devs/makedev_2.3.1-46.2.diff
gzip ./source/a/devs/makedev_2.3.1.slack.diff
gzip ./source/a/devs/makedev_2.3.1.hd.diff
gzip ./source/a/devs/makedev.hd.diff
gzip ./source/a/rpm2tgz/patches/0003-allow-every-user-to-use-rpm2tgz.patch
gzip ./source/a/rpm2tgz/patches/0004-produce-more-compliant-slack-desc.patch
gzip ./source/a/rpm2tgz/patches/0009-Add-c-option-just-as-makepkg-c-y.patch
gzip ./source/a/rpm2tgz/patches/0005-gzip-man-info-pages.patch
gzip ./source/a/rpm2tgz/patches/0006-should-we-use-.txz-format-in-slackware-current.patch
gzip ./source/a/rpm2tgz/patches/0002-fix-spurious-path-to-rpm-file-with-n-option.patch
gzip ./source/a/rpm2tgz/patches/0007-Add-support-for-.txz-packages-and-rpm2txz-symlink.patch
gzip ./source/a/rpm2tgz/patches/0008-Avoid-none-values-in-slack-desc.patch
gzip ./source/a/rpm2tgz/patches/0001-fix-d-handling.patch
gzip ./source/a/mdadm/mdadm.static.diff
gzip ./source/a/mdadm/doinst.sh
gzip ./source/a/findutils/findutils.no.default.options.warnings.diff
gzip ./source/a/findutils/findutils.nolocate.diff
gzip ./source/a/attr/attr.destdir.diff
gzip ./source/a/module-init-tools/modprobe.ignore_some_suffixes.diff
gzip ./source/a/module-init-tools/doinst.sh
gzip ./source/a/unarj/Makefile
gzip ./source/n/httpd/httpd.nossldefault.diff
gzip ./source/n/httpd/httpd.brigade_move.__noinline__.gcc451.diff
gzip ./source/n/httpd/config.layout.diff
gzip ./source/n/httpd/httpd.runasapache.diff
gzip ./source/n/httpd/doinst.sh
gzip ./source/n/dnsmasq/dnsmasq.leasedir.diff
gzip ./source/n/dnsmasq/rc.dnsmasq
gzip ./source/n/dnsmasq/doinst.sh
gzip ./source/n/portmap/rc.rpc
gzip ./source/n/portmap/doinst.sh
gzip ./source/n/portmap/portmap.lwrap.needs.lnsl.diff
gzip ./source/n/htdig/htdig.conf.diff
gzip ./source/n/htdig/htdig-3.2.0b6.diff
gzip ./source/n/htdig/doinst.sh
gzip ./source/n/lftp/doinst.sh
gzip ./source/n/irssi/irssi.ssl_proxy.diff
gzip ./source/n/irssi/irssi.manpage_fix.diff
gzip ./source/n/irssi/doinst.sh
gzip ./source/n/openssh/doinst.sh
gzip ./source/n/bluez/patches/bluez-dbus-config.patch
gzip ./source/n/bluez/patches/bluez-run_udev_helper.patch
gzip ./source/n/bluez/patches/bluez-unbreak_dell_mouse.patch
gzip ./source/n/bluez/doinst.sh
gzip ./source/n/mailx/doinst.sh
gzip ./source/n/nfs-utils/nfs-utils.lwrap.needs.lnsl.diff
gzip ./source/n/nfs-utils/doinst.sh
gzip ./source/n/network-scripts/doinst.sh
gzip ./source/n/netkit-timed/netkit-timed-0.17.diff
gzip ./source/n/ytalk/doinst.sh
gzip ./source/n/stunnel/doinst.sh
gzip ./source/n/netatalk/netatalk.etc2ps.diff
gzip ./source/n/netatalk/netatalk.afpdconf.diff
gzip ./source/n/netatalk/doinst.sh
gzip ./source/n/netatalk/netatalk.without_xfs.diff
gzip ./source/n/icmpinfo/icmpinfo-1.11.diff
gzip ./source/n/netwrite/netwrite-0.17.diff
gzip ./source/n/bsd-finger/bsd-finger-0.17.diff
gzip ./source/n/netkit-routed/routed.18.candidate.final.patch
gzip ./source/n/netkit-routed/netkit-routed-0.17.diff
gzip ./source/n/net-tools/net-tools_1.60-23.diff
gzip ./source/n/net-tools/net-tools.struct.x25_address.gcc4.diff
gzip ./source/n/net-tools/net-tools.switch.default.gcc4.diff
gzip ./source/n/net-tools/net-tools.diff
gzip ./source/n/net-tools/net-tools.mii-tool.string.diff
gzip ./source/n/inetd/inetd.loopingdos.diff
gzip ./source/n/inetd/inetd-OpenBSD-1.79.diff
gzip ./source/n/openldap-client/doinst.sh
gzip ./source/n/netwatch/netwatch.makefile.diff
gzip ./source/n/netwatch/netwatch.phonemyself.diff
gzip ./source/n/wpa_supplicant/hostap-07.git-b80b5639935d37b95d00f86b57f2844a9c775f57.patch
gzip ./source/n/nmap/nmap.ndiff.mandir.diff
gzip ./source/n/procmail/procmail_3.22-5.diff
gzip ./source/n/procmail/procmail.lfs.diff
gzip ./source/n/rp-pppoe/doinst.sh
gzip ./source/n/pidentd/pidentd.conf.diff
gzip ./source/n/pidentd/doinst.sh
gzip ./source/n/dhcpcd/COPYRIGHT
gzip ./source/n/dhcpcd/50-ntp.conf.diff
gzip ./source/n/dhcpcd/doinst.sh
gzip ./source/n/sendmail/Build
gzip ./source/n/popa3d/popa3d.diff
gzip ./source/n/popa3d/doinst.sh
gzip ./source/n/nc/nc-110-21.diff
gzip ./source/n/nc/nc.diff
gzip ./source/n/dhcp/doinst.sh
gzip ./source/n/dhcp/dhclient-script.PATH.diff
gzip ./source/n/rdist/rdist-6.1.5-06.maxargs.diff
gzip ./source/n/rdist/rdist-6.1.5-04.bison.diff
gzip ./source/n/rdist/rdist-6.1.5-05.varargs.diff
gzip ./source/n/rdist/rdist-6.1.5-10.ssh.diff
gzip ./source/n/rdist/rdist-6.1.5-01.links.diff
gzip ./source/n/rdist/rdist-6.1.5-07.lfs.diff
gzip ./source/n/rdist/rdist-6.1.5-12.stat64.diff
gzip ./source/n/rdist/rdist-6.1.5-00.linux.diff
gzip ./source/n/rdist/rdist-6.1.5-11.mkstemp.diff
gzip ./source/n/rdist/rdist-6.1.5-08.cleanup.diff
gzip ./source/n/rdist/rdist-6.1.5-14.fix-msgsndnotify-loop.diff
gzip ./source/n/rdist/rdist-6.1.5-03.hardlink.diff
gzip ./source/n/rdist/rdist-6.1.5-09.svr4.diff
gzip ./source/n/netdate/netdate.diff
gzip ./source/n/netdate/netdate.diff2
gzip ./source/n/wget/doinst.sh
gzip ./source/n/gpa/doinst.sh
gzip ./source/n/samba/doinst.sh
gzip ./source/n/samba/smb.conf.diff
gzip ./source/n/php/php.session.save_path.diff
gzip ./source/n/php/php.ini-development.diff
gzip ./source/n/php/doinst.sh
gzip ./source/n/alpine/alpine.manpage.diff
gzip ./source/n/alpine/alpine.config.h.diff
gzip ./source/n/alpine/alpine.tech-notes.txt.diff
gzip ./source/n/alpine/pinepgp-0.18.0-makefile-sed-fix.diff
gzip ./source/n/alpine/pinepgp.pinegpgp.in.diff
gzip ./source/n/obex-data-server/doinst.sh
gzip ./source/n/nn/nn.diff
gzip ./source/n/nn/nntpserver
gzip ./source/n/nn/nn.destdir.diff
gzip ./source/n/nn/m-x86_64.h
gzip ./source/n/nn/nn.badnntphost.diff
gzip ./source/n/nn/doinst.sh
gzip ./source/n/nn/NNTP
gzip ./source/n/net-snmp/snmpd.conf
gzip ./source/n/net-snmp/net-snmp.net-snmp-create-v3-user.etc.snmpd.conf.diff
gzip ./source/n/net-snmp/doinst.sh
gzip ./source/n/trn/config.sh
gzip ./source/n/trn/config.x86_64.sh
gzip ./source/n/iproute2/iproute2.fixup_dbpath_and_iptablespath.diff
gzip ./source/n/iproute2/doinst.sh
gzip ./source/n/biff+comsat/biff+comsat.offset.diff
gzip ./source/n/biff+comsat/biff+comsat-0.17.diff
gzip ./source/n/biff+comsat/biff+comsat.badutmp.diff
gzip ./source/n/telnet/netkit-telnet-0.17.diff
gzip ./source/n/telnet/telnet-OpenBSD-014_telnet.diff
gzip ./source/n/telnet/netkit-telnet-0.17-ayt.patch
gzip ./source/n/telnet/telnet-OpenBSD-20020321.diff
gzip ./source/n/bootp/bootptab
gzip ./source/n/bootp/bootp_2.4.3-15.diff
gzip ./source/n/bridge-utils/bridge-utils.isbridge.diff
gzip ./source/n/netkit-rwho/rwhod_getloadavg.diff
gzip ./source/n/netkit-rwho/netkit-rwho-0.17.diff
gzip ./source/n/mutt/mutt.gpgme.diff
gzip ./source/n/mutt/doinst.sh
gzip ./source/n/bind/bind.so_bsdcompat.diff
gzip ./source/n/bind/doinst.sh
gzip ./source/n/openssl/openssl.optsx86.diff
gzip ./source/n/openssl/openssl.soname.diff
gzip ./source/n/openssl/doinst.sh-openssl
gzip ./source/n/openssl/doinst.sh-openssl-solibs
gzip ./source/n/openssl/certwatch
gzip ./source/n/metamail/metamail.uue.getline.diff
gzip ./source/n/wireless-tools/wireless_tools.nowhine.diff
gzip ./source/n/wireless-tools/doinst.sh
gzip ./source/n/wireless-tools/wireless_tools.static.diff
gzip ./source/n/yptools/rc.yp
gzip ./source/n/yptools/nsswitch.conf-nis
gzip ./source/n/lynx/lynx.path.diff
gzip ./source/n/lynx/lynx.cfg.diff
gzip ./source/n/ppp/pppsetup-1.98.slack.diff
gzip ./source/n/ppp/realms
gzip ./source/n/ppp/servers
gzip ./source/n/ppp/pppsetup-1.98.pppoff.diff
gzip ./source/n/ppp/options.new
gzip ./source/n/ppp/ppp.slack.diff
gzip ./source/n/ppp/pppsetup-1.98.backupfiles.diff
gzip ./source/n/ppp/doinst.sh
gzip ./source/n/ppp/pppsetup-1.98.moredevs.diff
gzip ./source/n/ppp/radius.msdict
gzip ./source/n/autofs/autofs-5.0.5-fix-libxml2-workaround-configure.patch
gzip ./source/n/autofs/doinst.sh
gzip ./source/n/obexftp/ruby_rstringlen.diff
gzip ./source/n/ca-certificates/cacerts-20090814-remove_debconf.diff
gzip ./source/n/ca-certificates/cacerts-20090814-fixup_update-ca-certificates.diff
gzip ./source/n/ca-certificates/cacerts-20090814-fixup_DESTDIR.diff
gzip ./source/n/ca-certificates/doinst.sh
gzip ./source/n/cyrus-sasl/rc.saslauthd
gzip ./source/n/cyrus-sasl/doinst.sh
gzip ./source/n/vsftpd/vsftpd.log
gzip ./source/n/vsftpd/vsftpd.conf.diff
gzip ./source/n/vsftpd/doinst.sh
gzip ./source/n/vsftpd/vsftpd.builddefs.diff
gzip ./source/n/netkit-rusers/netkit-rusers-0.17.diff
gzip ./source/n/slrn/doinst.sh
gzip ./source/n/uucp/policy.h.diff
gzip ./source/n/proftpd/doinst.sh
gzip ./source/n/netkit-ntalk/netkit-ntalk-0.11.diff
gzip ./source/n/netkit-ntalk/ntalk-0.17-slackware-alt-talkd.patch
gzip ./source/n/netkit-ntalk/netkit-ntalk-0.17.diff
gzip ./source/n/ntp/ntp.nano.diff
gzip ./source/n/ntp/doinst.sh
gzip ./source/kdei/kde-l10n/kdepim-l10n/kdepim-l10n-fr-4.4.5.korganizer.docbook.reorganize.diff
gzip ./source/installer/dhcpcd/config.h.diff
gzip ./source/installer/dhcpcd/dhcpcd.sh.diff
gzip ./source/installer/busybox.2.6.32.2.diff
gzip ./source/ap/hplip/doinst.sh
gzip ./source/ap/xfsdump/xfsdump.destdir.diff
gzip ./source/ap/sysstat/doinst.sh
gzip ./source/ap/ghostscript-fonts-std/doinst.sh
gzip ./source/ap/groff/groff.man.mdoc.local
gzip ./source/ap/cdrtools/doinst.sh
gzip ./source/ap/diffutils/doinst.sh
gzip ./source/ap/diffutils/diffutils-sdiff-no-waitpid.patch
gzip ./source/ap/acct/acct.logdir.fhs.diff
gzip ./source/ap/amp/amp-gcc34.diff
gzip ./source/ap/ispell/ispell.diff
gzip ./source/ap/seejpeg/seejpeg-1.10.diff
gzip ./source/ap/libx86/lrmi.c.diff
gzip ./source/ap/man-pages/doinst.sh
gzip ./source/ap/alsa-utils/alsa-utils.alsaconf.diff
gzip ./source/ap/alsa-utils/rc.alsa
gzip ./source/ap/alsa-utils/doinst.sh
gzip ./source/ap/workbone/workbone_2.40-9.diff
gzip ./source/ap/workbone/workbone.1.diff
gzip ./source/ap/sudo/doinst.sh
gzip ./source/ap/dvd+rw-tools/dvd+rw-tools.limits.h.diff
gzip ./source/ap/texinfo/dir
gzip ./source/ap/texinfo/doinst.sh
gzip ./source/ap/jove/jove.makefile.diff
gzip ./source/ap/sc/sc-7.16-3.diff
gzip ./source/ap/man/man-1.6f.nroff.mandoc.diff
gzip ./source/ap/man/doinst.sh
gzip ./source/ap/madplay/madplay-0.15.2b-fix-segfault.patch
gzip ./source/ap/ash/patches/ash-freebsd.patch
gzip ./source/ap/ash/patches/ash-setmode.patch
gzip ./source/ap/ash/patches/ash-syntax.patch
gzip ./source/ap/ash/patches/ash-makefile.patch
gzip ./source/ap/ash/patches/ash-kill.patch
gzip ./source/ap/ash/patches/ash-test.patch
gzip ./source/ap/ash/patches/ash-echo.patch
gzip ./source/ap/ash/patches/ash-debian.patch
gzip ./source/ap/ash/patches/ash-getcwd.patch
gzip ./source/ap/ash/patches/ash-getopt.patch
gzip ./source/ap/ash/patches/ash-hetio.patch
gzip ./source/ap/ash/patches/ash-glob.patch
gzip ./source/ap/ash/patches/ash-manpage.patch
gzip ./source/ap/ash/patches/ash-ppid.patch
gzip ./source/ap/ash/patches/ash-times.patch
gzip ./source/ap/ash/patches/ash-sighup.patch
gzip ./source/ap/ash/patches/ash-memout.patch
gzip ./source/ap/ash/patches/ash-misc.patch
gzip ./source/ap/ash/patches/ash-builtin.patch
gzip ./source/ap/ash/patches/ash-redir.patch
gzip ./source/ap/ash/patches/ash-jobs.patch
gzip ./source/ap/dmidecode/dmidecode.makefile.diff
gzip ./source/ap/cdparanoia/cdparanoia-III-10.2_cdda_private.patch
gzip ./source/ap/pm-utils/fix-wrong-path-in-intel-audio-powersave.patch
gzip ./source/ap/pm-utils/use_more_sane_harddrive_defaults.patch
gzip ./source/ap/sqlite/COPYRIGHT
gzip ./source/ap/ghostscript/cidfmap
gzip ./source/ap/ghostscript/ghostscript.rev11948.diff
gzip ./source/ap/dmapi/dmapi.destdir.diff
gzip ./source/ap/rpm/doinst.sh
gzip ./source/ap/rpm/Packages
gzip ./source/ap/at/doinst.sh
gzip ./source/ap/mysql/rc.mysqld
gzip ./source/ap/mysql/doinst.sh
gzip ./source/ap/mc/mc.ext.in.geeqie.diff
gzip ./source/ap/foomatic-filters/doinst.sh
gzip ./source/ap/zsh/zsh.regex.oh.bah.diff
gzip ./source/ap/zsh/doinst.sh
gzip ./source/ap/flac/flac.gcc45.diff
gzip ./source/ap/flac/flac.man.diff
gzip ./source/ap/vim/patches/7.3.115
gzip ./source/ap/vim/patches/7.3.039
gzip ./source/ap/vim/patches/7.3.013
gzip ./source/ap/vim/patches/7.3.112
gzip ./source/ap/vim/patches/7.3.090
gzip ./source/ap/vim/patches/7.3.034
gzip ./source/ap/vim/patches/7.3.054
gzip ./source/ap/vim/patches/7.3.061
gzip ./source/ap/vim/patches/7.3.101
gzip ./source/ap/vim/patches/7.3.011
gzip ./source/ap/vim/patches/7.3.131
gzip ./source/ap/vim/patches/7.3.153
gzip ./source/ap/vim/patches/7.3.110
gzip ./source/ap/vim/patches/7.3.150
gzip ./source/ap/vim/patches/7.3.002
gzip ./source/ap/vim/patches/7.3.059
gzip ./source/ap/vim/patches/7.3.089
gzip ./source/ap/vim/patches/7.3.132
gzip ./source/ap/vim/patches/7.3.117
gzip ./source/ap/vim/patches/7.3.111
gzip ./source/ap/vim/patches/7.3.074
gzip ./source/ap/vim/patches/7.3.024
gzip ./source/ap/vim/patches/7.3.038
gzip ./source/ap/vim/patches/7.3.069
gzip ./source/ap/vim/patches/7.3.104
gzip ./source/ap/vim/patches/7.3.124
gzip ./source/ap/vim/patches/7.3.085
gzip ./source/ap/vim/patches/7.3.068
gzip ./source/ap/vim/patches/7.3.100
gzip ./source/ap/vim/patches/7.3.077
gzip ./source/ap/vim/patches/7.3.136
gzip ./source/ap/vim/patches/7.3.120
gzip ./source/ap/vim/patches/7.3.071
gzip ./source/ap/vim/patches/7.3.129
gzip ./source/ap/vim/patches/7.3.137
gzip ./source/ap/vim/patches/7.3.062
gzip ./source/ap/vim/patches/7.3.116
gzip ./source/ap/vim/patches/7.3.144
gzip ./source/ap/vim/patches/7.3.064
gzip ./source/ap/vim/patches/7.3.093
gzip ./source/ap/vim/patches/7.3.032
gzip ./source/ap/vim/patches/7.3.008
gzip ./source/ap/vim/patches/7.3.004
gzip ./source/ap/vim/patches/7.3.126
gzip ./source/ap/vim/patches/7.3.147
gzip ./source/ap/vim/patches/7.3.138
gzip ./source/ap/vim/patches/7.3.006
gzip ./source/ap/vim/patches/7.3.028
gzip ./source/ap/vim/patches/7.3.073
gzip ./source/ap/vim/patches/7.3.081
gzip ./source/ap/vim/patches/7.3.113
gzip ./source/ap/vim/patches/7.3.010
gzip ./source/ap/vim/patches/7.3.088
gzip ./source/ap/vim/patches/7.3.005
gzip ./source/ap/vim/patches/7.3.070
gzip ./source/ap/vim/patches/7.3.094
gzip ./source/ap/vim/patches/7.3.001
gzip ./source/ap/vim/patches/7.3.146
gzip ./source/ap/vim/patches/7.3.029
gzip ./source/ap/vim/patches/7.3.140
gzip ./source/ap/vim/patches/7.3.119
gzip ./source/ap/vim/patches/7.3.060
gzip ./source/ap/vim/patches/7.3.036
gzip ./source/ap/vim/patches/7.3.035
gzip ./source/ap/vim/patches/7.3.103
gzip ./source/ap/vim/patches/7.3.122
gzip ./source/ap/vim/patches/7.3.123
gzip ./source/ap/vim/patches/7.3.018
gzip ./source/ap/vim/patches/7.3.106
gzip ./source/ap/vim/patches/7.3.154
gzip ./source/ap/vim/patches/7.3.040
gzip ./source/ap/vim/patches/7.3.086
gzip ./source/ap/vim/patches/7.3.053
gzip ./source/ap/vim/patches/7.3.072
gzip ./source/ap/vim/patches/7.3.075
gzip ./source/ap/vim/patches/7.3.056
gzip ./source/ap/vim/patches/7.3.026
gzip ./source/ap/vim/patches/7.3.003
gzip ./source/ap/vim/patches/7.3.145
gzip ./source/ap/vim/patches/7.3.127
gzip ./source/ap/vim/patches/7.3.067
gzip ./source/ap/vim/patches/7.3.102
gzip ./source/ap/vim/patches/7.3.015
gzip ./source/ap/vim/patches/7.3.019
gzip ./source/ap/vim/patches/7.3.151
gzip ./source/ap/vim/patches/7.3.044
gzip ./source/ap/vim/patches/7.3.091
gzip ./source/ap/vim/patches/7.3.142
gzip ./source/ap/vim/patches/7.3.021
gzip ./source/ap/vim/patches/7.3.017
gzip ./source/ap/vim/patches/7.3.050
gzip ./source/ap/vim/patches/7.3.105
gzip ./source/ap/vim/patches/7.3.114
gzip ./source/ap/vim/patches/7.3.118
gzip ./source/ap/vim/patches/7.3.048
gzip ./source/ap/vim/patches/7.3.009
gzip ./source/ap/vim/patches/7.3.007
gzip ./source/ap/vim/patches/7.3.037
gzip ./source/ap/vim/patches/7.3.012
gzip ./source/ap/vim/patches/7.3.141
gzip ./source/ap/vim/patches/7.3.109
gzip ./source/ap/vim/patches/7.3.125
gzip ./source/ap/vim/patches/7.3.087
gzip ./source/ap/vim/patches/7.3.148
gzip ./source/ap/vim/patches/7.3.023
gzip ./source/ap/vim/patches/7.3.033
gzip ./source/ap/vim/patches/7.3.065
gzip ./source/ap/vim/patches/7.3.084
gzip ./source/ap/vim/patches/7.3.041
gzip ./source/ap/vim/patches/7.3.057
gzip ./source/ap/vim/patches/7.3.027
gzip ./source/ap/vim/patches/7.3.016
gzip ./source/ap/vim/patches/7.3.049
gzip ./source/ap/vim/patches/7.3.052
gzip ./source/ap/vim/patches/7.3.080
gzip ./source/ap/vim/patches/7.3.134
gzip ./source/ap/vim/patches/7.3.135
gzip ./source/ap/vim/patches/7.3.079
gzip ./source/ap/vim/patches/7.3.096
gzip ./source/ap/vim/patches/7.3.078
gzip ./source/ap/vim/patches/7.3.092
gzip ./source/ap/vim/patches/7.3.108
gzip ./source/ap/vim/patches/7.3.149
gzip ./source/ap/vim/patches/7.3.099
gzip ./source/ap/vim/patches/7.3.043
gzip ./source/ap/vim/patches/7.3.020
gzip ./source/ap/vim/patches/7.3.152
gzip ./source/ap/vim/patches/7.3.082
gzip ./source/ap/vim/patches/7.3.128
gzip ./source/ap/vim/patches/7.3.031
gzip ./source/ap/vim/patches/7.3.022
gzip ./source/ap/vim/patches/7.3.066
gzip ./source/ap/vim/patches/7.3.046
gzip ./source/ap/vim/patches/7.3.042
gzip ./source/ap/vim/patches/7.3.098
gzip ./source/ap/vim/patches/7.3.083
gzip ./source/ap/vim/patches/7.3.051
gzip ./source/ap/vim/patches/7.3.139
gzip ./source/ap/vim/patches/7.3.014
gzip ./source/ap/vim/patches/7.3.063
gzip ./source/ap/vim/patches/7.3.058
gzip ./source/ap/vim/patches/7.3.095
gzip ./source/ap/vim/patches/7.3.055
gzip ./source/ap/vim/patches/7.3.121
gzip ./source/ap/vim/patches/7.3.030
gzip ./source/ap/vim/patches/7.3.097
gzip ./source/ap/vim/patches/7.3.143
gzip ./source/ap/vim/patches/7.3.130
gzip ./source/ap/vim/patches/7.3.045
gzip ./source/ap/vim/patches/7.3.076
gzip ./source/ap/vim/patches/7.3.107
gzip ./source/ap/vim/patches/7.3.025
gzip ./source/ap/vim/patches/7.3.133
gzip ./source/ap/vim/patches/7.3.047
gzip ./source/ap/vim/vim-runtime-syntax-20110328.diff
gzip ./source/ap/vim/vim.vimrc.diff
gzip ./source/ap/vim/doinst.sh
gzip ./source/ap/a2ps/a2ps.diff
gzip ./source/ap/a2ps/psutils.destdir.diff
gzip ./source/ap/a2ps/psutils.diff
gzip ./source/ap/a2ps/a2ps.a2ps_cfg.in.diff
gzip ./source/ap/lm_sensors/lm_sensors.makefile.diff
gzip ./source/d/autoconf/doinst.sh
gzip ./source/d/oprofile/oprofile.qt4.diff
gzip ./source/d/mercurial/doinst.sh
gzip ./source/d/libtool/libtool.no.moved.warning.diff
gzip ./source/d/libtool/doinst.sh
gzip ./source/d/rcs/rcs-5.7.diff
gzip ./source/d/dev86/dev86-x86_64.noelks.patch
gzip ./source/d/dev86/dev86-x86_64.patch
gzip ./source/d/automake/doinst.sh
gzip ./source/d/python/python.readline.set_pre_input_hook.diff
gzip ./source/d/python/python.pure64.diff
gzip ./source/d/python/python.x86_64.diff
gzip ./source/d/pmake/pmake.strerror.strdup.diff
gzip ./source/d/pmake/pmake.txt
gzip ./source/d/pmake/pmake_1.111-1.diff
gzip ./source/d/pkg-config/doinst.sh
gzip ./source/d/gcc/fastjar-patches/1004-fastjar-man.patch
gzip ./source/d/gcc/fastjar-patches/1002-fastjar-0.97-filename0.patch
gzip ./source/d/gcc/fastjar-patches/1000-fastjar-0.97-segfault.patch
gzip ./source/d/gcc/fastjar-patches/1001-fastjar-0.97-len1.patch
gzip ./source/d/gcc/fastjar-patches/1003-fastjar-CVE-2010-0831.patch
gzip ./source/d/gcc/gcc-no_fixincludes.diff
gzip ./source/d/p2c/p2c_1.21alpha2-2.1.diff
gzip ./source/d/p2c/p2c.examples.diff
gzip ./source/d/p2c/p2c_time.diff
gzip ./source/d/perl/perl.configure.multilib.patch
gzip ./source/xap/rxvt/rxvt.utempter.diff
gzip ./source/xap/xmms/xmms.gtk.doublesize.diff
gzip ./source/xap/xmms/xmms.wmxmms_vis_depth_workaround.diff
gzip ./source/xap/gftp/gftp.desktop
gzip ./source/xap/gv/gv.keysym.diff
gzip ./source/xap/xfce/patches/xfce-utils.xinitrc.consolekit.diff
gzip ./source/xap/xfce/patches/xfce-utils-load_systemwide_Xmodmap.diff
gzip ./source/xap/xfce/patches/Thunar.thunar-vfs-io-local.diff
gzip ./source/xap/xfce/patches/thunar-1.0.2-fixup_docdir.diff
gzip ./source/xap/xfce/patches/xfsm-compat-kde.c-start-kde4-services.diff
gzip ./source/xap/xfce/patches/xfdesktop-fix_education_icon.diff
gzip ./source/xap/xfce/patches/xfcalendar.desktop.in.diff
gzip ./source/xap/xfce/patches/fixup_comments_in_xfce-utils-Xft.xrdb.diff
gzip ./source/xap/xfce/patches/mousepad-fix_find.diff
gzip ./source/xap/xfce/patches/mousepad-fix_find_and_replace.diff
gzip ./source/xap/xfce/patches/no_sensitive_panel_during_plugin_moves.patch
gzip ./source/xap/xfce4-notifyd/doinst.sh
gzip ./source/xap/fluxbox/xinitrc.fluxbox
gzip ./source/xap/mozilla-thunderbird/mimeTypes.rdf
gzip ./source/xap/xine-ui/xine.desktop
gzip ./source/xap/xine-ui/xine-ui.png14.diff
gzip ./source/xap/xfce4-power-manager/doinst.sh
gzip ./source/xap/geeqie/doinst.sh
gzip ./source/xap/gkrellm/gkrellm.theme.defaults.diff
gzip ./source/xap/x3270/doinst.sh
gzip ./source/xap/blackbox/blackbox-0.70.1-gcc-4.3.patch
gzip ./source/xap/blackbox/xinitrc.blackbox
gzip ./source/xap/windowmaker/windowmaker.no-mmx.diff
gzip ./source/xap/windowmaker/windowmaker.png.1.4.0.diff
gzip ./source/xap/windowmaker/wmaker.inst.diff
gzip ./source/xap/windowmaker/xinitrc.wmaker
gzip ./source/xap/audacious/doinst.sh
gzip ./source/xap/electricsheep/electricsheep.mplayer.diff
gzip ./source/xap/gucharmap/doinst.sh
gzip ./source/xap/pidgin/purple-allow-sign-rsa-md5.patch
gzip ./source/xap/xgames/xlander-2009-07-18.diff
gzip ./source/xap/xgames/xcolormap.diff
gzip ./source/xap/xgames/spider.diff
gzip ./source/xap/xgames/xcuckoo.diff
gzip ./source/xap/xgames/maze.diff
gzip ./source/xap/xgames/xlander.fixes.diff
gzip ./source/xap/xscreensaver/setuid.c
gzip ./source/xap/xscreensaver/xscreensaver.setuid.diff
gzip ./source/xap/xscreensaver/xscreensaver.electricsheep.diff
gzip ./source/xap/sane/sane-frontends-1.0.14-sane_cap_always_settable.diff
gzip ./source/xap/sane/doinst.sh
gzip ./source/xap/sane/dll.conf.additions
gzip ./source/xap/seamonkey/doinst.sh
gzip ./source/xap/gnuchess/eboard.assert.diff
gzip ./source/xap/audacious-plugins/audacious-plugins.alsa.noise.is.not.helpful.diff
gzip ./source/xap/xine-lib/xine-lib.XvMClib.h.diff
gzip ./source/xap/blueman/blueman-use_blueman-open_for_obexfs.diff
gzip ./source/xap/blueman/doinst.sh
gzip ./source/xap/xpdf/patches/xpdf-resizefix.diff
gzip ./source/xap/xpdf/patches/xpdfrc.diff
gzip ./source/xap/xpdf/patches/xpdf_3.02-1.3.diff
gzip ./source/xap/xpdf/doinst.sh
gzip ./source/xap/xpdf/lang/xpdf-hebrew.diff
gzip ./source/xap/xpdf/lang/xpdf-thai.diff
gzip ./source/xap/xpdf/lang/xpdf-korean.diff
gzip ./source/xap/xpdf/lang/xpdf-chinese-traditional.diff
gzip ./source/xap/xpdf/lang/xpdf-greek.diff
gzip ./source/xap/xpdf/lang/xpdf-chinese-simplified.diff
gzip ./source/xap/xpdf/lang/xpdf-turkish.diff
gzip ./source/xap/xpdf/lang/xpdf-arabic.diff
gzip ./source/xap/xpdf/lang/xpdf-japanese.diff
gzip ./source/xap/xpdf/lang/xpdf-cyrillic.diff
gzip ./source/xap/xpdf/lang/xpdf-latin2.diff
gzip ./source/xap/seyon/seyon_2.20c-16.diff
gzip ./source/xap/xaos/xaos.6
gzip ./source/xap/xlockmore/xlockmore.bitmap.diff
gzip ./source/xap/fvwm/xinitrc.fvwm2
gzip ./source/xap/fvwm/fvwm.colormap.diff
gzip ./source/xap/fvwm/doinst.sh
gzip ./source/xap/fvwm/system.fvwm2rc
gzip ./source/xap/xv/xv.jasper.diff
gzip ./source/xap/xv/xv.prefix_x86_64.diff
gzip ./source/xap/xv/xv.prefix.diff
gzip ./source/xap/xv/xv-3.10a.patch
gzip ./source/xap/mozilla-firefox/mozilla-firefox-mimeTypes-fix.diff
gzip ./source/xap/mozilla-firefox/firefox.moz_plugin_path.diff
gzip ./source/xap/mozilla-firefox/mimeTypes.rdf
gzip ./source/xap/rdesktop/rdesktop.CVE-2011-1595.diff
gzip ./source/x/xdg-user-dirs/doinst.sh
gzip ./source/x/x11-skel/doinst.sh
gzip ./source/x/scim-bridge/patches/scim-bridge-0.4.16-scim-bridge-agent-application.cpp.patch
gzip ./source/x/scim-bridge/patches/scim-bridge-0.4.16-scim-bridge-client-imcontext-qt.cpp.patch
gzip ./source/x/scim-bridge/patches/scim-bridge-0.4.16-scim-bridge-client-imcontext-gtk.c.patch
gzip ./source/x/scim-bridge/patches/scim-bridge-0.4.16-scim-bridge-agent-imcontext.h.patch
gzip ./source/x/scim-bridge/patches/scim-bridge-0.4.16-scim-bridge-agent.cpp.patch
gzip ./source/x/scim-bridge/patches/scim-bridge-0.4.16-scim-bridge-agent-imcontext.cpp.patch
gzip ./source/x/x11/post-install/xorg-cf-files/x11.tmpl.lib64.kludge.diff
gzip ./source/x/x11/post-install/libX11/XKeysymDB
gzip ./source/x/x11/patch/xorg-server/xorg-server.fb.fbpict.c.mod.diff
gzip ./source/x/x11/patch/xorg-server/x11.startwithblackscreen.diff
gzip ./source/x/x11/patch/xorg-server/xorg-server.try_nouveau.diff
gzip ./source/x/x11/patch/xcompmgr/xcompmgr-follow-icccm-spec.diff
gzip ./source/x/ttf-indic-fonts/ttf-indic-fonts.copyright.diff
gzip ./source/x/ttf-indic-fonts/doinst.sh
gzip ./source/x/scim-hangul/scim-hangul.gcc43.diff
gzip ./source/x/xdg-utils/doinst.sh
gzip ./source/x/liberation-fonts-ttf/doinst.sh
gzip ./source/x/libdrm/libdrm.uint32_t.diff
gzip ./source/x/mesa/patches/i915_fragment_shader_disable.patch
gzip ./source/x/mesa/patches/mesa-7.9-libdrm-2.4.23-nouveau-api.patch
gzip ./source/x/scim-anthy/scim-anthy.gcc43.diff
gzip ./source/x/scim/scim-1.4.9-fix-ltdl.cpp.patch
gzip ./source/x/dejavu-fonts-ttf/doinst.sh
gzip ./source/x/fontconfig/fontconfig.dejavu.diff
gzip ./source/x/fontconfig/doinst.sh
gzip ./source/x/fontconfig/fontconfig.font.dir.list.diff
gzip ./source/x/scim-pinyin/scim-pinyin.gcc43.diff
gzip ./source/t/transfig/transfig.png14.nodither.diff
gzip ./source/t/transfig/transfig.diff
gzip ./source/t/transfig/transfig.3.2.4-gcc4.patch
gzip ./source/t/tetex/tetex.dvipdfm.mkstemp.diff
gzip ./source/t/tetex/tetex.png14.diff
gzip ./source/t/tetex/tetex.cpascal.getline.posix.2008.diff
gzip ./source/t/tetex/tetex.fontcachedirinhome.diff
gzip ./source/t/tetex/tetex.etex.diff
gzip ./source/t/tetex/tetex.tmp.cleanup.diff
gzip ./source/t/tetex/tetex.amstex.fmtutil.diff
gzip ./source/t/tetex/tetex.browsers.diff
gzip ./source/t/tetex/tetex.scripts.mktemp.diff
gzip ./source/t/tetex/tetex.var.fonts.diff
gzip ./source/t/tetex/tetex.CVE-2005-3193.diff
gzip ./source/t/tetex/tetex.afm2tfm.getline.diff
gzip ./source/t/tetex/tetex.leet.diff
gzip ./source/t/xfig/xfig.png14.nodither.diff
gzip ./source/t/xfig/xfig.3.2.4-null.diff
gzip ./source/t/xfig/xfig-3.2.4-mkstemp.diff
gzip ./source/t/xfig/xfig.3.2.3d-international-std-fonts.diff
gzip ./source/t/xfig/xfig.3.2.4-quiet.diff
gzip ./source/t/xfig/xfig.no.pdf.ref.diff
gzip ./source/t/xfig/xfig.3.2.3d-xcolor.diff
gzip ./source/t/xfig/xfig.3.2.4-gcc4.diff
gzip ./source/t/xfig/xfig.fig.ad.diff
gzip ./source/t/xfig/xfig.no.xfig_ref_en.pdf.diff
gzip ./source/t/xfig/xfig.docs.location.diff
gzip ./source/t/xfig/xfig.3.2.3d-xim.diff
gzip ./source/t/xfig/xfig.3.2.4-locale.diff
gzip ./source/t/xfig/xfig.3.2.4.diff
gzip ./source/t/xfig/xfig.3.2.4-urw-fonts.diff
gzip ./source/y/bsd-games/bsd-games.getline.diff
gzip ./source/y/bsd-games/bsd-games.ospeed.diff
gzip ./source/y/bsd-games/bsd-games.config.params.diff
gzip ./source/y/bsd-games/bsd-games.strfile.8.diff
gzip ./source/y/bsd-games/bsd-games.phantasia_install_fix.diff
gzip ./source/y/bsd-games/bsd-games.fortlen.diff
gzip ./source/y/bsd-games/bsd-games.trek-gcc4.diff
gzip ./source/y/bsd-games/hangman-words
gzip ./source/y/bsd-games/bsd-games.pom.diff
gzip ./source/y/bsd-games/bsd-games.fortunepath.diff
gzip ./source/kde/kdeutils/doinst.sh
gzip ./source/kde/kdemultimedia/doinst.sh
gzip ./source/kde/kdeadmin/doinst.sh
gzip ./source/kde/kdeadmin/knetworkconf.diff
gzip ./source/kde/k3b/doinst.sh
gzip ./source/kde/polkit-qt-1/polkit-qt-1.null-checking.diff
gzip ./source/kde/kdeartwork/doinst.sh
gzip ./source/kde/amarok/doinst.sh
gzip ./source/kde/ktorrent/doinst.sh
gzip ./source/kde/kdepim-runtime/doinst.sh
gzip ./source/kde/kaudiocreator/doinst.sh
gzip ./source/kde/kdenetwork/doinst.sh
gzip ./source/kde/kdebindings/pykdeuic4.patch
gzip ./source/kde/kdebindings/kdebindings-ruby-env.h.diff
gzip ./source/kde/kdebindings/kdebindings.1170602.sip_4_11_x.diff
gzip ./source/kde/kdebindings/kdebindings-len-ptr-rfloat.diff
gzip ./source/kde/kdebindings/kdebindings-rubyconfig.h.diff
gzip ./source/kde/kdebase-runtime/doinst.sh
gzip ./source/kde/kdebase-workspace/kdebase-workspace.kdm.server.timeout.diff
gzip ./source/kde/kdebase-workspace/doinst.sh
gzip ./source/kde/kdepimlibs/kdepimlibs-4.5.imap4.cpp.r1216162.diff
gzip ./source/kde/kdetoys/doinst.sh
gzip ./source/kde/kdewebdev/include-tidy.patch
gzip ./source/kde/kdewebdev/doinst.sh
gzip ./source/kde/kdewebdev/kde4-kdewebdev-findtidy.diff
gzip ./source/kde/kdepim/doinst.sh
gzip ./source/kde/kdeedu/doinst.sh
gzip ./source/kde/kdeaccessibility/doinst.sh
gzip ./source/kde/kdeplasma-addons/doinst.sh
gzip ./source/kde/polkit-kde-1/polkit-kde-1.nodrkonqi.diff
gzip ./source/kde/kdegraphics/doinst.sh
gzip ./source/kde/kdebase/konsole_right_click-185466.patch.patch
gzip ./source/kde/kdebase/konsole_right_click-185466.patch
gzip ./source/kde/kdebase/doinst.sh
gzip ./source/kde/skanlite/doinst.sh
gzip ./source/kde/koffice/doinst.sh
gzip ./source/kde/kdegames/doinst.sh
gzip ./source/kde/kdevplatform/doinst.sh
gzip ./source/kde/kdevelop/doinst.sh
gzip ./source/kde/konq-plugins/konq-plugins-4.4.0-qt47.patch
gzip ./source/kde/kdelibs/kdelibs.khtml.CVE-2011-1168.diff
gzip ./source/kde/kdelibs/kdesu-allow_NOPASS_in_suauth.patch
gzip ./source/kde/kdelibs/doinst.sh
gzip ./source/kde/kdelibs/kdelibs.docbook.patch
gzip ./source/kde/kdesdk/doinst.sh
gzip ./source/kde/kopete-cryptography/doinst.sh
gzip ./source/e/emacs/doinst.sh
gzip ./source/tcl/tix/tix.soname.patch
gzip ./source/tcl/tix/tix.tcl8.5.patch
gzip ./source/tcl/expect/expect.exp_main_tk.c.version.require.diff
gzip ./source/tcl/hfsutils/hfsutils.errno.diff
gzip ./source/tcl/tclx/tclx-8.4.configure.diff
gzip ./source/tcl/tclx/tclx-8.4.gcc4.diff
gzip ./source/l/hal/patches/fix_libusb_detection.diff
gzip ./source/l/hal/patches/increase_HAL_PATH_MAX_to_4096.diff
gzip ./source/l/hal/patches/fix-hal-segfault.patch
gzip ./source/l/hal/patches/10-keymap.fdi-restore_zap.diff
gzip ./source/l/hal/patches/ignore_internal_dm_devices.diff
gzip ./source/l/hal/patches/fix_ioperm_arguments.patch
gzip ./source/l/hal/patches/fix-build-with-automake-1.11.1.patch
gzip ./source/l/hal/patches/handle_input.touchpad_explicitly.diff
gzip ./source/l/hal/patches/fix_segfault-dbus_error_init.patch
gzip ./source/l/hal/patches/fix_segfault_in_LIBHAL_FREE_DBUS_ERROR.diff
gzip ./source/l/hal/hal.conf
gzip ./source/l/hal/doinst.sh
gzip ./source/l/hal/rc.hald
gzip ./source/l/ncurses/ncurses.mkhashsize.diff
gzip ./source/l/shared-mime-info/doinst.sh
gzip ./source/l/loudmouth/loudmouth.async_assertion.diff
gzip ./source/l/loudmouth/loudmouth.gnutls.configure.ac.diff
gzip ./source/l/loudmouth/loudmouth.stanzadrop.diff
gzip ./source/l/loudmouth/loudmouth.sasl-md5-digest-uri.diff
gzip ./source/l/loudmouth/loudmouth.crtpath.diff
gzip ./source/l/db42/patch.4.2.52.2
gzip ./source/l/db42/patch.4.2.52.1
gzip ./source/l/db42/patch.4.2.52.4
gzip ./source/l/db42/patch.4.2.52.3
gzip ./source/l/hicolor-icon-theme/doinst.sh
gzip ./source/l/svgalib/svgalib.nohelper.diff
gzip ./source/l/svgalib/svgalib-1.9.25-kernel-2.6.26.diff
gzip ./source/l/svgalib/svgalib.prefix.diff
gzip ./source/l/cairo/cairo-1.10.0-buggy_gradients.patch
gzip ./source/l/urwid/LICENSE
gzip ./source/l/djvulibre/doinst.sh
gzip ./source/l/gd/gd.png14.diff
gzip ./source/l/glib2/doinst.sh
gzip ./source/l/libusb/libusb.fix.debug.log.level.diff
gzip ./source/l/sdl/sdl.linux-2.6.31.input_absinfo.diff
gzip ./source/l/sdl/SDL_mixer.usrlocal.diff
gzip ./source/l/expat/expat-2.0.1-fixes-3.patch
gzip ./source/l/gst-plugins-good/gst-plugins-good.6b86b56abd8a28b9e94cee679e3d86367a9a0ab3.diff
gzip ./source/l/parted/parted.configure.diff
gzip ./source/l/libtiff/libtiff-CVE-2011-0192.patch
gzip ./source/l/libtiff/libtiff-CVE-2011-1167.patch
gzip ./source/l/glibc/glibc.disable.broken.optimized.memcpy.diff
gzip ./source/l/glibc/glibc-2.10-dns-no-gethostbyname4.diff
gzip ./source/l/glibc/glibc.make-3.82.diff
gzip ./source/l/glibc/glibc.git-96611391ad8823ba58405325d78cefeae5cdf699-CVE-2010-3847b.patch
gzip ./source/l/glibc/glibc.ldd.trace.through.dynamic.linker.diff
gzip ./source/l/glibc/glibc.ru_RU.CP1251.diff
gzip ./source/l/glibc/glibc.nis-netgroups.diff
gzip ./source/l/glibc/glibc.git-4a531bb0b3b582cb693de9f76d2d97d970f9a5d5.patch
gzip ./source/l/glibc/glibc.getcwd.max.macro.diff
gzip ./source/l/glibc/is_IS.diff
gzip ./source/l/glibc/glibc.locale.no-archive.diff
gzip ./source/l/glibc/glibc.revert.to.fix.build.breakages.diff
gzip ./source/l/libvisual-plugins/libvisual-plugins.gstreamer.diff
gzip ./source/l/qt/qt.blacklist.bad.certs.patch02.diff
gzip ./source/l/qt/qt.x86.cflags.diff
gzip ./source/l/qt/qt.mysql.h.diff
gzip ./source/l/qt/doinst.sh
gzip ./source/l/qt/qt.QSortFilterProxyModel.reformatted.diff
gzip ./source/l/qt/qt.blacklist.bad.certs.diff
gzip ./source/l/gamin/gaminrc
gzip ./source/l/gamin/doinst.sh
gzip ./source/l/system-config-printer/doinst.sh
gzip ./source/l/netpbm/config.mk
gzip ./source/l/PyQt/PyQt.phonon.diff
gzip ./source/l/libwmf/libwmf.png14.diff
gzip ./source/l/esound/doinst.sh
gzip ./source/l/t1lib/t1lib_5.1.2-3.diff
gzip ./source/l/gdk-pixbuf2/gdk-pixbuf.pnglz.diff
gzip ./source/l/gdk-pixbuf2/doinst.sh
gzip ./source/l/qtscriptgenerator/include-everything.patch
gzip ./source/l/qtscriptgenerator/qtscriptgenerator.gcc44.diff
gzip ./source/l/libtermcap/termcap.h.diff
gzip ./source/l/libtermcap/termcap-compat_1.2.3.diff
gzip ./source/l/libtermcap/termcap.bufsize.diff
gzip ./source/l/openexr/openexr.gcc4.diff
gzip ./source/l/libxml2/libxml2-2.7.8.broken.versioning.diff
gzip ./source/l/lesstif/lesstif.x86_64.patch
gzip ./source/l/lesstif/lesstif.rendertable.check.diff
gzip ./source/l/lesstif/lesstif.Makefile.in.patch
gzip ./source/l/lesstif/doinst.sh
gzip ./source/l/lesstif/lesstif.PutPixel32.patch
gzip ./source/l/imlib/imlib.mitshm.render.diff
gzip ./source/l/gtk+2/gtk+-2.24.x.icon-compat.diff
gzip ./source/l/gtk+2/fix_build_issues_on_tutorial_and_faq.diff
gzip ./source/l/gtk+2/gtk+-2.24.x.icon-compat.am.diff
gzip ./source/l/gtk+2/use_host_triplet_for_gtk_immodules.diff
gzip ./source/l/gtk+2/doinst.sh
gzip ./source/l/gtk+2/gtk.xid.nowarningflood.diff
gzip ./source/l/pilot-link/pilot-link.png14.diff
gzip ./source/l/pygobject/pygobject.fix.no.introspection.crash.diff
gzip ./source/l/libgpod/doinst.sh
gzip ./source/l/libnl/libnl-include_limits.h.patch
gzip ./source/l/hal-info/patches/quirk-LG_X110-keyboard.patch
gzip ./source/l/hal-info/patches/quirk-acer_aspire_hotkey.patch
gzip ./source/l/pango/pango.etc.host.location.diff
gzip ./source/l/desktop-file-utils/desktop-file-utils.quiet.warnings.diff
gzip ./source/l/desktop-file-utils/doinst.sh
gzip ./source/l/apr/apr.apr_ring.h.gcc45.diff
gzip ./source/l/db44/patch.4.4.20.2
gzip ./source/l/db44/patch.4.4.20.1
gzip ./source/l/libcap/libcap.capability.h.fix.broken.includes.diff
gzip ./source/l/ilmbase/ilmbase.gcc4.diff
gzip ./source/l/zlib/zlib.largefile64_source.diff
gzip ./source/l/ConsoleKit/consolekit-0.4.2-revert.patch
gzip ./source/l/ConsoleKit/consolekit-0.2.10-cleanup_console_tags.patch
gzip ./source/l/ConsoleKit/doinst.sh
gzip ./source/l/freetype/freetype.illadvisederror.diff
gzip ./source/l/freetype/freetype.subpixel.rendering.diff
gzip ./source/l/qca-ossl/qca-ossl.nowhirlpool.diff
gzip ./source/l/akonadi/doinst.sh
gzip ./source/l/icon-naming-utils/icon-naming-utils.pkgconfigdir.diff
gzip ./source/l/fuse/doinst.sh
gzip ./source/l/gnome-icon-theme/doinst.sh
gzip ./source/l/gnome-icon-theme/gnome-icon-theme.pkgconfig.path.diff
gzip ./source/l/virtuoso-ose/doinst.sh
gzip ./source/l/libexif/libexif.pc.diff
gzip ./pasture/source/gxine/gxine.desktop
bzip2 ./source/n/curl/cacert.pem
bzip2 ./source/xap/xv/xv-3.10a-enhancements.20070520-20081216.diff
bzip2 ./source/xap/xv/xv-3.10a-jumbo-fix-enh-patch-20070520.txt
bzip2 ./source/xap/xv/xv-3.10a-jumbo-additions.diff
bzip2 ./source/x/ttf-indic-fonts/Samyak_Malayalam.ttf
bzip2 ./source/x/ttf-indic-fonts/COPYING
bzip2 ./source/l/gtk+/gtk+1.2_1.2.10-18.diff
bzip2 ./source/l/glib/glib1.2_1.2.10-17.diff
