#!/bin/sh
#
# Run this script in the root directory of the repository to re-compress
# all patches and scripts that were un-compressed to make a better git commit:
#
gzip ./extra/source/pure-alsa-system/xfce4-volumed/0003-Removing-edge-case-memleaks.patch
gzip ./extra/source/pure-alsa-system/xfce4-volumed/0001-Removed-deprecated-Encoding-entry-in-.desktop-file-t.patch
gzip ./extra/source/pure-alsa-system/xfce4-mixer/0001-icons-Makefile.am-Remove-unnecessary-gtk-update-icon.patch
gzip ./extra/source/pure-alsa-system/xfce4-mixer/0001-Use-datadir-xfce4-mixer-as-MIXER_DATADIR.patch
gzip ./extra/source/pure-alsa-system/xfce4-mixer/doinst.sh
gzip ./extra/source/pure-alsa-system/xfce4-mixer/0001-Make-Unique-support-optional.patch
gzip ./extra/source/bittorrent/doinst.sh
gzip ./extra/source/bittorrent/bittorrent-xterm.sh
gzip ./extra/source/emacspeak/emacspeak.tcl8.6.diff
gzip ./extra/source/brltty/brltty.brlapi.pyx.diff
gzip ./extra/source/bittornado/doinst.sh
gzip ./extra/source/bittornado/btdownloadxterm.sh
gzip ./extra/source/recordmydesktop/shmstr-to-shmproto.patch
gzip ./extra/source/recordmydesktop/recordmydesktop-bitrate.patch
gzip ./extra/source/fltk/fltk.fltk-config.in.diff
gzip ./extra/source/wicd/curses_bitrate_fix.patch
gzip ./extra/source/wicd/doinst.sh
gzip ./extra/source/wicd/wicd.netentry_curses.py.save.settings.patch
gzip ./extra/source/wicd/wicd-1421918.patch
gzip ./extra/source/wicd/wicd-1.7.3-urwid-1.3.0.patch
gzip ./extra/source/wicd/manually-compile-translations.diff
gzip ./extra/source/bash-completion/fixup-sh-script-completions.diff
gzip ./extra/source/sendmail/Build
gzip ./extra/source/sendmail/openssl-1.1.0.patch
gzip ./source/x/liberation-fonts-ttf/doinst.sh
gzip ./source/x/motif/motif-2.3.4-no_demos.patch
gzip ./source/x/motif/motif-2.3.4-mwmrc_dir.patch
gzip ./source/x/motif/motif-2.3.4-bindings.patch
gzip ./source/x/motif/motif.rgbtxt.patch
gzip ./source/x/ttf-indic-fonts/doinst.sh
gzip ./source/x/x11/patch/xpyb/xpyb-1.3.1-xcbproto-1.13.patch
gzip ./source/x/x11/patch/xorg-server/fix-nouveau-segfault.diff
gzip ./source/x/x11/patch/xorg-server/xorg-server.combo.mouse.keyboard.layout.patch
gzip ./source/x/x11/patch/xorg-server/x11.startwithblackscreen.diff
gzip ./source/x/x11/patch/xf86-video-voodoo/0001-don-t-use-PCITAG-in-struct-anymore.patch
gzip ./source/x/x11/patch/xf86-video-intel/0001-Fix-build-on-i686.patch
gzip ./source/x/x11/patch/xf86-video-intel/intel-gcc-pr65873.patch
gzip ./source/x/x11/patch/xf86-video-intel/0001-Fix-build-on-F28-and-later.patch
gzip ./source/x/x11/patch/xf86-video-intel/0001-sna-Let-modestting-glamor-handle-gen9.patch
gzip ./source/x/x11/patch/xf86-video-intel/0001-sna-Avoid-clobbering-output-physical-size-with-xf86O.patch
gzip ./source/x/x11/patch/xf86-video-xgixp/0005-Update-for-new-damage-API.patch
gzip ./source/x/x11/patch/xf86-video-xgixp/0004-Stop-using-deprecated-xf86PciInfo.h.patch
gzip ./source/x/x11/patch/xf86-video-xgixp/0002-Remove-symbol-lists-as-they-are-not-used-any-more.patch
gzip ./source/x/x11/patch/xf86-video-xgixp/0003-shadow-shadowInit-shadowAdd-Remove.patch
gzip ./source/x/x11/patch/xf86-video-xgixp/0001-Remove-mibstore.h.patch
gzip ./source/x/x11/patch/xf86-video-v4l/xf86-video-v4l-0.2.0-build-fix.patch
gzip ./source/x/x11/patch/xf86-video-v4l/xorg-x11-drv-v4l-support_v4l2_only_drivers.patch
gzip ./source/x/x11/patch/xinit/xinit.remove.systemd.kludge.diff
gzip ./source/x/x11/patch/xdm/xdm-1.1.11-arc4random-include.patch
gzip ./source/x/x11/patch/xdm/xdm.glibc.crypt.diff
gzip ./source/x/x11/patch/xdm/xdm-consolekit.patch
gzip ./source/x/x11/patch/xdm/xdm-1.1.11-setproctitle-include.patch
gzip ./source/x/x11/patch/xcompmgr/xcompmgr-follow-icccm-spec.diff
gzip ./source/x/x11/patch/xcompmgr/patch-XFixesSetPictureClipRegion-shadow-fix-xcompmgr.c.diff
gzip ./source/x/x11/patch/luit/luit_use_system_extensions.diff
gzip ./source/x/x11/post-install/xorg-cf-files/x11.tmpl.lib64.kludge.diff
gzip ./source/x/x11/post-install/libX11/XKeysymDB
gzip ./source/x/x11-skel/doinst.sh
gzip ./source/x/xdg-user-dirs/doinst.sh
gzip ./source/x/mesa/doinst.sh
gzip ./source/x/dejavu-fonts-ttf/doinst.sh
gzip ./source/x/scim-hangul/scim-hangul-0.3.2+gcc-4.3.patch
gzip ./source/x/scim-hangul/scim-hangul-0.3.2+gcc-4.7.patch
gzip ./source/x/scim-hangul/scim-hangul-0.4.0+gtk.patch
gzip ./source/x/fontconfig/fontconfig.font.dir.list.diff
gzip ./source/x/fontconfig/doinst.sh
gzip ./source/x/fontconfig/fontconfig.dejavu.diff
gzip ./source/x/fontconfig/fontconfig.liberation.diff
gzip ./source/x/urw-core35-fonts-otf/doinst.sh
gzip ./source/x/xdg-utils/doinst.sh
gzip ./source/x/xterm/doinst.sh
gzip ./source/x/ttf-tlwg/doinst.sh
gzip ./source/x/scim-anthy/scim-anthy.gcc43.diff
gzip ./source/x/wqy-zenhei-font-ttf/wqy-zenhei.fix.fontconfig.warning.diff
gzip ./source/x/wqy-zenhei-font-ttf/fixup-fontconfig-file.diff
gzip ./source/x/wqy-zenhei-font-ttf/64-wqy-zenhei.conf
gzip ./source/e/emacs/doinst.sh
gzip ./source/n/ppp/radius.msdict
gzip ./source/n/ppp/doinst.sh
gzip ./source/n/ppp/ppp.CVE-2015-3310.diff
gzip ./source/n/ppp/realms
gzip ./source/n/ppp/options.new
gzip ./source/n/ppp/0028-pppoe-include-netinet-in.h-before-linux-in.h.patch
gzip ./source/n/ppp/pppsetup-1.98.moredevs.diff
gzip ./source/n/ppp/pppsetup-1.98.pppoff.diff
gzip ./source/n/ppp/ppp.slack.diff
gzip ./source/n/ppp/pppsetup-1.98.slack.diff
gzip ./source/n/ppp/pppsetup-1.98.backupfiles.diff
gzip ./source/n/ntp/ntp.nano.diff
gzip ./source/n/ntp/doinst.sh
gzip ./source/n/openssh/doinst.sh
gzip ./source/n/openssh/openssh.tcp_wrappers.diff
gzip ./source/n/openssh/openssh.no.openssl.version.check.diff
gzip ./source/n/openssh/openssh.fix_tunnel_forwarding.diff
gzip ./source/n/openssh/openssl-1.1.0.patch
gzip ./source/n/ulogd/doinst.sh
gzip ./source/n/yptools/yp-tools-2.14-glibc217-crypt.diff
gzip ./source/n/yptools/rc.yp
gzip ./source/n/yptools/nsswitch.conf-nis
gzip ./source/n/lynx/doinst.sh
gzip ./source/n/lynx/lynx.cfg.diff
gzip ./source/n/lynx/lynx-CVE-2008-4690.patch
gzip ./source/n/php/php-fpm.conf.diff
gzip ./source/n/php/doinst.sh
gzip ./source/n/php/php.ini-development.diff
gzip ./source/n/popa3d/doinst.sh
gzip ./source/n/popa3d/popa3d.diff
gzip ./source/n/lftp/doinst.sh
gzip ./source/n/gpa/doinst.sh
gzip ./source/n/nfs-utils/doinst.sh
gzip ./source/n/nfs-utils/nfs-utils.lwrap.needs.lnsl.diff
gzip ./source/n/nc/nc-110-21.diff
gzip ./source/n/nc/nc.diff
gzip ./source/n/irssi/doinst.sh
gzip ./source/n/openvpn/doinst.sh
gzip ./source/n/rpcbind/0002-rpcbind-pair-all-svc_getargs-calls-with-svc_freeargs.patch
gzip ./source/n/rpcbind/0006-rpcbproc_callit_com-No-need-to-allocate-output-buffe.patch
gzip ./source/n/rpcbind/0005-rpcbproc_callit_com-Stop-freeing-a-static-pointer.patch
gzip ./source/n/rpcbind/doinst.sh
gzip ./source/n/rpcbind/rpcbind.lwrap.needs.lnsl.diff
gzip ./source/n/rpcbind/0003-pmapproc_dump-Fixed-typo-in-memory-leak-patch.patch
gzip ./source/n/rpcbind/0004-rpcbind-fix-building-without-enable-debug.patch
gzip ./source/n/rpcbind/0001-man-rpcibind.8-Clarify-state-file-usage-and-history.patch
gzip ./source/n/rpcbind/rc.rpc
gzip ./source/n/bluez/doinst.sh
gzip ./source/n/bluez/bluez-5.30-obexd_without_systemd-1.patch
gzip ./source/n/bluez/refresh_adv_manager_for_non-LE_devices.diff
gzip ./source/n/network-scripts/doinst.sh
gzip ./source/n/vsftpd/0035-Modify-DH-enablement-patch-to-build-with-OpenSSL-1.1.patch
gzip ./source/n/vsftpd/0021-Introduce-support-for-DHE-based-cipher-suites.patch
gzip ./source/n/vsftpd/vsftpd.log
gzip ./source/n/vsftpd/doinst.sh
gzip ./source/n/vsftpd/vsftpd.builddefs.diff
gzip ./source/n/vsftpd/vsftpd.link-with-openssl-1.1.diff
gzip ./source/n/vsftpd/vsftpd.crypt.diff
gzip ./source/n/vsftpd/vsftpd.conf.diff
gzip ./source/n/uucp/policy.h.diff
gzip ./source/n/ca-certificates/doinst.sh
gzip ./source/n/ca-certificates/patches/fixup_update-ca-certificates.diff
gzip ./source/n/ca-certificates/patches/fixup_DESTDIR.diff
gzip ./source/n/netwrite/netwrite-0.17.diff
gzip ./source/n/dhcp/doinst.sh
gzip ./source/n/dhcp/dhclient-script.PATH.diff
gzip ./source/n/rp-pppoe/doinst.sh
gzip ./source/n/rp-pppoe/rp-pppoe-manpages.patch
gzip ./source/n/rp-pppoe/rp-pppoe-3.12-pluginpath.patch
gzip ./source/n/rp-pppoe/rp-pppoe-3.12-doc.patch
gzip ./source/n/rp-pppoe/rp-pppoe-3.12-plugin.patch
gzip ./source/n/rp-pppoe/rp-pppoe-3.12-bz1469960-new-kernel-header.patch
gzip ./source/n/rp-pppoe/rp-pppoe-3.12-ip-allocation.patch
gzip ./source/n/ebtables/doinst.sh
gzip ./source/n/ytalk/doinst.sh
gzip ./source/n/telnet/telnet-OpenBSD-014_telnet.diff
gzip ./source/n/telnet/netkit-telnet-0.17.diff
gzip ./source/n/telnet/telnet-OpenBSD-20020321.diff
gzip ./source/n/telnet/netkit-telnet-0.17-ayt.patch
gzip ./source/n/httpd/httpd.runasapache.diff
gzip ./source/n/httpd/doinst.sh
gzip ./source/n/dovecot/dovecot.default.shadow.auth.diff
gzip ./source/n/dovecot/doinst.sh
gzip ./source/n/dovecot/dovecot.config.README.diff
gzip ./source/n/netwatch/netwatch.phonemyself.diff
gzip ./source/n/netwatch/netwatch.makefile.diff
gzip ./source/n/inetd/doinst.sh
gzip ./source/n/inetd/inetd.loopingdos.diff
gzip ./source/n/inetd/fix-x86_64-daytime-segfault.diff
gzip ./source/n/inetd/inetd-OpenBSD-1.79.diff
gzip ./source/n/autofs/doinst.sh
gzip ./source/n/postfix/postfix.only.warn.regular.files.diff
gzip ./source/n/postfix/doinst.sh
gzip ./source/n/postfix/postfix.script.starting.message.diff
gzip ./source/n/netkit-routed/routed.18.candidate.final.patch
gzip ./source/n/netkit-routed/netkit-routed-0.17.diff
gzip ./source/n/stunnel/doinst.sh
gzip ./source/n/wireless_tools/doinst.sh
gzip ./source/n/wireless_tools/wireless_tools.nowhine.diff
gzip ./source/n/wireless_tools/wireless_tools.static.diff
gzip ./source/n/pssh/pssh-2.3.1-py3-min-int-none.patch
gzip ./source/n/pssh/pssh-read-stdin-as-bytes-in-Python-3.patch
gzip ./source/n/pssh/pssh-2.3.1-py3-str-bytes-encode.patch
gzip ./source/n/pssh/pssh-2.3.1-py3-non-blocking.patch
gzip ./source/n/pssh/pssh-2.3.1-py3-import.patch
gzip ./source/n/netkit-ntalk/netkit-ntalk-0.17.diff
gzip ./source/n/netkit-ntalk/netkit-ntalk-0.11.diff
gzip ./source/n/netkit-ntalk/ntalk-0.17-slackware-alt-talkd.patch
gzip ./source/n/NetworkManager/doinst.sh
gzip ./source/n/NetworkManager/patches/0000-slackware-use-fqdn.diff
gzip ./source/n/newspost/newspost.getline.diff
gzip ./source/n/samba/smb.conf.diff
gzip ./source/n/samba/doinst.sh
gzip ./source/n/net-snmp/net-snmp-5.7.3-openssl.patch
gzip ./source/n/net-snmp/net-snmp-5.7.3-Fix-Makefile-PL.patch
gzip ./source/n/net-snmp/doinst.sh
gzip ./source/n/net-snmp/net-snmp-5.7.3-mariadb-10.2.8.diff
gzip ./source/n/net-snmp/net-snmp.net-snmp-create-v3-user.etc.snmpd.conf.diff
gzip ./source/n/net-snmp/snmpd.conf
gzip ./source/n/net-snmp/net-snmp-5.7.3-Remove-U64-typedef.patch
gzip ./source/n/snownews/snownews.fake.destdir.diff
gzip ./source/n/netkit-timed/netkit-timed-0.17.diff
gzip ./source/n/wpa_supplicant/doinst.sh
gzip ./source/n/wpa_supplicant/patches/Fix-openssl-1-1-private-key-callback.patch
gzip ./source/n/wpa_supplicant/patches/flush-debug-output.diff
gzip ./source/n/wpa_supplicant/patches/dbus-service-file-args.diff
gzip ./source/n/wpa_supplicant/patches/rh1497640-pae-validate-input-before-pointer.patch
gzip ./source/n/wpa_supplicant/patches/rh1451834-nl80211-Fix-race-condition-in-detecting-MAC-change.patch
gzip ./source/n/wpa_supplicant/patches/quiet-scan-results-message.diff
gzip ./source/n/wpa_supplicant/patches/assoc-timeout.diff
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0001-hostapd-Avoid-key-reinstallation-in-FT-handshake.patch
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0004-Prevent-installation-of-an-all-zero-TK.patch
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0006-TDLS-Reject-TPK-TK-reconfiguration.patch
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0005-Fix-PTK-rekeying-to-generate-a-new-ANonce.patch
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0008-FT-Do-not-allow-multiple-Reassociation-Response-fram.patch
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0007-WNM-Ignore-WNM-Sleep-Mode-Response-without-pending-r.patch
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0003-Extend-protection-of-GTK-IGTK-reinstallation-of-WNM-.patch
gzip ./source/n/wpa_supplicant/2017-1/rebased-v2.6-0002-Prevent-reinstallation-of-an-already-in-use-group-ke.patch
gzip ./source/n/biff+comsat/biff+comsat.badutmp.diff
gzip ./source/n/biff+comsat/biff+comsat.offset.diff
gzip ./source/n/biff+comsat/biff+comsat-0.17.diff
gzip ./source/n/wget/doinst.sh
gzip ./source/n/netkit-rsh/netkit-rsh.arg_max.diff
gzip ./source/n/netkit-rsh/netkit-rsh.union_wait.diff
gzip ./source/n/netkit-rsh/netkit-rsh.auth.c.stddef.diff
gzip ./source/n/obexftp/patches/obexftp-0.24-fix-absurd-install-path.patch
gzip ./source/n/obexftp/patches/obexftp-norpath.patch
gzip ./source/n/icmpinfo/icmpinfo-1.11.diff
gzip ./source/n/icmpinfo/icmpinfo-1.11-time.diff
gzip ./source/n/bsd-finger/bsd-finger-0.17-host-info.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-init-realname.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-utmp.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-match_sigsegv.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-rfc742.patch
gzip ./source/n/bsd-finger/bsd-finger-wide-char-support5.patch
gzip ./source/n/bsd-finger/bsd-finger-0.16-pts.patch
gzip ./source/n/bsd-finger/bsd-finger-0.16-allocbroken.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-coverity-bugs.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-usagi-ipv6.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-exact.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-strip.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17-time.patch
gzip ./source/n/bsd-finger/bsd-finger-0.17.diff
gzip ./source/n/epic5/openssl-1.1.patch
gzip ./source/n/netdate/netdate.diff2
gzip ./source/n/netdate/netdate.diff
gzip ./source/n/openssl/openssl-1.1.0h.fix_c_rehash_quoting.diff
gzip ./source/n/openssl/certwatch
gzip ./source/n/openssl/doinst.sh-openssl
gzip ./source/n/openssl/doinst.sh-openssl-solibs
gzip ./source/n/dhcpcd/COPYRIGHT
gzip ./source/n/dhcpcd/doinst.sh
gzip ./source/n/netatalk/doinst.sh
gzip ./source/n/netatalk/netatalk.etc2ps.diff
gzip ./source/n/procmail/procmail.lfs.diff
gzip ./source/n/procmail/procmail_3.22-5.diff
gzip ./source/n/dnsmasq/doinst.sh
gzip ./source/n/dnsmasq/rc.dnsmasq
gzip ./source/n/dnsmasq/dnsmasq.libidn2.diff
gzip ./source/n/dnsmasq/dnsmasq.leasedir.diff
gzip ./source/n/mailx/mailx-12.5-openssl.patch
gzip ./source/n/mailx/mailx-12.5-globname-Invoke-wordexp-with-WRDE_NOCMD-CVE-2004-277.patch
gzip ./source/n/mailx/doinst.sh
gzip ./source/n/mailx/mailx-12.5-outof-Introduce-expandaddr-flag.patch
gzip ./source/n/metamail/metamail.uue.getline.diff
gzip ./source/n/alpine/pinepgp.pinegpgp.in.diff
gzip ./source/n/alpine/alpine.manpage.diff
gzip ./source/n/alpine/pinepgp-0.18.0-makefile-sed-fix.diff
gzip ./source/n/mutt/doinst.sh
gzip ./source/n/slrn/doinst.sh
gzip ./source/n/cyrus-sasl/doinst.sh
gzip ./source/n/cyrus-sasl/rc.saslauthd
gzip ./source/n/proftpd/doinst.sh
gzip ./source/n/cifs-utils/cifs-utils-6.7-talloc.patch
gzip ./source/n/iproute2/doinst.sh
gzip ./source/n/openssl10/openssl-1.0-versioned-symbols.patch
gzip ./source/n/pidentd/pidentd.openssl-1.1.diff
gzip ./source/n/pidentd/doinst.sh
gzip ./source/n/pidentd/pidentd.conf.diff
gzip ./source/n/openldap-client/doinst.sh
gzip ./source/n/htdig/htdig-3.2.0b6.diff
gzip ./source/n/htdig/doinst.sh
gzip ./source/n/htdig/htdig.conf.diff
gzip ./source/n/netkit-rwho/rwhod_getloadavg.diff
gzip ./source/n/netkit-rwho/netkit-rwho-0.17.diff
gzip ./source/n/bind/doinst.sh
gzip ./source/n/bind/bind.libidn.patch
gzip ./source/n/bind/bind.so_bsdcompat.diff
gzip ./source/n/net-tools/net-tools.config.h
gzip ./source/n/netkit-rusers/netkit-rusers-0.17.diff
gzip ./source/n/nn/nn_6.7.3-10.diff
gzip ./source/n/nn/nn.badnntphost.diff
gzip ./source/n/nn/nn.diff
gzip ./source/n/nn/m-x86_64.h
gzip ./source/n/nn/NNTP
gzip ./source/n/ModemManager/WeDoNotHaveSystemD.patch
gzip ./source/n/libtirpc/doinst.sh
gzip ./source/n/bridge-utils/bridge-utils-1.5-linux_3.8.x.patch
gzip ./source/n/rdist/rdist-6.1.5-07.lfs.diff
gzip ./source/n/rdist/rdist-6.1.5-04.bison.diff
gzip ./source/n/rdist/rdist-6.1.5-12.stat64.diff
gzip ./source/n/rdist/rdist-6.1.5-03.hardlink.diff
gzip ./source/n/rdist/rdist-6.1.5-05.varargs.diff
gzip ./source/n/rdist/rdist-6.1.5-14.fix-msgsndnotify-loop.diff
gzip ./source/n/rdist/rdist-6.1.5-00.linux.diff
gzip ./source/n/rdist/rdist-6.1.5-08.cleanup.diff
gzip ./source/n/rdist/rdist-6.1.5-09.svr4.diff
gzip ./source/n/rdist/rdist-6.1.5-01.links.diff
gzip ./source/n/rdist/rdist-6.1.5-06.maxargs.diff
gzip ./source/n/rdist/rdist-6.1.5-11.mkstemp.diff
gzip ./source/n/rdist/rdist-6.1.5-10.ssh.diff
gzip ./source/n/bootp/bootptab
gzip ./source/n/bootp/bootp_2.4.3-15.diff
gzip ./source/l/netpbm/config.mk
gzip ./source/l/netpbm/netpbm-noppmtompeg.patch
gzip ./source/l/netpbm/netpbm-pnmtops.patch
gzip ./source/l/ilmbase/ilmbase-2.2.0-no_undefined.patch
gzip ./source/l/libiodbc/libiodbc.disable.rpath.diff
gzip ./source/l/djvulibre/doinst.sh
gzip ./source/l/gst-plugins-base0/gst-plugins-base-0.10.36-gcc_4_9_0_i686-1.patch
gzip ./source/l/imagemagick/policy.xml.diff
gzip ./source/l/imagemagick/doinst.sh
gzip ./source/l/dconf-editor/doinst.sh
gzip ./source/l/gnome-themes-standard/doinst.sh
gzip ./source/l/taglib-extras/taglib-extras-1.0.1-version.patch
gzip ./source/l/taglib-extras/taglib-extras-0.1-multilib-1.patch
gzip ./source/l/taglib-extras/taglib-extras-1.0.1-taglib_ver.patch
gzip ./source/l/qca/Add_support_for_OpenSSL_1.1.0.diff
gzip ./source/l/qca/qca.tlsunittest.cpp.diff
gzip ./source/l/qt/qt.icu59.c++11.diff
gzip ./source/l/qt/qt.webkit-no_Werror.patch
gzip ./source/l/qt/qt.qclipboard_delay.patch
gzip ./source/l/qt/qt.mysql.h.diff
gzip ./source/l/qt/qt.QT_VERSION_CHECK.diff
gzip ./source/l/qt/qt.alsa-1.1.diff
gzip ./source/l/qt/qt.fix.broken.gif.crash.diff
gzip ./source/l/qt/doinst.sh
gzip ./source/l/qt/qt.icu59.patch
gzip ./source/l/qt/qtwebkit/doinst.sh
gzip ./source/l/qt/qtwebkit/qtwebkit.putByIndexBeyondVectorLengthWithArrayStorage.diff
gzip ./source/l/qt/qt.QTBUG-22829.diff
gzip ./source/l/qt/qt.qsystemtrayicon-plugin-system.diff
gzip ./source/l/qt/qt.qtreeview.crash.diff
gzip ./source/l/qt/qt.QTBUG-35459.diff
gzip ./source/l/qt/qt.gcc6.diff
gzip ./source/l/qt/qt.qclipboard_fix_recursive.patch
gzip ./source/l/qt/qt4.openssl-1.1.diff
gzip ./source/l/qt/qt.glib-honor-ExcludeSocketNotifiers-flag.diff
gzip ./source/l/qt/qt.icu4c.nodebug.diff
gzip ./source/l/libffi/libffi.includedir.diff
gzip ./source/l/pygtk/pygtk-fix-pango-object-leaks.patch
gzip ./source/l/gcr/doinst.sh
gzip ./source/l/sdl/libsdl-1.2.15-resizing.patch
gzip ./source/l/sdl/sdl-1.2.14-fix-mouse-clicking.patch
gzip ./source/l/sdl/SDL_ttf.shaded.text.diff
gzip ./source/l/sdl/SDL_mixer.usrlocal.diff
gzip ./source/l/id3lib/patches/id3lib.nullpointer_check.patch
gzip ./source/l/id3lib/patches/id3lib.manpages.patch
gzip ./source/l/id3lib/patches/id3lib.utf8_writing.patch
gzip ./source/l/id3lib/patches/id3lib.cppheaders.patch
gzip ./source/l/id3lib/patches/id3lib.c_wrapper.patch
gzip ./source/l/id3lib/patches/id3lib.mkstemp.patch
gzip ./source/l/id3lib/patches/id3lib.vbr_stack_smash.patch
gzip ./source/l/esound/esound-nospawn.patch
gzip ./source/l/esound/esound-0.2.38-drain.patch
gzip ./source/l/esound/doinst.sh
gzip ./source/l/esound/esound-0.2.38-fix-open-macro.patch
gzip ./source/l/esound/esound-0.2.41-libm.patch
gzip ./source/l/esound/remove-confusing-spew.patch
gzip ./source/l/PyQt/PyQt.phonon.diff
gzip ./source/l/gstreamer0/gstreamer-0.10.36-bison3.patch
gzip ./source/l/qt-gstreamer/doinst.sh
gzip ./source/l/db44/patch.4.4.20.1
gzip ./source/l/db44/patch.4.4.20.2
gzip ./source/l/libexif/libexif.pc.diff
gzip ./source/l/dconf/doinst.sh
gzip ./source/l/gst-plugins-good0/v4l.compile.fixes.diff
gzip ./source/l/glib/glib-1.2.10-multilib.patch
gzip ./source/l/glib/glib-1.2.10-gcc34.patch
gzip ./source/l/glib/glib-1.2.10-autotools.patch
gzip ./source/l/glib/glib-1.2.10-gcc5.patch
gzip ./source/l/glib/glib-1.2.10-unused-dep.patch
gzip ./source/l/glib/glib-1.2.10-no_undefined.patch
gzip ./source/l/glib/glib-1.2.10-format.patch
gzip ./source/l/glib/glib-1.2.10-isowarning.patch
gzip ./source/l/glib/glib-1.2.10-underquoted.patch
gzip ./source/l/apr-util/apr-util-mariadb-upstream.patch
gzip ./source/l/db48/db48.no.broken.doc.install.diff
gzip ./source/l/db42/patch.4.2.52.4
gzip ./source/l/db42/patch.4.2.52.3
gzip ./source/l/db42/patch.4.2.52.1
gzip ./source/l/db42/patch.4.2.52.2
gzip ./source/l/gtk+3/doinst.sh
gzip ./source/l/libgpod/doinst.sh
gzip ./source/l/libnl3/doinst.sh
gzip ./source/l/libxml2/libxml2.do-not-check-crc.diff
gzip ./source/l/parted/parted.configure.diff
gzip ./source/l/clucene/clucene.install_contribs_lib.diff
gzip ./source/l/clucene/clucene.pkgconfig.diff
gzip ./source/l/ebook-tools/epub3_fixed_layout.patch
gzip ./source/l/akonadi/doinst.sh
gzip ./source/l/akonadi/mysql-global.conf.patch
gzip ./source/l/akonadi/akonadi-mariadb-10.2.patch
gzip ./source/l/pulseaudio/0001-client-conf-Add-allow-autospawn-for-root.patch
gzip ./source/l/pulseaudio/doinst.sh
gzip ./source/l/pulseaudio/0003-no-root-warn.diff
gzip ./source/l/pulseaudio/030_posix-completion.diff
gzip ./source/l/pulseaudio/020_no-parallel-make.diff
gzip ./source/l/pulseaudio/pulseaudio-autostart.patch
gzip ./source/l/pulseaudio/0002-allow-autospawn-for-root-default.diff
gzip ./source/l/freetype/freetype.compile.both.subpixel.hinting.methods.diff
gzip ./source/l/freetype/doinst.sh
gzip ./source/l/freetype/freetype.illadvisederror.diff
gzip ./source/l/freetype/freetype.sh
gzip ./source/l/freetype/freetype.subpixel.rendering.diff
gzip ./source/l/freetype/freetype.csh
gzip ./source/l/qtscriptgenerator/include-everything.patch
gzip ./source/l/hicolor-icon-theme/doinst.sh
gzip ./source/l/openexr/openexr.CVE-2017-9110-to-9116.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2006-3376.patch
gzip ./source/l/libwmf/libwmf.png14.diff
gzip ./source/l/libwmf/libwmf-0.2.8.4-pixbufloaderdir.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2015-4695.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2007-3473.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-useafterfree.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-fallbackfont.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2016-9011.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2007-3477.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2007-2756.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2015-0848+CVE-2015-4588.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2016-10167.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2016-9317.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-reducesymbols.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2017-6362.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2007-3472.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2004-0941.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2016-10168.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2009-3546.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2007-0455.patch
gzip ./source/l/libwmf/libwmf-0.2.8.4-CVE-2015-4696.patch
gzip ./source/l/poppler/poppler.splashpath.h.revert.diff
gzip ./source/l/gamin/no_g_const_return.patch
gzip ./source/l/gamin/doinst.sh
gzip ./source/l/gamin/gaminrc
gzip ./source/l/gamin/fix-double-lock-in-inotify-helper-c.patch
gzip ./source/l/gvfs/doinst.sh
gzip ./source/l/adwaita-icon-theme/doinst.sh
gzip ./source/l/adwaita-icon-theme/inherit-hicolor-theme.diff
gzip ./source/l/gnome-keyring/doinst.sh
gzip ./source/l/openjpeg/openjpeg2_remove-thirdparty.patch
gzip ./source/l/fribidi/fribidi.glib.h.diff
gzip ./source/l/libvisual-plugins/libvisual-plugins.gstreamer.diff
gzip ./source/l/glib2/doinst.sh
gzip ./source/l/gtk+/gtk+-1.2.10-unused-deps.patch
gzip ./source/l/gtk+/gtk+-1.2.10-fontwarning.patch
gzip ./source/l/gtk+/gtk+-1.2.10-autotools.patch
gzip ./source/l/gtk+/gtk+-1.2.10-utf8fontset.patch
gzip ./source/l/gtk+/gtk+-1.2.10-ahiguti.patch
gzip ./source/l/gtk+/gtk+-1.2.10-gtkgdkdep.patch
gzip ./source/l/gtk+/gtk+-1.2.10-alignment.patch
gzip ./source/l/gtk+/gtk+-1.2.10-focus.patch
gzip ./source/l/gtk+/gtk+-1.2.10-encoding.patch
gzip ./source/l/gtk+/gtk+-1.2.10-dndorder.patch
gzip ./source/l/gtk+/gtk+-1.2.10-libtool.patch
gzip ./source/l/gtk+/gtk+-1.2.8-wrap-alnum.patch
gzip ./source/l/gtk+/gtk+-1.2.10-deletedir.patch
gzip ./source/l/gtk+/gtk+-underquoted.patch
gzip ./source/l/gtk+/gtk+-1.2.10-expose.patch
gzip ./source/l/gtk+/gtk+-1.2.10-troughpaint.patch
gzip ./source/l/gtk+/gtk+-1.2.10-kpenter.patch
gzip ./source/l/gtk+/gtk+-1.2.10-bellvolume.patch
gzip ./source/l/gtk+/gtk+-1.2.10-ukfont.patch
gzip ./source/l/gtk+/gtk+-1.2.10-missingchar.patch
gzip ./source/l/gtk+/gtk+-1.2.10-clistfocusrow.patch
gzip ./source/l/gtk+/gtk+-1.2.10-no_undefined.patch
gzip ./source/l/gtk+/gtk+-1.2.10-multilib.patch
gzip ./source/l/gtk+/gtk+-1.2.10-ctext.patch
gzip ./source/l/gtk+/gtk+-1.2.10-themeswitch.patch
gzip ./source/l/gtk+/gtk+-1.2.10-ppc64.patch
gzip ./source/l/gtk+/gtk+-1.2.10-format.patch
gzip ./source/l/gtk+/gtk+-1.2.10-pixmapref.patch
gzip ./source/l/gtk+/gtk+-1.2.10-localecrash.patch
gzip ./source/l/virtuoso-ose/doinst.sh
gzip ./source/l/t1lib/t1lib_5.1.2-3.5.diff
gzip ./source/l/alsa-lib/doinst.sh
gzip ./source/l/libvisual/libvisual.glib.h.diff
gzip ./source/l/ConsoleKit2/doinst.sh
gzip ./source/l/ConsoleKit2/patches/0002-Fix-some-libdir-scripts-stuff-missed-in-4d87a25ea0af.patch
gzip ./source/l/ConsoleKit2/patches/0001-Revert-Minor-code-refactoring.patch
gzip ./source/l/ConsoleKit2/patches/0004-Apply-overlooked-prefix-lib-libdir-substitution.patch
gzip ./source/l/ConsoleKit2/patches/0003-Filter-out-the-kdm-user.patch
gzip ./source/l/fuse/doinst.sh
gzip ./source/l/GConf/doinst.sh
gzip ./source/l/GConf/patches/0002-dbus-Don-t-spew-to-console-when-unable-to-connect-to.patch
gzip ./source/l/GConf/patches/0003-gsettings-data-convert-Warn-and-fix-invalid-schema-p.patch
gzip ./source/l/GConf/patches/0001-mconvert-enable-recursive-scheme-lookup-and-fix-a-cr.patch
gzip ./source/l/system-config-printer/system-config-printer.auth.dialog.2766d74a.patch
gzip ./source/l/system-config-printer/doinst.sh
gzip ./source/l/ncurses/terminfo/xterm.terminfo.orig
gzip ./source/l/ncurses/terminfo/xterm.terminfo.diff
gzip ./source/l/ncurses/doinst.sh
gzip ./source/l/ncurses/ncurses.mkhashsize.diff
gzip ./source/l/gtk+2/fix_build_issues_on_tutorial_and_faq.diff
gzip ./source/l/gtk+2/doinst.sh
gzip ./source/l/gtk+2/gtk.gtk-faq.diff
gzip ./source/l/gtk+2/gtk.gtk-tut.diff
gzip ./source/l/gtk+2/gtk.xid.nowarningflood.diff
gzip ./source/l/gtk+2/gtk+-2.24.x.icon-compat.diff
gzip ./source/l/gtk+2/gtk+-2.24.x.icon-compat.am.diff
gzip ./source/l/shared-mime-info/doinst.sh
gzip ./source/l/glibc/glibc.locale.no-archive.diff
gzip ./source/l/glibc/glibc-c-utf8-locale.patch
gzip ./source/l/glibc/glibc.ru_RU.CP1251.diff
gzip ./source/l/glibc/glibc.pkey_get.56170e0.diff
gzip ./source/l/strigi/libstreams-0003-Build-fix-for-gcc-4.8.patch
gzip ./source/l/strigi/libstreams-0005-use-rpath-only-when-needed.patch
gzip ./source/l/strigi/libstreams-0004-Fix-Krazy-issues.patch
gzip ./source/l/strigi/libstreams-0001-Generate-config.h-after-looking-for-dependencies.patch
gzip ./source/l/strigi/libstreamanalyzer-0002-order-matters-for-systems-that-have-things-already-i.patch
gzip ./source/l/strigi/libstreamanalyzer-0004-ffmpeg-Rename-mutex-to-g_mutex.patch
gzip ./source/l/strigi/libstreams-0002-Reduce-noise-in-analysis-tools-complain-about-resour.patch
gzip ./source/l/strigi/libstreamanalyzer-0005-use-rpath-only-when-needed.patch
gzip ./source/l/strigi/libstreamanalyzer-0001-Fix-for-non-valid-values-in-Exif-field-ISOSpeedRatin.patch
gzip ./source/l/strigi/libstreamanalyzer-0003-Fix-Krazy-issues.patch
gzip ./source/l/libtiff/libtiff-am-version.patch
gzip ./source/l/svgalib/svgalib-1.9.25-round_gtf_gtfcalc_c.patch
gzip ./source/l/svgalib/svgalib.nohelper.diff
gzip ./source/l/svgalib/svgalib-1.9.25-kernel-2.6.26.diff
gzip ./source/l/svgalib/svgalib-1.9.25-quickmath-h-redefinitions.patch
gzip ./source/l/svgalib/svgalib-1.9.25-vga_getmodenumber.patch
gzip ./source/l/svgalib/svgalib.prefix.diff
gzip ./source/l/libxslt/libxslt.xsltMaxDepth.diff
gzip ./source/l/icon-naming-utils/icon-naming-utils.pkgconfigdir.diff
gzip ./source/l/glib-networking/doinst.sh
gzip ./source/l/libcap/libcap.capability.h.fix.broken.includes.diff
gzip ./source/l/gdk-pixbuf2/doinst.sh
gzip ./source/l/gdk-pixbuf2/gdk-pixbuf.pnglz.diff
gzip ./source/l/pilot-link/pilot-link-0.12.5-redefinePerlsymbols.patch
gzip ./source/l/pilot-link/pilot-link.png14.diff
gzip ./source/l/desktop-file-utils/doinst.sh
gzip ./source/l/desktop-file-utils/desktop-file-utils.quiet.warnings.diff
gzip ./source/l/libcap-ng/python3.patch
gzip ./source/l/gsettings-desktop-schemas/doinst.sh
gzip ./source/l/polkit/0004-polkit-Add-g_autoptr-support-for-GObject-derived-pol.patch
gzip ./source/l/polkit/0015-polkitpermission-Fix-a-memory-leak-on-authority-chan.patch
gzip ./source/l/polkit/doinst.sh
gzip ./source/l/polkit/0001-Fix-a-memory-leak-of-PolkitAgentListener-s-Server-ob.patch
gzip ./source/l/polkit/0005-data-Set-GIO_USE_VFS-local-in-the-environment.patch
gzip ./source/l/polkit/dont-set-wheel-group-as-admin.diff
gzip ./source/l/at-spi2-atk/doinst.sh
gzip ./source/l/libtheora/libtheora-1.1.1-libpng16.patch
gzip ./source/l/libtheora/libtheora-1.1.1.latex.patch
gzip ./source/l/aalib/aalib-aclocal.patch
gzip ./source/l/libimobiledevice/libimobiledevice.use_tlsv1_instead_of_sslv3.diff
gzip ./source/l/libimobiledevice/02a0e03e24bc96bba2e5ea2438c30baf803fd137.patch
gzip ./source/y/bsd-games/bsd-games.fortlen.diff
gzip ./source/y/bsd-games/bsd-games.config.params.diff
gzip ./source/y/bsd-games/bsd-games.sail.no.union_wait.diff
gzip ./source/y/bsd-games/bsd-games.strfile.8.diff
gzip ./source/y/bsd-games/bsd-games.ospeed.diff
gzip ./source/y/bsd-games/bsd-games.pom.diff
gzip ./source/y/bsd-games/hangman-words
gzip ./source/y/bsd-games/bsd-games.trek-gcc4.diff
gzip ./source/y/bsd-games/bsd-games.getline.diff
gzip ./source/y/bsd-games/bsd-games.fortunepath.diff
gzip ./source/y/bsd-games/bsd-games.phantasia_install_fix.diff
gzip ./source/y/bsd-games/fortune-fixes-sorry-no-additions-accepted-here/20120302.diff
gzip ./source/xap/gparted/doinst.sh
gzip ./source/xap/xscreensaver/xscreensaver.setuid.diff
gzip ./source/xap/xscreensaver/xscreensaver.no.expiration.date.diff
gzip ./source/xap/xscreensaver/xscreensaver.electricsheep.diff
gzip ./source/xap/xscreensaver/setuid.c
gzip ./source/xap/blackbox/blackbox-0.70.1-gcc-4.3.patch
gzip ./source/xap/blackbox/xinitrc.blackbox
gzip ./source/xap/blackbox/textpropertytostring-unconditional.diff
gzip ./source/xap/blackbox/startblackbox
gzip ./source/xap/hexchat/doinst.sh
gzip ./source/xap/fluxbox/fluxbox.startfluxbox.dbus.diff
gzip ./source/xap/fluxbox/fluxbox.keys.diff
gzip ./source/xap/fluxbox/xinitrc.fluxbox
gzip ./source/xap/fvwm/doinst.sh
gzip ./source/xap/fvwm/xinitrc.fvwm2
gzip ./source/xap/fvwm/startfvwm2
gzip ./source/xap/x3270/doinst.sh
gzip ./source/xap/pidgin/doinst.sh
gzip ./source/xap/pidgin/fix-gmain_h-compile-error.diff
gzip ./source/xap/rxvt-unicode/rxvt-unicode.utempter.diff
gzip ./source/xap/windowmaker/WindowMaker.noopensusemenu.diff
gzip ./source/xap/windowmaker/wmaker.inst.diff
gzip ./source/xap/windowmaker/xinitrc.wmaker
gzip ./source/xap/network-manager-applet/doinst.sh
gzip ./source/xap/network-manager-applet/fix-double-free.diff
gzip ./source/xap/seamonkey/sm.ui.scrollToClick.diff
gzip ./source/xap/seamonkey/doinst.sh
gzip ./source/xap/seamonkey/autoconf/autoconf-2.13-consolidated_fixes-1.patch
gzip ./source/xap/rdesktop/02-Fix-OpenSSL-1.1-compability-issues.patch
gzip ./source/xap/xpdf/doinst.sh
gzip ./source/xap/xpdf/patches/xpdfrc.diff
gzip ./source/xap/xpdf/lang/xpdf-korean.diff
gzip ./source/xap/xpdf/lang/xpdf-turkish.diff
gzip ./source/xap/xpdf/lang/xpdf-chinese-traditional.diff
gzip ./source/xap/xpdf/lang/xpdf-cyrillic.diff
gzip ./source/xap/xpdf/lang/xpdf-thai.diff
gzip ./source/xap/xpdf/lang/xpdf-latin2.diff
gzip ./source/xap/xpdf/lang/xpdf-hebrew.diff
gzip ./source/xap/xpdf/lang/xpdf-chinese-simplified.diff
gzip ./source/xap/xpdf/lang/xpdf-greek.diff
gzip ./source/xap/xpdf/lang/xpdf-arabic.diff
gzip ./source/xap/xpdf/lang/xpdf-japanese.diff
gzip ./source/xap/MPlayer/include-samba-4.0.patch
gzip ./source/xap/mozilla-thunderbird/mozilla-firefox.xpcom_arm.patch
gzip ./source/xap/mozilla-thunderbird/autoconf/autoconf-2.13-consolidated_fixes-1.patch
gzip ./source/xap/mozilla-thunderbird/tb.ui.scrollToClick.diff
gzip ./source/xap/ddd/doinst.sh
gzip ./source/xap/ddd/strclass.C.diff
gzip ./source/xap/ddd/machine_code_window_fix.diff
gzip ./source/xap/blueman/doinst.sh
gzip ./source/xap/blueman/dont-autostart-applet-in-kde.diff
gzip ./source/xap/mozilla-firefox/mozilla-firefox-mimeTypes-fix.diff
gzip ./source/xap/mozilla-firefox/mimeTypes.rdf
gzip ./source/xap/mozilla-firefox/firefox.moz_plugin_path.diff
gzip ./source/xap/mozilla-firefox/autoconf/autoconf-2.13-consolidated_fixes-1.patch
gzip ./source/xap/mozilla-firefox/ff.ui.scrollToClick.diff
gzip ./source/xap/xaos/xaos.x86.registers.diff
gzip ./source/xap/xaos/xaos.6
gzip ./source/xap/geeqie/doinst.sh
gzip ./source/xap/geeqie/fix-build-re-docs.diff
gzip ./source/xap/xv/xv-3.10a.patch
gzip ./source/xap/xv/xv.prefix.diff
gzip ./source/xap/xv/xv-libpng-1.5.patch
gzip ./source/xap/xv/xv.prefix_x86_64.diff
gzip ./source/xap/xv/xv.jasper.diff
gzip ./source/xap/sane/doinst.sh
gzip ./source/xap/sane/dll.conf.additions
gzip ./source/xap/sane/sane-frontends-1.0.14-sane_cap_always_settable.diff
gzip ./source/xap/audacious/doinst.sh
gzip ./source/xap/xmms/xmms.gtk.doublesize.diff
gzip ./source/xap/xmms/xmms.wmxmms_vis_depth_workaround.diff
gzip ./source/xap/xmms/xmms.alsa.default.diff
gzip ./source/xap/seyon/seyon_2.20c-16.diff
gzip ./source/xap/electricsheep/electricsheep.mplayer.diff
gzip ./source/xap/gnuchess/doinst.sh
gzip ./source/xap/gnuchess/eboard.png16.diff
gzip ./source/xap/gnuchess/xboard.conf.diff
gzip ./source/xap/gnuchess/eboard.ldl.diff
gzip ./source/xap/gnuchess/eboard.assert.diff
gzip ./source/xap/xsane/xsane-0.995-close-fds.patch
gzip ./source/xap/xsane/xsane-0.998-preview-selection.patch
gzip ./source/xap/xsane/xsane-0.999-lcms2.patch
gzip ./source/xap/xsane/xsane-0.995-xdg-open.patch
gzip ./source/xap/xsane/xsane-0.999-pdf-no-high-bpp.patch
gzip ./source/xap/xsane/xsane-0.997-ipv6.patch
gzip ./source/xap/xsane/xsane-0.999-7-autoconf.patch
gzip ./source/xap/xsane/xsane-0.999-coverity.patch
gzip ./source/xap/xsane/xsane-0.996-no-eula.patch
gzip ./source/xap/xsane/xsane-0.999-no-file-selected.patch
gzip ./source/xap/xsane/xsane-0.999-snprintf-update.patch
gzip ./source/xap/xsane/xsane-0.998-libpng.patch
gzip ./source/xap/xsane/xsane-0.999-man-page.patch
gzip ./source/xap/xsane/xsane-0.998-wmclass.patch
gzip ./source/xap/xsane/xsane-0.999-signal-handling.patch
gzip ./source/xap/xsane/xsane-0.997-off-root-build.patch
gzip ./source/xap/xsane/xsane-0.998-desktop-file.patch
gzip ./source/xap/pavucontrol/doinst.sh
gzip ./source/xap/pavucontrol/replace-gtk-stock-lock-icon.diff
gzip ./source/xap/easytag/doinst.sh
gzip ./source/xap/gkrellm/gkrellm.theme.defaults.diff
gzip ./source/xap/xgames/xcolormap.diff
gzip ./source/xap/xgames/xlander-2009-07-18.diff
gzip ./source/xap/xgames/spider.diff
gzip ./source/xap/xgames/xlander.fixes.diff
gzip ./source/xap/xgames/maze.diff
gzip ./source/xap/xgames/xcuckoo.diff
gzip ./source/xap/gnuplot/gnuplot.fix.info.generation.diff
gzip ./source/xap/xlockmore/xlockmore.bitmap.diff
gzip ./source/xap/gucharmap/doinst.sh
gzip ./source/xap/gftp/gftp.desktop
gzip ./source/xap/gv/gv-bounding-box.patch
gzip ./source/xap/gv/gv-dat.patch
gzip ./source/xap/gv/gv-aarch64.patch
gzip ./source/xap/gv/gv-resource.patch
gzip ./source/xap/gv/gv-bug1071238.patch
gzip ./source/xfce/xfce4-pulseaudio-plugin/xfce4-pulseaudio-plugin-0.2.4-gtk3_theme_clean.patch
gzip ./source/xfce/xfce4-pulseaudio-plugin/xfce4-pulseaudio-plugin-0.2.4-gtk3_theme.patch
gzip ./source/xfce/orage/orage.libical3.diff
gzip ./source/xfce/xfce4-settings/xfce4-settings.xft.defaults.diff
gzip ./source/xfce/xfce4-settings/xfce4-settings.theme.diff
gzip ./source/xfce/xfce4-systemload-plugin/xfce4-systemload-plugin.HOVER_TIMEOUT.diff
gzip ./source/xfce/xfce4-panel/libxfce4panel.max_blinking_count.8.diff
gzip ./source/xfce/xfce4-notifyd/doinst.sh
gzip ./source/xfce/xfce4-taskmanager/doinst.sh
gzip ./source/xfce/xfce4-power-manager/doinst.sh
gzip ./source/xfce/xfce4-clipman-plugin/doinst.sh
gzip ./source/xfce/xfce4-screenshooter/doinst.sh
gzip ./source/d/python3/python3.no-static-library.diff
gzip ./source/d/python3/python3.x86_64.diff
gzip ./source/d/python3/python3.readline.set_pre_input_hook.diff
gzip ./source/d/binutils/patches/binutils-2.20.51.0.10-sec-merge-emit.patch
gzip ./source/d/binutils/patches/binutils-2.25-version.patch
gzip ./source/d/binutils/patches/binutils-2.24-ldforcele.patch
gzip ./source/d/binutils/patches/binutils-2.20.51.0.10-copy-osabi.patch
gzip ./source/d/binutils/patches/binutils-2.20.51.0.2-libtool-lib64.patch
gzip ./source/d/binutils/patches/binutils.no-config-h-check.diff
gzip ./source/d/binutils/patches/binutils-2.25.1-cleansweep.patch
gzip ./source/d/binutils/patches/binutils-2.25-set-long-long.patch
gzip ./source/d/binutils/patches/binutils.export.demangle.h.diff
gzip ./source/d/python/python.x86_64.diff
gzip ./source/d/python/python.no-static-library.diff
gzip ./source/d/python/python.readline.set_pre_input_hook.diff
gzip ./source/d/p2c/p2c_time.diff
gzip ./source/d/p2c/p2c.getline.diff
gzip ./source/d/p2c/p2c.examples.diff
gzip ./source/d/p2c/p2c_1.21alpha2-2.1.diff
gzip ./source/d/doxygen/doxygen.9468ede.diff
gzip ./source/d/automake/doinst.sh
gzip ./source/d/libtool/doinst.sh
gzip ./source/d/libtool/libtool.no.moved.warning.diff
gzip ./source/d/llvm/clang_disable_pgo.patch
gzip ./source/d/llvm/clang.toolchains.i586.triple.diff
gzip ./source/d/opencl-headers/cl2.hpp
gzip ./source/d/opencl-headers/cl.hpp
gzip ./source/d/intltool/no-guess-builddir.diff
gzip ./source/d/intltool/intltool-0.51.0-perl-5.22.patch
gzip ./source/d/distcc/doinst.sh
gzip ./source/d/autoconf/doinst.sh
gzip ./source/d/clisp/clisp.c_data.compact_empty_buckets.diff
gzip ./source/d/rust/link_libffi.diff
gzip ./source/d/perl/libnet-3.08-Do-not-create-Net-libnet.cfg.patch
gzip ./source/d/perl/perl.configure.multilib.patch
gzip ./source/d/perl/DBD-mysql.net_buffer_length.diff
gzip ./source/d/pmake/pmake.txt
gzip ./source/d/pmake/pmake.strerror.strdup.diff
gzip ./source/d/pmake/pmake_1.111-1.diff
gzip ./source/d/make/make.glibc-2.27.glob.diff
gzip ./source/d/make/make.guile22.diff
gzip ./source/d/pkg-config/doinst.sh
gzip ./source/d/mercurial/doinst.sh
gzip ./source/d/gcc/gcc-no_fixincludes.diff
gzip ./source/d/cvs/cvs.crypt-2.diff
gzip ./source/d/cvs/cvs.getline64.diff
gzip ./source/kde/patch/pykde4/Annotate-KAutoMount-as-Abstract.patch
gzip ./source/kde/patch/pykde4/pykde4.solid.cmake.diff
gzip ./source/kde/patch/pykde4/pykde4-4.14.3-checkstate-sip-4.19.5.patch
gzip ./source/kde/patch/pykde4/fix_kpythonpluginfactory_build.diff
gzip ./source/kde/patch/pykde4/0003-Fix-build-with-sip-4.19.patch
gzip ./source/kde/patch/kuser/kuser.cmake.include.checkincludefiles.diff
gzip ./source/kde/patch/plasma-nm/plasma-nm.nm.diff
gzip ./source/kde/patch/kgamma/kgamma.cmake.include.checkincludefiles.diff
gzip ./source/kde/patch/konsole/konsole.term.is.konsole.diff
gzip ./source/kde/patch/konsole/konsole.scrollup.diff
gzip ./source/kde/patch/print-manager/print-manager.fix.build.against.cups22.diff
gzip ./source/kde/patch/kdelibs/return-not-break.-copy-paste-error.patch
gzip ./source/kde/patch/kdelibs/coding-style-fixes.patch
gzip ./source/kde/patch/kdelibs/return-application-icons-properly.patch
gzip ./source/kde/patch/kdelibs/kdelibs.docbook.patch
gzip ./source/kde/patch/kdelibs/kdelibs.upnp_conditional.patch
gzip ./source/kde/patch/kdelibs/kdelibs-openssl-1.1.patch
gzip ./source/kde/patch/krdc/krdc_freerdp-1.1.0.patch
gzip ./source/kde/patch/kde-workspace/kde-workspace.kdm.server.timeout.diff
gzip ./source/kde/patch/kde-workspace/kde-workspace.batteryapplet.diff
gzip ./source/kde/patch/kde-workspace/kde-workspace.panel-layout.diff
gzip ./source/kde/patch/kde-runtime/kde-runtime-4.14.3.nm.diff
gzip ./source/kde/patch/kdevelop-pg-qt/kdevelop-pg-qt.ftbfs.diff
gzip ./source/kde/patch/kdevelop-pg-qt/0011-fix-some-warnings.patch
gzip ./source/kde/patch/ktouch/ktouch.performance.diff
gzip ./source/kde/patch/kdewebdev/include-tidy.patch
gzip ./source/kde/patch/kdepim/kdepim-install_kleopatra_headers.patch
gzip ./source/kde/patch/libkscreen/libkscreen.broken.test.diff
gzip ./source/kde/patch/k3b/k3b.narrowing.diff
gzip ./source/kde/patch/k3b/k3b.pointer.compare.diff
gzip ./source/kde/patch/k3b/k3b-ffmpeg3.patch
gzip ./source/kde/patch/kate/kate4-fix_gcc7.patch
gzip ./source/kde/patch/kdepimlibs/kdepimlibs.libical3.diff
gzip ./source/kde/patch/perlqt/perlqt.gcc6.diff
gzip ./source/kde/patch/strigi-multimedia/strigi-multimedia_port.patch
gzip ./source/kde/patch/calligra/boost-1.65.0.patch
gzip ./source/kde/patch/calligra/calligra.mariadb.diff
gzip ./source/kde/patch/kdeconnect-kde/kdeconnect-kde.openssh7.diff
gzip ./source/kde/patch/kscreen/kscreen.broken.test.diff
gzip ./source/kde/patch/kopete/kopete-gcc6.patch
gzip ./source/kde/patch/kdeartwork/kdeartwork.cmake.include.checkincludefiles.diff
gzip ./source/tcl/tix/configure.private.diff
gzip ./source/tcl/tix/tix.soname.patch
gzip ./source/tcl/tix/tix.tcl8.5.patch
gzip ./source/tcl/hfsutils/hfsutils.errno.diff
gzip ./source/a/tar/tar.nolonezero.diff
gzip ./source/a/tar/tar-1.13.bzip2.diff
gzip ./source/a/less/lesspipe.sh
gzip ./source/a/file/file.etc.file.diff
gzip ./source/a/file/file.crdaregbin.magic
gzip ./source/a/file/doinst.sh
gzip ./source/a/file/file.short.diff
gzip ./source/a/file/file.quiet.diff
gzip ./source/a/file/file.xz.magic
gzip ./source/a/file/file.zisofs.magic
gzip ./source/a/file/recompile_magic.mgc.sh
gzip ./source/a/mdadm/doinst.sh
gzip ./source/a/smartmontools/doinst.sh
gzip ./source/a/mcelog/mcelog.init.diff
gzip ./source/a/mcelog/doinst.sh
gzip ./source/a/gpm/mouseconfig
gzip ./source/a/gpm/gpm-1.20.1-select-1.patch
gzip ./source/a/gpm/gpm.gcc7.diff
gzip ./source/a/gpm/gpm.types.diff
gzip ./source/a/gpm/gpm-1.20.1-weak-wgetch.patch
gzip ./source/a/gpm/gpm-1.20.5-close-fds.patch
gzip ./source/a/gpm/gpm-1.20.1-lib-silent.patch
gzip ./source/a/gpm/inputattach.c
gzip ./source/a/gpm/setup.mouse
gzip ./source/a/udisks/udisks.no.pci-db.diff
gzip ./source/a/findutils/findutils.nolocate.diff
gzip ./source/a/findutils/findutils.no.default.options.warnings.diff
gzip ./source/a/dcron/doinst.sh
gzip ./source/a/dcron/run-parts.8
gzip ./source/a/dcron/patches/0007-Update-main.c.patch
gzip ./source/a/dcron/patches/defs.h.TMPDIR.diff
gzip ./source/a/dcron/patches/0006-Fixed-a-bug-whereby-syncs-killed-all-waiting-jobs.patch
gzip ./source/a/dcron/patches/0008-Fix-3-every-Nth-day-of-week-syntax-not-working.patch
gzip ./source/a/dcron/patches/0009-Updated-manpage.patch
gzip ./source/a/dcron/patches/crontab.c.O_EXCL.diff
gzip ./source/a/dcron/patches/0003-CHANGELOG-tweak.patch
gzip ./source/a/dcron/patches/0002-README-var-spool-cron-crontabs-root.patch
gzip ./source/a/dcron/crontab.root
gzip ./source/a/dcron/run-parts
gzip ./source/a/usb_modeswitch/doinst.sh
gzip ./source/a/usb_modeswitch/device_reference.txt
gzip ./source/a/floppy/fdutils-5.5-20081027.diff
gzip ./source/a/floppy/fdutils.mediaprm.diff
gzip ./source/a/rpm2tgz/patches/0008-Avoid-none-values-in-slack-desc.patch
gzip ./source/a/rpm2tgz/patches/0009-Add-c-option-just-as-makepkg-c-y.patch
gzip ./source/a/rpm2tgz/patches/0004-produce-more-compliant-slack-desc.patch
gzip ./source/a/rpm2tgz/patches/0005-gzip-man-info-pages.patch
gzip ./source/a/rpm2tgz/patches/0001-fix-d-handling.patch
gzip ./source/a/rpm2tgz/patches/0006-should-we-use-.txz-format-in-slackware-current.patch
gzip ./source/a/rpm2tgz/patches/0002-fix-spurious-path-to-rpm-file-with-n-option.patch
gzip ./source/a/rpm2tgz/patches/0003-allow-every-user-to-use-rpm2tgz.patch
gzip ./source/a/rpm2tgz/patches/0007-Add-support-for-.txz-packages-and-rpm2txz-symlink.patch
gzip ./source/a/coreutils/DIR_COLORS
gzip ./source/a/coreutils/doinst.sh
gzip ./source/a/coreutils/coreutils-dircolors.csh
gzip ./source/a/coreutils/coreutils.uname.diff
gzip ./source/a/coreutils/no_ls_quoting.patch
gzip ./source/a/coreutils/coreutils-dircolors.sh
gzip ./source/a/util-linux/ziptool-fix_build.patch
gzip ./source/a/util-linux/doinst.sh
gzip ./source/a/util-linux/setserial-rc.serial.diff
gzip ./source/a/util-linux/adjtimex_1.29-2.2.diff
gzip ./source/a/util-linux/bsdstrings-util-linux_overflow.diff
gzip ./source/a/util-linux/util-linux.fdisk-no-solaris.diff
gzip ./source/a/util-linux/setserial-undef_TIOCGHAYESESP.diff
gzip ./source/a/getty-ps/getty.bugfixes.diff
gzip ./source/a/lilo/lilo.ignore.usable.memory.above.4G.diff
gzip ./source/a/lilo/lilo.allow.colons.in.by-id.diff
gzip ./source/a/lilo/lilo.nvme.support.diff
gzip ./source/a/infozip/unzip.process.c.diff
gzip ./source/a/infozip/unzip.use.system.libbz2.diff
gzip ./source/a/infozip/unzip.git.archive.fix.diff
gzip ./source/a/elvis/elvis.ref.c.getline.diff
gzip ./source/a/genpower/genpower.var.diff
gzip ./source/a/genpower/genpower.halt.diff
gzip ./source/a/lha/lha_1.14i-10.1.diff
gzip ./source/a/quota/quota.lwrap.needs.lnsl.diff
gzip ./source/a/acpid/default
gzip ./source/a/acpid/doinst.sh
gzip ./source/a/acpid/acpi_handler.sh
gzip ./source/a/acpid/rc.acpid
gzip ./source/a/e2fsprogs/doinst.sh
gzip ./source/a/e2fsprogs/e2fsprogs.no.64bit.by.default.diff
gzip ./source/a/minicom/doinst.sh
gzip ./source/a/minicom/minicom.users
gzip ./source/a/minicom/config.sub-x86_64.diff
gzip ./source/a/minicom/lrzsz_0.12.21-5.diff
gzip ./source/a/bash/doinst.sh
gzip ./source/a/bash/bash_manpages.patch
gzip ./source/a/upower/doinst.sh
gzip ./source/a/upower/patches/upower-pm-utils-0.9.23-fix-segfault.patch
gzip ./source/a/upower/patches/rules-Add-support-for-Logitech-G700s-G700-Gaming-Mou.patch
gzip ./source/a/upower/patches/rules-support-Logitech-Unifying-in-Linux-3.19.patch
gzip ./source/a/upower/patches/Update-UPower-HID-rules-supported-devices-list.patch
gzip ./source/a/upower/patches/Fix-HID-rules-header-as-per-discussions.patch
gzip ./source/a/upower/patches/linux-Properly-detect-bluetooth-mice-and-keyboards-t.patch
gzip ./source/a/upower/patches/linux-Detect-docked-docking-stations-correctly.patch
gzip ./source/a/upower/patches/linux-Clamp-percentage-for-overfull-batteries.patch
gzip ./source/a/sysvinit/doinst.sh
gzip ./source/a/sysvinit/sysvinit.use_dev_initctl_not_run_initctl.diff
gzip ./source/a/sysvinit/sysvinit.paths.diff
gzip ./source/a/haveged/doinst.sh
gzip ./source/a/eudev/doinst.sh
gzip ./source/a/eudev/60-cdrom_id.rules.diff
gzip ./source/a/eudev/eudev.ignore_bind_unbind_events.diff
gzip ./source/a/udisks2/doinst.sh
gzip ./source/a/sysklogd/sysklogd.allow.repeated.messages.diff
gzip ./source/a/sysklogd/doinst.sh
gzip ./source/a/sysklogd/use_memmove_not_strcpy.diff
gzip ./source/a/sysklogd/sysklogd.union.wait.int.diff
gzip ./source/a/utempter/doinst.sh
gzip ./source/a/unarj/Makefile
gzip ./source/a/lrzip/doinst.sh
gzip ./source/a/patch/0001-Refuse-to-apply-ed-scripts-by-default.patch
gzip ./source/a/pciutils/pciutils.dontcompress.diff
gzip ./source/a/etc/doinst.sh
gzip ./source/a/etc/nsswitch.conf
gzip ./source/a/procps-ng/psmisc.3638cc55b4d08851faba46635d737b24d016665b.diff
gzip ./source/a/bzip2/bzip2.saneso.diff
gzip ./source/a/kbd/sources/kbd-1.15-unicode_start.patch
gzip ./source/a/kbd/sources/speakupmap.map
gzip ./source/a/kbd/sources/kbd-1.15.3-fix-es-translation.patch
gzip ./source/a/kbd/sources/kbd-1.15.2-po.patch
gzip ./source/a/kbd/sources/kbd-1.15-keycodes-man.patch
gzip ./source/a/kbd/sources/kbd-1.15-resizecon-x86_64.patch
gzip ./source/a/kbd/sources/nl.euro.diff
gzip ./source/a/devs/makedev_2.3.1.slack.diff
gzip ./source/a/devs/makedev.hd.diff
gzip ./source/a/devs/makedev_2.3.1-46.2.diff
gzip ./source/a/devs/makedev_2.3.1.hd.diff
gzip ./source/a/logrotate/doinst.sh
gzip ./source/a/logrotate/logrotate.cron
gzip ./source/a/logrotate/logrotate.slackware.diff
gzip ./source/a/logrotate/logrotate.conf
gzip ./source/a/sysvinit-scripts/doinst.sh
gzip ./source/a/dialog/dialog.smaller.min.height.diff
gzip ./source/a/glibc-zoneinfo/doinst.sh
gzip ./source/a/attr/doinst.sh
gzip ./source/a/lvm2/doinst.sh
gzip ./source/a/lvm2/create-dm-run-dir.diff
gzip ./source/a/tcsh/doinst.sh
gzip ./source/a/tcsh/tcsh.nobuiltincolorls.diff
gzip ./source/a/shadow/shadow.CVE-2005-4890.relax.diff
gzip ./source/a/shadow/shadow.login.display.short.hostname.diff
gzip ./source/a/shadow/useradd
gzip ./source/a/shadow/doinst.sh
gzip ./source/a/shadow/shadow.CVE-2017-2616.diff
gzip ./source/a/shadow/login.defs
gzip ./source/a/elilo/elilo.double.kernel.size.limit.diff
gzip ./source/a/mlocate/doinst.sh
gzip ./source/a/pcmciautils/doinst.sh
gzip ./source/a/pkgtools/doinst.sh
gzip ./source/a/bin/scripts/xx
gzip ./source/a/bin/scripts/diskcopy
gzip ./source/a/sysvinit-functions/doinst.sh
gzip ./source/a/grub/initrd_naming.patch
gzip ./source/a/grub/doinst.sh
gzip ./source/a/grub/grub.dejavusansmono.gfxterm.font.diff
gzip ./source/a/grub/0001-Fix-CVE-2015-8370-Grub2-user-pass-vulnerability.patch
gzip ./source/a/dbus/doinst.sh
gzip ./source/a/dbus/dbus-1.12.x-allow_root_globally.diff
gzip ./source/a/dbus/rc.messagebus
gzip ./source/a/os-prober/os-prober.reiserfs.diff
gzip ./source/a/libcgroup/libcgroup.loop.diff
gzip ./source/a/libcgroup/doinst.sh
gzip ./source/a/libcgroup/libcgroup.conf.diff
gzip ./source/a/libcgroup/libcgroup.init.diff
gzip ./source/installer/sources/initrd/etc/keymaps.tar
gzip ./source/ap/ghostscript-fonts-std/doinst.sh
gzip ./source/ap/jove/jove.makefile.diff
gzip ./source/ap/nano/doinst.sh
gzip ./source/ap/cgmanager/doinst.sh
gzip ./source/ap/dvd+rw-tools/dvd+rw-tools.limits.h.diff
gzip ./source/ap/sysstat/doinst.sh
gzip ./source/ap/soma/doinst.sh
gzip ./source/ap/slackpkg/0001-Fix-for-var_log_packages-being-a-symlink.patch
gzip ./source/ap/slackpkg/doinst.sh
gzip ./source/ap/slackpkg/0003-mirrors-x86-.sample-Remove-bjtu.edu.cn-mirror.patch
gzip ./source/ap/slackpkg/0002-Use-CHECKSUMS.md5.asc-to-determine-ChangeLog-newness.patch
gzip ./source/ap/slackpkg/files/dialog-functions.sh
gzip ./source/ap/slackpkg/files/slackpkg
gzip ./source/ap/slackpkg/files/post-functions.sh
gzip ./source/ap/slackpkg/files/filelist.awk
gzip ./source/ap/slackpkg/files/mirrors-x86_64.sample
gzip ./source/ap/slackpkg/files/GPL
gzip ./source/ap/slackpkg/files/README
gzip ./source/ap/slackpkg/files/mirrors-x86.sample
gzip ./source/ap/slackpkg/files/mirrors-arm.sample
gzip ./source/ap/slackpkg/files/blacklist.new
gzip ./source/ap/slackpkg/files/ChangeLog
gzip ./source/ap/slackpkg/files/slackpkg.8
gzip ./source/ap/slackpkg/files/install-new.awk
gzip ./source/ap/slackpkg/files/core-functions.sh
gzip ./source/ap/slackpkg/files/cutpkg.awk
gzip ./source/ap/slackpkg/files/mirrors-s390.sample
gzip ./source/ap/slackpkg/files/pkglist.awk
gzip ./source/ap/slackpkg/files/slackpkg.conf.5
gzip ./source/ap/slackpkg/files/slackpkg.conf.new
gzip ./source/ap/pm-utils/patches/add-in-kernel-suspend-to-both.patch
gzip ./source/ap/pm-utils/patches/fix-wrong-path-in-intel-audio-powersave.patch
gzip ./source/ap/pm-utils/patches/log-line-spacing-fix.patch
gzip ./source/ap/pm-utils/patches/init-logfile-append.patch
gzip ./source/ap/pm-utils/patches/use_more_sane_harddrive_defaults.patch
gzip ./source/ap/pm-utils/patches/hook-exit-code-log.patch
gzip ./source/ap/a2ps/a2ps-4.14-texinfo-nodes.patch
gzip ./source/ap/a2ps/a2ps-texi-comments.patch
gzip ./source/ap/a2ps/a2ps.a2ps_cfg.in.diff
gzip ./source/ap/a2ps/a2ps.diff
gzip ./source/ap/hplip/hplip.python3.shebang.diff
gzip ./source/ap/hplip/doinst.sh
gzip ./source/ap/hplip/hplip.no.upgrade.diff
gzip ./source/ap/hplip/setup.py.lc_all.c.diff
gzip ./source/ap/cups-filters/doinst.sh
gzip ./source/ap/zsh/doinst.sh
gzip ./source/ap/sqlite/COPYRIGHT
gzip ./source/ap/usbmuxd/doinst.sh
gzip ./source/ap/usbmuxd/39-usbmuxd.rules
gzip ./source/ap/man-db/doinst.sh
gzip ./source/ap/man-db/dont_write_in_usr.diff
gzip ./source/ap/at/doinst.sh
gzip ./source/ap/groff/groff.man.mdoc.local
gzip ./source/ap/mc/mc-3605-extfs.c-fix-buffer-overflow.patch
gzip ./source/ap/mc/mc.image.sh.geeqie.diff
gzip ./source/ap/cdrdao/cdrdao-1.2.3-helpmansync.patch
gzip ./source/ap/cdrdao/cdrdao.bitrate_table.diff
gzip ./source/ap/cdrdao/cdrdao-1.2.3-format.patch
gzip ./source/ap/cdrdao/cdrdao.narrowing.diff
gzip ./source/ap/cdrdao/cdrdao-1.2.3-stat.patch
gzip ./source/ap/amp/amp-gcc34.diff
gzip ./source/ap/madplay/madplay-0.15.2b-fix-segfault.patch
gzip ./source/ap/dmapi/bug799162.patch
gzip ./source/ap/screen/26source_encoding.patch
gzip ./source/ap/screen/screen.no_libelf.diff
gzip ./source/ap/screen/60-revert-screenrc-change.diff
gzip ./source/ap/screen/45suppress_remap.patch
gzip ./source/ap/screen/52fix_screen_utf8_nfd.patch
gzip ./source/ap/mariadb/rc.mysqld
gzip ./source/ap/mariadb/doinst.sh
gzip ./source/ap/vim/vim.vimrc.diff
gzip ./source/ap/vim/doinst.sh
gzip ./source/ap/flac/flac.man.diff
gzip ./source/ap/libx86/libx86-mmap-offset.patch
gzip ./source/ap/libx86/libx86-add-pkgconfig.patch
gzip ./source/ap/seejpeg/seejpeg-1.10.diff
gzip ./source/ap/ghostscript/cidfmap
gzip ./source/ap/acct/acct.logdir.fhs.diff
gzip ./source/ap/squashfs-tools/0004-unsquashfs-add-support-for-LZMA-magics.patch
gzip ./source/ap/squashfs-tools/0006-uptream-fix-race.patch
gzip ./source/ap/squashfs-tools/0007-fix-2GB-limit-in-mksquashfs.patch
gzip ./source/ap/squashfs-tools/0001-kfreebsd.patch
gzip ./source/ap/squashfs-tools/0003-CVE-2015-4645_and_CVE-2015-4646.patch
gzip ./source/ap/squashfs-tools/0002-fix_phys_mem_calculation.patch
gzip ./source/ap/alsa-utils/alsa-utils.alsaconf.diff
gzip ./source/ap/alsa-utils/doinst.sh
gzip ./source/ap/alsa-utils/rc.alsa-oss
gzip ./source/ap/alsa-utils/rc.alsa
gzip ./source/ap/texinfo/doinst.sh
gzip ./source/ap/texinfo/dir
gzip ./source/ap/terminus-font/doinst.sh
gzip ./source/ap/terminus-font/terminus-font.Makefile.paths.diff
gzip ./source/ap/diffutils/diffutils-sdiff-no-waitpid.patch
gzip ./source/ap/diffutils/doinst.sh
gzip ./source/ap/diffutils/diffutils.mkdir_p.diff
gzip ./source/ap/tmux/doinst.sh
gzip ./source/ap/tmux/tmux.conf
gzip ./source/ap/gutenprint/doinst.sh
gzip ./source/ap/sudo/doinst.sh
gzip ./source/ap/rpm/doinst.sh
gzip ./source/ap/rpm/Packages
gzip ./source/ap/cdrtools/doinst.sh
gzip ./source/ap/cdrtools/cdrtools-3.01-fix-20151126-mkisofs-isoinfo.patch
gzip ./source/ap/vorbis-tools/ogg123.opus.diff
gzip ./source/ap/ispell/local.h.linux.diff
gzip ./source/ap/dash/doinst.sh
gzip ./source/ap/dash/dash-0.5.7-format-security.patch
gzip ./source/ap/cdparanoia/cdparanoia-III-10.2_cdda_private.patch
gzip ./source/ap/cups/doinst.sh
gzip ./source/ap/cups/455c52a027ab3548953372a0b7bdb0008420e9ba.patch
gzip ./source/ap/linuxdoc-tools/doinst.sh
gzip ./source/t/texlive/doinst.sh
gzip ./source/t/xfig/xfig.fig.ad.diff
gzip ./source/t/xfig/xfig.no.pdf.ref.diff
gzip ./pasture/source/php/php-fpm.conf.diff
gzip ./pasture/source/php/PHP-5.6.31-OpenSSL-1.1.0-compatibility-20170801.patch
gzip ./pasture/source/php/doinst.sh
gzip ./pasture/source/php/php.ini-development.diff
bzip2 ./source/n/curl/cacert.pem
bzip2 ./source/xap/xv/xv-3.10a-enhancements.20070520-20081216.diff
bzip2 ./source/xap/xv/xv-3.10a-jumbo-additions.diff
bzip2 ./source/xap/xv/xv-3.10a-jumbo-fix-enh-patch-20070520.txt
