#!/bin/sh
#
# Run this script in the root directory of the repository to re-compress
# all patches and scripts that were un-compressed to make a better git commit:
#
gzip ./extra/source/kde3-compat/qt3/qt.x86.cflags.diff
gzip ./extra/source/kde3-compat/qt3/qt-x11.diff
gzip ./extra/source/kde3-compat/qt3/qt.mysql.h.diff
gzip ./extra/source/kde3-compat/qt3/doinst.sh
gzip ./extra/source/kde3-compat/arts/arts.tmpdir.diff
gzip ./extra/source/kde3-compat/kdelibs3/kdelibs-utempter.diff
gzip ./extra/source/kde3-compat/kdelibs3/kdelibs.inotify.diff
gzip ./extra/source/kde3-compat/kdelibs3/kdelibs.no.inotify.externs.diff
gzip ./extra/source/grub/grub-0.97-x86_64.patch
gzip ./extra/source/grub/grub_support_256byte_inode.patch
gzip ./extra/source/grub/grubconfig_localefix.patch
gzip ./extra/source/bittorrent/doinst.sh
gzip ./extra/source/bittorrent/bittorrent-xterm.sh
gzip ./extra/source/partitionmanager/doinst.sh
gzip ./extra/source/wicd/doinst.sh
gzip ./extra/source/bash-completion/bash_completion.sh
gzip ./extra/source/bash-completion/bash-completion-xz.diff
gzip ./extra/source/tightvnc/doinst.sh
gzip ./extra/source/tightvnc/tightvnc.paths-and-perms.diff
gzip ./testing/source/bash/doinst.sh
gzip ./source/a/kbd/sources/kbd-1.15-unicode_start.patch
gzip ./source/a/kbd/sources/speakupmap.map
gzip ./source/a/kbd/sources/kbd-1.15-po.patch
gzip ./source/a/kbd/sources/kbd-1.15-keycodes-man.patch
gzip ./source/a/kbd/sources/kbd-1.15-quiet_doc.patch
gzip ./source/a/kbd/sources/kbd-1.15-resizecon-x86_64.patch
gzip ./source/a/kbd/sources/nl.euro.diff
gzip ./source/a/kbd/sources/kbd-1.15-sparc.patch
gzip ./source/a/pcmciautils/doinst.sh
gzip ./source/a/dialog/dialog.smaller.min.height.diff
gzip ./source/a/splitvt/splitvt_1.6.5-9.diff
gzip ./source/a/bin/scripts/xx
gzip ./source/a/bin/scripts/diskcopy
gzip ./source/a/cpio/cpio-2.9.gcc43.diff
gzip ./source/a/acl/acl.destdir.diff
gzip ./source/a/util-linux-ng/adjtimex_1.23-1.diff
gzip ./source/a/util-linux-ng/setserial-rc.serial.diff
gzip ./source/a/util-linux-ng/ziptool-fix_build.patch
gzip ./source/a/util-linux-ng/doinst.sh
gzip ./source/a/util-linux-ng/net-tools.diff
gzip ./source/a/util-linux-ng/net-tools_1.60-19.diff
gzip ./source/a/util-linux-ng/util-linux-ng.fdisk-no-solaris.diff
gzip ./source/a/lha/lha_1.14i-10.1.diff
gzip ./source/a/bash/patches/bash31-016
gzip ./source/a/bash/patches/bash31-014
gzip ./source/a/bash/patches/bash31-015
gzip ./source/a/bash/patches/bash31-005
gzip ./source/a/bash/patches/bash31-009
gzip ./source/a/bash/patches/bash31-008
gzip ./source/a/bash/patches/bash31-010
gzip ./source/a/bash/patches/bash31-011
gzip ./source/a/bash/patches/bash31-012
gzip ./source/a/bash/patches/bash31-001
gzip ./source/a/bash/patches/bash31-007
gzip ./source/a/bash/patches/bash31-002
gzip ./source/a/bash/patches/bash31-013
gzip ./source/a/bash/patches/bash31-006
gzip ./source/a/bash/patches/bash31-003
gzip ./source/a/bash/patches/bash31-004
gzip ./source/a/bash/patches/bash31-017
gzip ./source/a/bash/doinst.sh
gzip ./source/a/tcsh/tcsh.nobuiltincolorls.diff
gzip ./source/a/tcsh/doinst.sh
gzip ./source/a/dbus/rc.messagebus
gzip ./source/a/dbus/doinst.sh
gzip ./source/a/minicom/minicom.users
gzip ./source/a/minicom/lrzsz_0.12.21-4.diff
gzip ./source/a/minicom/wintcap.diff
gzip ./source/a/minicom/minirc.dfl
gzip ./source/a/minicom/config.sub-x86_64.diff
gzip ./source/a/minicom/doinst.sh
gzip ./source/a/sysvinit-scripts/doinst.sh
gzip ./source/a/acpid/rc.acpid
gzip ./source/a/acpid/default
gzip ./source/a/acpid/doinst.sh
gzip ./source/a/acpid/acpi_handler.sh
gzip ./source/a/mkinitrd/busybox-1.12.1_inotify.diff
gzip ./source/a/mkinitrd/archive/busybox-1.7.2.remove_warning.diff
gzip ./source/a/mkinitrd/archive/busybox-1.7.2.no-gc-sections.diff
gzip ./source/a/utempter/doinst.sh
gzip ./source/a/lvm2/doinst.sh
gzip ./source/a/sysvinit-functions/doinst.sh
gzip ./source/a/logrotate/logrotate.slackware.diff
gzip ./source/a/etc/nsswitch.conf
gzip ./source/a/etc/termcap-BSD
gzip ./source/a/file/file.short.diff
gzip ./source/a/file/file.crdaregbin.magic
gzip ./source/a/file/file.zisofs.magic
gzip ./source/a/file/file.quiet.diff
gzip ./source/a/file/file.etc.file.diff
gzip ./source/a/file/file.xz.magic
gzip ./source/a/pciutils/pciutils.ids.dest.diff
gzip ./source/a/tar/tar.nolonezero.diff
gzip ./source/a/tar/tar.norecordsizespam.diff
gzip ./source/a/tar/tar-1.22-support_txz.diff
gzip ./source/a/tar/rmt.8
gzip ./source/a/tar/tar.1
gzip ./source/a/tar/tar-1.13.bzip2.diff
gzip ./source/a/less/less.sysconfdir.diff
gzip ./source/a/less/lesspipe.sh
gzip ./source/a/floppy/fdutils-5.4-20020222.diff
gzip ./source/a/floppy/fdutils.mediaprm.diff
gzip ./source/a/gpm/inputattach.c
gzip ./source/a/gpm/gpm-1.20.1-math.patch
gzip ./source/a/gpm/gpm-evdev-cumulative.patch
gzip ./source/a/gpm/gpm-1.20.1-no-console-error.patch
gzip ./source/a/gpm/mouseconfig
gzip ./source/a/gpm/gpm-1.20.1-input-defines.diff
gzip ./source/a/gpm/setup.mouse
gzip ./source/a/gpm/gpm-1.20.1-gpmopen.patch
gzip ./source/a/gpm/gpm-1.20.1.send-noise-to-syslogs.diff
gzip ./source/a/gpm/gpm-1.20.1-multilib.patch
gzip ./source/a/gpm/gpm-1.20.1-idie.patch
gzip ./source/a/gpm/gpm.evdevmakefile.patch
gzip ./source/a/gpm/gpm-1.20.1-consolename.patch
gzip ./source/a/gpm/gpm-1.20.1-lib-silent.patch
gzip ./source/a/gpm/gpm-1.20.1-weak-wgetch.patch
gzip ./source/a/gpm/gpm-1.20.1-nodebug.patch
gzip ./source/a/gpm/gpm-1.20.1-input.patch
gzip ./source/a/gpm/gpm-1.20.1-subscript.patch
gzip ./source/a/shadow/shadow.remove.obsolete.options.diff
gzip ./source/a/shadow/shadow.newgrp.getlogin
gzip ./source/a/shadow/shadow-4.0.3.x86_64.diff
gzip ./source/a/shadow/shadow.shadowconfig.diff
gzip ./source/a/shadow/shadow.gcc34.diff
gzip ./source/a/shadow/shadow.login.defs.diff
gzip ./source/a/shadow/shadow.newgrp.nopam
gzip ./source/a/zoo/zoo_2.10-18.diff
gzip ./source/a/bzip2/bzip2-1.0.4.saneso.diff
gzip ./source/a/e2fsprogs/doinst.sh
gzip ./source/a/smartmontools/doinst.sh
gzip ./source/a/usbutils/usbutils.ids.dest
gzip ./source/a/dcron/dcron-2.3.3.version.diff
gzip ./source/a/dcron/run-parts.8
gzip ./source/a/dcron/dcron-2.3.3.diff3
gzip ./source/a/dcron/dcron-2.3.3.diff2
gzip ./source/a/dcron/dcron-2.3.3.diff
gzip ./source/a/dcron/dcron.fork.diff
gzip ./source/a/dcron/dcron.tmpdir.diff
gzip ./source/a/dcron/dcron-2.3.3.crontab.diff4
gzip ./source/a/dcron/run-parts
gzip ./source/a/getty-ps/getty.bugfixes.diff
gzip ./source/a/sysvinit/sysvinit.pidof.rhforkseverything.diff
gzip ./source/a/sysvinit/doinst.sh
gzip ./source/a/sysvinit/sysvinit.diff
gzip ./source/a/sysvinit/sysvinit-2.86-timeval.patch
gzip ./source/a/sysklogd/sysklogd-1.4.1-owl-syslogd-crunch_list.diff
gzip ./source/a/sysklogd/sysklogd_1.4.1-20.diff
gzip ./source/a/udev/rule_generator.diff
gzip ./source/a/udev/doinst.sh
gzip ./source/a/genpower/genpower.halt.diff
gzip ./source/a/genpower/genpower.var.diff
gzip ./source/a/ncompress/ncompress.filenamelen.diff
gzip ./source/a/ncompress/ncompress.zerobyteforce.diff
gzip ./source/a/ncompress/ncompress-4.2.4-bssUnderflow.patch
gzip ./source/a/ncompress/ncompress.lfs2.diff
gzip ./source/a/ncompress/ncompress.make.diff
gzip ./source/a/ncompress/ncompress.2GB.diff
gzip ./source/a/ncompress/ncompress-4.2.4-endians.patch
gzip ./source/a/procps/procinfo.gcc3.diff
gzip ./source/a/procps/procps.nowarning.diff
gzip ./source/a/procps/procps.w.showfrom.diff
gzip ./source/a/procps/procps-3.2.7-ps-eip64.diff
gzip ./source/a/coreutils/DIR_COLORS
gzip ./source/a/coreutils/coreutils-dircolors.csh
gzip ./source/a/coreutils/coreutils.uname.diff
gzip ./source/a/coreutils/doinst.sh
gzip ./source/a/coreutils/coreutils-dircolors.sh
gzip ./source/a/mt-st/mt-st.man.diff
gzip ./source/a/mt-st/mt-st.config.diff
gzip ./source/a/mt-st/mt-st.sdlt.diff
gzip ./source/a/cups/cups.firefox.desktop.diff
gzip ./source/a/cups/doinst.sh
gzip ./source/a/devs/makedev_2.3.1-46.2.diff
gzip ./source/a/devs/makedev_2.3.1.slack.diff
gzip ./source/a/devs/makedev_2.3.1.hd.diff
gzip ./source/a/devs/makedev.hd.diff
gzip ./source/a/mdadm/mdadm.static.small.diff
gzip ./source/a/mdadm/doinst.sh
gzip ./source/a/findutils/findutils.no.default.options.warnings.diff
gzip ./source/a/findutils/findutils.nolocate.diff
gzip ./source/a/attr/attr.destdir.diff
gzip ./source/a/module-init-tools/modprobe.favor.etc.modprobe.d.diff
gzip ./source/a/module-init-tools/modprobe.ignore_some_suffixes.diff
gzip ./source/a/module-init-tools/modprobe.no_sys_check.diff
gzip ./source/a/module-init-tools/doinst.sh
gzip ./source/a/unarj/Makefile
gzip ./source/k/2.6.29.x-intel-crash-patch.diff
gzip ./source/k/linux-2.6.29.6-02-default-mmap_min_addr-4096.diff
gzip ./source/k/linux-2.6.29.6-01-sendpage.diff
gzip ./source/n/httpd/httpd.nossldefault.diff
gzip ./source/n/httpd/config.layout.diff
gzip ./source/n/httpd/httpd.runasapache.diff
gzip ./source/n/httpd/doinst.sh
gzip ./source/n/dnsmasq/dnsmasq.leasedir.diff
gzip ./source/n/dnsmasq/rc.dnsmasq
gzip ./source/n/dnsmasq/doinst.sh
gzip ./source/n/portmap/rc.rpc
gzip ./source/n/portmap/doinst.sh
gzip ./source/n/portmap/portmap.lwrap.needs.lnsl.diff
gzip ./source/n/iptraf/iptraf_3.0.0-6.diff
gzip ./source/n/iptraf/iptraf.paths.diff
gzip ./source/n/htdig/htdig.conf.diff
gzip ./source/n/htdig/htdig-3.2.0b6.diff
gzip ./source/n/htdig/doinst.sh
gzip ./source/n/lftp/doinst.sh
gzip ./source/n/irssi/irsi-0.8.14.manpage_fix.diff
gzip ./source/n/irssi/doinst.sh
gzip ./source/n/openssh/doinst.sh
gzip ./source/n/mailx/doinst.sh
gzip ./source/n/nfs-utils/nfs-utils.lwrap.needs.lnsl.diff
gzip ./source/n/network-scripts/doinst.sh
gzip ./source/n/netkit-timed/netkit-timed-0.17.diff
gzip ./source/n/ytalk/doinst.sh
gzip ./source/n/stunnel/doinst.sh
gzip ./source/n/netatalk/netatalk-2.0.4-afpdconf.diff
gzip ./source/n/netatalk/netatalk-2.0.4-without_xfs.diff
gzip ./source/n/netatalk/netatalk.etc2ps.diff
gzip ./source/n/netatalk/doinst.sh
gzip ./source/n/icmpinfo/icmpinfo-1.11.diff
gzip ./source/n/netwrite/netwrite-0.17.diff
gzip ./source/n/bsd-finger/bsd-finger-0.17.diff
gzip ./source/n/netkit-routed/routed.18.candidate.final.patch
gzip ./source/n/netkit-routed/netkit-routed-0.17.diff
gzip ./source/n/net-tools/net-tools.diff
gzip ./source/n/net-tools/net-tools_1.60-19.diff
gzip ./source/n/inetd/inetd.loopingdos.diff
gzip ./source/n/inetd/inetd-OpenBSD-1.79.diff
gzip ./source/n/openldap-client/doinst.sh
gzip ./source/n/netwatch/netwatch.makefile.diff
gzip ./source/n/netwatch/netwatch.phonemyself.diff
gzip ./source/n/nmap/nmap.ndiff.mandir.diff
gzip ./source/n/procmail/procmail_3.22-5.diff
gzip ./source/n/procmail/procmail.lfs.diff
gzip ./source/n/rp-pppoe/doinst.sh
gzip ./source/n/bluez-utils/doinst.sh
gzip ./source/n/pidentd/pidentd.conf.diff
gzip ./source/n/pidentd/doinst.sh
gzip ./source/n/dhcpcd/COPYRIGHT
gzip ./source/n/dhcpcd/patches/config.h.diff
gzip ./source/n/dhcpcd/patches/dhcpcd.8.in.diff
gzip ./source/n/dhcpcd/patches/dhcpcd.sh.diff
gzip ./source/n/dhcpcd/dhcpcd.vararg.diff
gzip ./source/n/sendmail/Build
gzip ./source/n/popa3d/popa3d.diff
gzip ./source/n/popa3d/doinst.sh
gzip ./source/n/traceroute/traceroute.no.domain.strip.diff
gzip ./source/n/traceroute/traceroute_1.4a12-5.diff
gzip ./source/n/nc/nc-110-21.diff
gzip ./source/n/nc/nc.diff
gzip ./source/n/rdist/rdist-6.1.5-cleanup.diff
gzip ./source/n/rdist/rdist-6.1.5-varargs.diff
gzip ./source/n/rdist/rdist-6.1.5-bison.diff
gzip ./source/n/rdist/rdist-6.1.5.diff
gzip ./source/n/netdate/netdate.diff
gzip ./source/n/netdate/netdate.diff2
gzip ./source/n/wget/doinst.sh
gzip ./source/n/gpa/doinst.sh
gzip ./source/n/samba/doinst.sh
gzip ./source/n/samba/smb.conf.diff
gzip ./source/n/php/php.ini.diff
gzip ./source/n/php/php.recommended.ini.diff
gzip ./source/n/php/doinst.sh
gzip ./source/n/alpine/alpine.manpage.diff
gzip ./source/n/alpine/alpine.config.h.diff
gzip ./source/n/alpine/alpine.tech-notes.txt.diff
gzip ./source/n/alpine/pinepgp-0.18.0-makefile-sed-fix.diff
gzip ./source/n/alpine/pinepgp.pinegpgp.in.diff
gzip ./source/n/nn/nn.diff
gzip ./source/n/nn/nntpserver
gzip ./source/n/nn/nn.destdir.diff
gzip ./source/n/nn/nn.badnntphost.diff
gzip ./source/n/nn/doinst.sh
gzip ./source/n/nn/NNTP
gzip ./source/n/net-snmp/snmpd.conf
gzip ./source/n/net-snmp/doinst.sh
gzip ./source/n/trn/config.sh
gzip ./source/n/trn/config.x86_64.sh
gzip ./source/n/iproute2/iproute2.dbpath.diff
gzip ./source/n/iproute2/doinst.sh
gzip ./source/n/iproute2/iproute2.iptablespath.diff
gzip ./source/n/biff+comsat/biff+comsat.offset.diff
gzip ./source/n/biff+comsat/biff+comsat-0.17.diff
gzip ./source/n/biff+comsat/biff+comsat.badutmp.diff
gzip ./source/n/telnet/netkit-telnet-0.17.diff
gzip ./source/n/telnet/telnet-OpenBSD-014_telnet.diff
gzip ./source/n/telnet/netkit-telnet-0.17-ayt.patch
gzip ./source/n/telnet/telnet-OpenBSD-20020321.diff
gzip ./source/n/bootp/bootptab
gzip ./source/n/bootp/bootp_2.4.3-15.diff
gzip ./source/n/bridge-utils/bridge-utils.isbridge.diff
gzip ./source/n/netkit-rwho/rwhod_getloadavg.diff
gzip ./source/n/netkit-rwho/netkit-rwho-0.17.diff
gzip ./source/n/mutt/doinst.sh
gzip ./source/n/bind/bind.man.diff
gzip ./source/n/bind/bind.var.run.named.diff
gzip ./source/n/bind/bind.so_bsdcompat.diff
gzip ./source/n/bind/doinst.sh
gzip ./source/n/openssl/openssl.optsx86.diff
gzip ./source/n/openssl/openssl.soname.diff
gzip ./source/n/openssl/doinst.sh-openssl
gzip ./source/n/openssl/doinst.sh-openssl-solibs
gzip ./source/n/openssl/openssl.no-extssl.diff
gzip ./source/n/openssl/certwatch
gzip ./source/n/wireless-tools/wireless_tools.nowhine.diff
gzip ./source/n/wireless-tools/doinst.sh
gzip ./source/n/wireless-tools/wireless_tools.static.diff
gzip ./source/n/yptools/rc.yp
gzip ./source/n/yptools/nsswitch.conf-nis
gzip ./source/n/lynx/lynx.path.diff
gzip ./source/n/lynx/lynx.cfg.diff
gzip ./source/n/ppp/pppsetup-1.98.slack.diff
gzip ./source/n/ppp/realms
gzip ./source/n/ppp/servers
gzip ./source/n/ppp/pppsetup-1.98.pppoff.diff
gzip ./source/n/ppp/options.new
gzip ./source/n/ppp/ppp.slack.diff
gzip ./source/n/ppp/pppsetup-1.98.backupfiles.diff
gzip ./source/n/ppp/doinst.sh
gzip ./source/n/ppp/pppsetup-1.98.moredevs.diff
gzip ./source/n/ppp/radius.msdict
gzip ./source/n/autofs/autofs.x86_64.diff
gzip ./source/n/autofs/autofs.gcc.fix.diff
gzip ./source/n/autofs/autofs-3.1.7.diff
gzip ./source/n/mtr/mtr-0.73.configure.error.diff
gzip ./source/n/cyrus-sasl/rc.saslauthd
gzip ./source/n/cyrus-sasl/doinst.sh
gzip ./source/n/vsftpd/vsftpd.vsf_findlibs.sh.diff
gzip ./source/n/vsftpd/vsftpd.log
gzip ./source/n/vsftpd/vsftpd.conf.diff
gzip ./source/n/vsftpd/doinst.sh
gzip ./source/n/vsftpd/vsftpd.builddefs.diff
gzip ./source/n/netkit-rusers/netkit-rusers-0.17.diff
gzip ./source/n/slrn/doinst.sh
gzip ./source/n/uucp/policy.h.diff
gzip ./source/n/proftpd/doinst.sh
gzip ./source/n/netkit-ntalk/netkit-ntalk-0.11.diff
gzip ./source/n/netkit-ntalk/ntalk-0.17-slackware-alt-talkd.patch
gzip ./source/n/netkit-ntalk/netkit-ntalk-0.17.diff
gzip ./source/n/ntp/doinst.sh
gzip ./source/installer/busybox-1.12.1_inotify.diff
gzip ./source/ap/hplip/hplip.prevent_segfault.diff
gzip ./source/ap/hplip/doinst.sh
gzip ./source/ap/xfsdump/xfsdump.destdir.diff
gzip ./source/ap/sysstat/sysstat.etc.sysstat.diff
gzip ./source/ap/sysstat/sysstat.var.run.diff
gzip ./source/ap/sysstat/sysstat.prefix.usr.diff
gzip ./source/ap/ghostscript-fonts-std/doinst.sh
gzip ./source/ap/groff/groff.docdir.diff
gzip ./source/ap/groff/groff.man.mdoc.local
gzip ./source/ap/cdrtools/doinst.sh
gzip ./source/ap/diffutils/doinst.sh
gzip ./source/ap/diffutils/diffutils-sdiff-no-waitpid.patch
gzip ./source/ap/acct/acct-6.4pre1-6.diff
gzip ./source/ap/acct/acct.logdir.fhs.diff
gzip ./source/ap/amp/amp-gcc34.diff
gzip ./source/ap/ispell/ispell.diff
gzip ./source/ap/seejpeg/seejpeg-1.10.diff
gzip ./source/ap/libx86/lrmi.c.diff
gzip ./source/ap/man-pages/doinst.sh
gzip ./source/ap/alsa-utils/alsa-utils.alsaconf.diff
gzip ./source/ap/alsa-utils/rc.alsa
gzip ./source/ap/workbone/workbone.1.diff
gzip ./source/ap/workbone/workbone_2.40-3.diff
gzip ./source/ap/sudo/doinst.sh
gzip ./source/ap/dvd+rw-tools/dvd+rw-tools.limits.h.diff
gzip ./source/ap/texinfo/dir
gzip ./source/ap/texinfo/doinst.sh
gzip ./source/ap/jove/jove.makefile.diff
gzip ./source/ap/sc/sc-malloc.diff
gzip ./source/ap/sc/sc-gcc34.diff
gzip ./source/ap/man/man-1.6f.nroff.mandoc.diff
gzip ./source/ap/man/doinst.sh
gzip ./source/ap/ash/patches/ash-freebsd.patch
gzip ./source/ap/ash/patches/ash-setmode.patch
gzip ./source/ap/ash/patches/ash-syntax.patch
gzip ./source/ap/ash/patches/ash-makefile.patch
gzip ./source/ap/ash/patches/ash-kill.patch
gzip ./source/ap/ash/patches/ash-test.patch
gzip ./source/ap/ash/patches/ash-echo.patch
gzip ./source/ap/ash/patches/ash-debian.patch
gzip ./source/ap/ash/patches/ash-getcwd.patch
gzip ./source/ap/ash/patches/ash-getopt.patch
gzip ./source/ap/ash/patches/ash-hetio.patch
gzip ./source/ap/ash/patches/ash-glob.patch
gzip ./source/ap/ash/patches/ash-manpage.patch
gzip ./source/ap/ash/patches/ash-ppid.patch
gzip ./source/ap/ash/patches/ash-times.patch
gzip ./source/ap/ash/patches/ash-sighup.patch
gzip ./source/ap/ash/patches/ash-memout.patch
gzip ./source/ap/ash/patches/ash-misc.patch
gzip ./source/ap/ash/patches/ash-builtin.patch
gzip ./source/ap/ash/patches/ash-redir.patch
gzip ./source/ap/ash/patches/ash-jobs.patch
gzip ./source/ap/dmidecode/dmidecode.makefile.diff
gzip ./source/ap/cdparanoia/cdparanoia-III-10.2_cdda_private.patch
gzip ./source/ap/radeontool/radeontool.c.diff
gzip ./source/ap/sqlite/COPYRIGHT
gzip ./source/ap/ghostscript/cidfmap
gzip ./source/ap/linuxdoc-tools/sources/docbook_4.5-4.diff
gzip ./source/ap/linuxdoc-tools/sources/libsgmls-perl_1.03ii-32.diff
gzip ./source/ap/dmapi/dmapi.destdir.diff
gzip ./source/ap/rpm/doinst.sh
gzip ./source/ap/rpm/Packages
gzip ./source/ap/at/doinst.sh
gzip ./source/ap/aumix/aumix.alsa.diff
gzip ./source/ap/mysql/rc.mysqld
gzip ./source/ap/mysql/doinst.sh
gzip ./source/ap/jed/jed.mouse.diff
gzip ./source/ap/jed/jed.multibyte.diff
gzip ./source/ap/foomatic-filters/doinst.sh
gzip ./source/ap/zsh/zsh-4.3.10-add_new_pkg_completion.diff
gzip ./source/ap/zsh/doinst.sh
gzip ./source/ap/flac/flac.man.diff
gzip ./source/ap/vim/patches/7.2.130
gzip ./source/ap/vim/patches/7.2.243
gzip ./source/ap/vim/patches/7.2.194
gzip ./source/ap/vim/patches/7.2.110
gzip ./source/ap/vim/patches/7.2.068
gzip ./source/ap/vim/patches/7.2.085
gzip ./source/ap/vim/patches/7.2.105
gzip ./source/ap/vim/patches/7.2.095
gzip ./source/ap/vim/patches/7.2.113
gzip ./source/ap/vim/patches/7.2.024
gzip ./source/ap/vim/patches/7.2.062
gzip ./source/ap/vim/patches/7.2.136
gzip ./source/ap/vim/patches/7.2.106
gzip ./source/ap/vim/patches/7.2.033
gzip ./source/ap/vim/patches/7.2.147
gzip ./source/ap/vim/patches/7.2.189
gzip ./source/ap/vim/patches/7.2.163
gzip ./source/ap/vim/patches/7.2.201
gzip ./source/ap/vim/patches/7.2.120
gzip ./source/ap/vim/patches/7.2.240
gzip ./source/ap/vim/patches/7.2.035
gzip ./source/ap/vim/patches/7.2.069
gzip ./source/ap/vim/patches/7.2.244
gzip ./source/ap/vim/patches/7.2.153
gzip ./source/ap/vim/patches/7.2.030
gzip ./source/ap/vim/patches/7.2.154
gzip ./source/ap/vim/patches/7.2.179
gzip ./source/ap/vim/patches/7.2.185
gzip ./source/ap/vim/patches/7.2.064
gzip ./source/ap/vim/patches/7.2.116
gzip ./source/ap/vim/patches/7.2.010
gzip ./source/ap/vim/patches/7.2.121
gzip ./source/ap/vim/patches/7.2.245
gzip ./source/ap/vim/patches/7.2.117
gzip ./source/ap/vim/patches/7.2.178
gzip ./source/ap/vim/patches/7.2.124
gzip ./source/ap/vim/patches/7.2.101
gzip ./source/ap/vim/patches/7.2.061
gzip ./source/ap/vim/patches/7.2.187
gzip ./source/ap/vim/patches/7.2.060
gzip ./source/ap/vim/patches/7.2.075
gzip ./source/ap/vim/patches/7.2.131
gzip ./source/ap/vim/patches/7.2.166
gzip ./source/ap/vim/patches/7.2.219
gzip ./source/ap/vim/patches/7.2.090
gzip ./source/ap/vim/patches/7.2.170
gzip ./source/ap/vim/patches/7.2.129
gzip ./source/ap/vim/patches/7.2.088
gzip ./source/ap/vim/patches/7.2.200
gzip ./source/ap/vim/patches/7.2.204
gzip ./source/ap/vim/patches/7.2.216
gzip ./source/ap/vim/patches/7.2.097
gzip ./source/ap/vim/patches/7.2.125
gzip ./source/ap/vim/patches/7.2.041
gzip ./source/ap/vim/patches/7.2.013
gzip ./source/ap/vim/patches/7.2.055
gzip ./source/ap/vim/patches/7.2.152
gzip ./source/ap/vim/patches/7.2.169
gzip ./source/ap/vim/patches/7.2.128
gzip ./source/ap/vim/patches/7.2.126
gzip ./source/ap/vim/patches/7.2.157
gzip ./source/ap/vim/patches/7.2.079
gzip ./source/ap/vim/patches/7.2.222
gzip ./source/ap/vim/patches/7.2.007
gzip ./source/ap/vim/patches/7.2.180
gzip ./source/ap/vim/patches/7.2.044
gzip ./source/ap/vim/patches/7.2.045
gzip ./source/ap/vim/patches/7.2.234
gzip ./source/ap/vim/patches/7.2.098
gzip ./source/ap/vim/patches/7.2.239
gzip ./source/ap/vim/patches/7.2.237
gzip ./source/ap/vim/patches/7.2.056
gzip ./source/ap/vim/patches/7.2.191
gzip ./source/ap/vim/patches/7.2.159
gzip ./source/ap/vim/patches/7.2.080
gzip ./source/ap/vim/patches/7.2.214
gzip ./source/ap/vim/patches/7.2.142
gzip ./source/ap/vim/patches/7.2.172
gzip ./source/ap/vim/patches/7.2.134
gzip ./source/ap/vim/patches/7.2.135
gzip ./source/ap/vim/patches/7.2.076
gzip ./source/ap/vim/patches/7.2.071
gzip ./source/ap/vim/patches/7.2.190
gzip ./source/ap/vim/patches/7.2.220
gzip ./source/ap/vim/patches/7.2.070
gzip ./source/ap/vim/patches/7.2.059
gzip ./source/ap/vim/patches/7.2.006
gzip ./source/ap/vim/patches/7.2.096
gzip ./source/ap/vim/patches/7.2.226
gzip ./source/ap/vim/patches/7.2.023
gzip ./source/ap/vim/patches/7.2.083
gzip ./source/ap/vim/patches/7.2.054
gzip ./source/ap/vim/patches/7.2.122
gzip ./source/ap/vim/patches/7.2.052
gzip ./source/ap/vim/patches/7.2.235
gzip ./source/ap/vim/patches/7.2.241
gzip ./source/ap/vim/patches/7.2.111
gzip ./source/ap/vim/patches/7.2.034
gzip ./source/ap/vim/patches/7.2.081
gzip ./source/ap/vim/patches/7.2.114
gzip ./source/ap/vim/patches/7.2.047
gzip ./source/ap/vim/patches/7.2.158
gzip ./source/ap/vim/patches/7.2.149
gzip ./source/ap/vim/patches/7.2.032
gzip ./source/ap/vim/patches/7.2.156
gzip ./source/ap/vim/patches/7.2.009
gzip ./source/ap/vim/patches/7.2.016
gzip ./source/ap/vim/patches/7.2.004
gzip ./source/ap/vim/patches/7.2.091
gzip ./source/ap/vim/patches/7.2.205
gzip ./source/ap/vim/patches/7.2.150
gzip ./source/ap/vim/patches/7.2.236
gzip ./source/ap/vim/patches/7.2.089
gzip ./source/ap/vim/patches/7.2.092
gzip ./source/ap/vim/patches/7.2.160
gzip ./source/ap/vim/patches/7.2.206
gzip ./source/ap/vim/patches/7.2.199
gzip ./source/ap/vim/patches/7.2.162
gzip ./source/ap/vim/patches/7.2.215
gzip ./source/ap/vim/patches/7.2.102
gzip ./source/ap/vim/patches/7.2.207
gzip ./source/ap/vim/patches/7.2.198
gzip ./source/ap/vim/patches/7.2.197
gzip ./source/ap/vim/patches/7.2.094
gzip ./source/ap/vim/patches/7.2.043
gzip ./source/ap/vim/patches/7.2.186
gzip ./source/ap/vim/patches/7.2.223
gzip ./source/ap/vim/patches/7.2.046
gzip ./source/ap/vim/patches/7.2.230
gzip ./source/ap/vim/patches/7.2.042
gzip ./source/ap/vim/patches/7.2.228
gzip ./source/ap/vim/patches/7.2.058
gzip ./source/ap/vim/patches/7.2.029
gzip ./source/ap/vim/patches/7.2.077
gzip ./source/ap/vim/patches/7.2.217
gzip ./source/ap/vim/patches/7.2.078
gzip ./source/ap/vim/patches/7.2.093
gzip ./source/ap/vim/patches/7.2.218
gzip ./source/ap/vim/patches/7.2.181
gzip ./source/ap/vim/patches/7.2.138
gzip ./source/ap/vim/patches/7.2.119
gzip ./source/ap/vim/patches/7.2.063
gzip ./source/ap/vim/patches/7.2.225
gzip ./source/ap/vim/patches/7.2.003
gzip ./source/ap/vim/patches/7.2.144
gzip ./source/ap/vim/patches/7.2.145
gzip ./source/ap/vim/patches/7.2.065
gzip ./source/ap/vim/patches/7.2.184
gzip ./source/ap/vim/patches/7.2.188
gzip ./source/ap/vim/patches/7.2.099
gzip ./source/ap/vim/patches/7.2.109
gzip ./source/ap/vim/patches/7.2.074
gzip ./source/ap/vim/patches/7.2.209
gzip ./source/ap/vim/patches/7.2.087
gzip ./source/ap/vim/patches/7.2.107
gzip ./source/ap/vim/patches/7.2.143
gzip ./source/ap/vim/patches/7.2.115
gzip ./source/ap/vim/patches/7.2.233
gzip ./source/ap/vim/patches/7.2.028
gzip ./source/ap/vim/patches/7.2.025
gzip ./source/ap/vim/patches/7.2.082
gzip ./source/ap/vim/patches/7.2.183
gzip ./source/ap/vim/patches/7.2.165
gzip ./source/ap/vim/patches/7.2.037
gzip ./source/ap/vim/patches/7.2.213
gzip ./source/ap/vim/patches/7.2.175
gzip ./source/ap/vim/patches/7.2.238
gzip ./source/ap/vim/patches/7.2.168
gzip ./source/ap/vim/patches/7.2.048
gzip ./source/ap/vim/patches/7.2.021
gzip ./source/ap/vim/patches/7.2.104
gzip ./source/ap/vim/patches/7.2.015
gzip ./source/ap/vim/patches/7.2.103
gzip ./source/ap/vim/patches/7.2.051
gzip ./source/ap/vim/patches/7.2.039
gzip ./source/ap/vim/patches/7.2.140
gzip ./source/ap/vim/patches/7.2.112
gzip ./source/ap/vim/patches/7.2.050
gzip ./source/ap/vim/patches/7.2.203
gzip ./source/ap/vim/patches/7.2.132
gzip ./source/ap/vim/patches/7.2.017
gzip ./source/ap/vim/patches/7.2.242
gzip ./source/ap/vim/patches/7.2.137
gzip ./source/ap/vim/patches/7.2.195
gzip ./source/ap/vim/patches/7.2.167
gzip ./source/ap/vim/patches/7.2.141
gzip ./source/ap/vim/patches/7.2.227
gzip ./source/ap/vim/patches/7.2.139
gzip ./source/ap/vim/patches/7.2.018
gzip ./source/ap/vim/patches/7.2.176
gzip ./source/ap/vim/patches/7.2.001
gzip ./source/ap/vim/patches/7.2.123
gzip ./source/ap/vim/patches/7.2.208
gzip ./source/ap/vim/patches/7.2.020
gzip ./source/ap/vim/patches/7.2.193
gzip ./source/ap/vim/patches/7.2.146
gzip ./source/ap/vim/patches/7.2.100
gzip ./source/ap/vim/patches/7.2.229
gzip ./source/ap/vim/patches/7.2.164
gzip ./source/ap/vim/patches/7.2.019
gzip ./source/ap/vim/patches/7.2.211
gzip ./source/ap/vim/patches/7.2.108
gzip ./source/ap/vim/patches/7.2.224
gzip ./source/ap/vim/patches/7.2.026
gzip ./source/ap/vim/patches/7.2.192
gzip ./source/ap/vim/patches/7.2.040
gzip ./source/ap/vim/patches/7.2.171
gzip ./source/ap/vim/patches/7.2.005
gzip ./source/ap/vim/patches/7.2.182
gzip ./source/ap/vim/patches/7.2.049
gzip ./source/ap/vim/patches/7.2.053
gzip ./source/ap/vim/patches/7.2.031
gzip ./source/ap/vim/patches/7.2.212
gzip ./source/ap/vim/patches/7.2.118
gzip ./source/ap/vim/patches/7.2.038
gzip ./source/ap/vim/patches/7.2.196
gzip ./source/ap/vim/patches/7.2.232
gzip ./source/ap/vim/patches/7.2.127
gzip ./source/ap/vim/patches/7.2.151
gzip ./source/ap/vim/patches/7.2.073
gzip ./source/ap/vim/patches/7.2.066
gzip ./source/ap/vim/patches/7.2.086
gzip ./source/ap/vim/patches/7.2.173
gzip ./source/ap/vim/patches/7.2.012
gzip ./source/ap/vim/patches/7.2.057
gzip ./source/ap/vim/patches/7.2.067
gzip ./source/ap/vim/patches/7.2.221
gzip ./source/ap/vim/patches/7.2.072
gzip ./source/ap/vim/patches/7.2.022
gzip ./source/ap/vim/patches/7.2.210
gzip ./source/ap/vim/patches/7.2.148
gzip ./source/ap/vim/patches/7.2.133
gzip ./source/ap/vim/patches/7.2.011
gzip ./source/ap/vim/patches/7.2.008
gzip ./source/ap/vim/patches/7.2.174
gzip ./source/ap/vim/patches/7.2.161
gzip ./source/ap/vim/patches/7.2.177
gzip ./source/ap/vim/patches/7.2.002
gzip ./source/ap/vim/patches/7.2.084
gzip ./source/ap/vim/patches/7.2.036
gzip ./source/ap/vim/patches/7.2.202
gzip ./source/ap/vim/patches/7.2.231
gzip ./source/ap/vim/patches/7.2.014
gzip ./source/ap/vim/patches/7.2.027
gzip ./source/ap/vim/patches/7.2.155
gzip ./source/ap/vim/vim.vimrc.diff
gzip ./source/ap/vim/doinst.sh
gzip ./source/ap/a2ps/a2ps.diff
gzip ./source/ap/a2ps/psutils.destdir.diff
gzip ./source/ap/a2ps/psutils.diff
gzip ./source/ap/a2ps/a2ps.a2ps_cfg.in.diff
gzip ./source/ap/lm_sensors/lm_sensors.makefile.diff
gzip ./source/d/autoconf/doinst.sh
gzip ./source/d/ruby/ruby.x86_64.diff
gzip ./source/d/doxygen/doxygen.qt4.diff
gzip ./source/d/libtool/libtool.no.moved.warning.diff
gzip ./source/d/libtool/doinst.sh
gzip ./source/d/rcs/rcs-5.7.diff
gzip ./source/d/dev86/dev86-x86_64.noelks.patch
gzip ./source/d/dev86/dev86-x86_64.patch
gzip ./source/d/automake/doinst.sh
gzip ./source/d/python/python.readline.set_pre_input_hook.diff
gzip ./source/d/python/python.pure64.diff
gzip ./source/d/python/python.x86_64.diff
gzip ./source/d/pmake/pmake.strerror.strdup.diff
gzip ./source/d/pmake/pmake.txt
gzip ./source/d/pmake/pmake_1.111-1.diff
gzip ./source/d/pkg-config/doinst.sh
gzip ./source/d/gcc/gcc-no_fixincludes.diff
gzip ./source/d/p2c/p2c_1.21alpha2-2.1.diff
gzip ./source/d/p2c/p2c.examples.diff
gzip ./source/d/p2c/p2c_time.diff
gzip ./source/d/perl/perl.configure.multilib.patch
gzip ./source/d/perl/doinst.sh
gzip ./source/xap/rxvt/rxvt.utempter.diff
gzip ./source/xap/xmms/xmms.gtk.doublesize.diff
gzip ./source/xap/xmms/xmms.wmxmms_vis_depth_workaround.diff
gzip ./source/xap/gxine/gxine.desktop
gzip ./source/xap/gftp/gftp.desktop
gzip ./source/xap/xfce/patches/exo_quoting_fix.diff
gzip ./source/xap/xfce/patches/migrate-itheme-smartly.diff
gzip ./source/xap/xfce/patches/xfdesktop-fix_education_icon.diff
gzip ./source/xap/xfce/patches/xfcalendar.desktop.in.diff
gzip ./source/xap/xfce/patches/launcher-plugin-migrate-icon-cat.diff
gzip ./source/xap/xfce/patches/terminal-0.4.0-fixup_docdir.diff
gzip ./source/xap/xfce/patches/thunar-1.0.1-fixup_docdir.diff
gzip ./source/xap/fluxbox/xinitrc.fluxbox
gzip ./source/xap/mozilla-thunderbird/mozilla-thunderbird-firefox.diff
gzip ./source/xap/xine-ui/xine.desktop
gzip ./source/xap/xfce4-power-manager/doinst.sh
gzip ./source/xap/xpaint/xpaint_2.7.8.1-1.2.diff
gzip ./source/xap/xpaint/xpaint_xaw3d_no_scroll_mode.diff
gzip ./source/xap/xchat/patches/xc286-smallfixes.diff
gzip ./source/xap/xchat/patches/xchat.gtk_2_14.diff
gzip ./source/xap/gkrellm/gkrellm.theme.defaults.diff
gzip ./source/xap/x3270/doinst.sh
gzip ./source/xap/xxgdb/xxgdb.fix_glibc_and_gcc.diff
gzip ./source/xap/blackbox/xinitrc.blackbox
gzip ./source/xap/blackbox/blackbox_0.65.0-5.diff
gzip ./source/xap/windowmaker/windowmaker.no-mmx.diff
gzip ./source/xap/windowmaker/wmaker.inst.diff
gzip ./source/xap/audacious/audacious.handle_cmd_line_options.diff
gzip ./source/xap/electricsheep/electricsheep.mplayer.diff
gzip ./source/xap/gucharmap/doinst.sh
gzip ./source/xap/pidgin/purple-allow-sign-rsa-md5.patch
gzip ./source/xap/xgames/xlander-2009-07-18.diff
gzip ./source/xap/xgames/xcolormap.diff
gzip ./source/xap/xgames/spider.diff
gzip ./source/xap/xgames/xcuckoo.diff
gzip ./source/xap/xgames/maze.diff
gzip ./source/xap/xgames/xlander.fixes.diff
gzip ./source/xap/xscreensaver/setuid.c
gzip ./source/xap/xscreensaver/xscreensaver.setuid.diff
gzip ./source/xap/xscreensaver/xscreensaver.electricsheep.diff
gzip ./source/xap/sane/doinst.sh
gzip ./source/xap/sane/dll.conf.additions
gzip ./source/xap/seamonkey/seamonkey.moz_plugin_path.diff
gzip ./source/xap/seamonkey/doinst.sh
gzip ./source/xap/gnuchess/xboard.buffer_overflow_fix.diff
gzip ./source/xap/gnuchess/gnuchess.gcc4_fix.diff
gzip ./source/xap/gnuchess/gnuchess.SlackBuild.diff
gzip ./source/xap/gnuchess/xboard.infodir.diff
gzip ./source/xap/audacious-plugins/amidi-plug.fix-drct.diff
gzip ./source/xap/audacious-plugins/audacious-plugins.libmtp8.diff
gzip ./source/xap/xpdf/xpdf-resizefix.diff
gzip ./source/xap/xpdf/xpdfrc.diff
gzip ./source/xap/xpdf/xpdf-hebrew.diff
gzip ./source/xap/xpdf/xpdf_3.02-1.3.diff
gzip ./source/xap/xpdf/xpdf-thai.diff
gzip ./source/xap/xpdf/xpdf-korean.diff
gzip ./source/xap/xpdf/xpdf-chinese-traditional.diff
gzip ./source/xap/xpdf/xpdf-greek.diff
gzip ./source/xap/xpdf/xpdf-chinese-simplified.diff
gzip ./source/xap/xpdf/xpdf-turkish.diff
gzip ./source/xap/xpdf/xpdf-arabic.diff
gzip ./source/xap/xpdf/xpdf-japanese.diff
gzip ./source/xap/xpdf/xpdf-cyrillic.diff
gzip ./source/xap/xpdf/xpdf-latin2.diff
gzip ./source/xap/seyon/seyon_2.20c-16.diff
gzip ./source/xap/xlockmore/xlockmore.bitmap.diff
gzip ./source/xap/fvwm/xinitrc.fvwm2
gzip ./source/xap/fvwm/fvwm.colormap.diff
gzip ./source/xap/fvwm/doinst.sh
gzip ./source/xap/fvwm/system.fvwm2rc
gzip ./source/xap/xv/xv.prefix_x86_64.diff
gzip ./source/xap/xv/xv.prefix.diff
gzip ./source/xap/xv/xv-3.10a.patch
gzip ./source/xap/mozilla-firefox/mozilla-firefox-mimeTypes-fix.diff
gzip ./source/xap/mozilla-firefox/firefox.moz_plugin_path.diff
gzip ./source/xap/mozilla-firefox/mimeTypes.rdf
gzip ./source/xap/gqview/doinst.sh
gzip ./source/x/x11-skel/doinst.sh
gzip ./source/x/xaw3d/Xaw3d-1.5-debian-fixes.diff
gzip ./source/x/xaw3d/Xaw3d-1.5E.diff
gzip ./source/x/x11/post-install/xorg-cf-files/x11.tmpl.lib64.kludge.diff
gzip ./source/x/x11/patch/xorg-server/x11.startwithblackscreen.diff
gzip ./source/x/x11/patch/xscope/xscope-1.1-scope.c.diff
gzip ./source/x/x11/patch/compiz/compiz-0.7.8-kde42-krunner.patch
gzip ./source/x/x11/patch/compiz/compiz-0.7.8-kde42-crash.patch
gzip ./source/x/x11/patch/compiz/compiz-0.7.8-kde42.patch
gzip ./source/x/ttf-indic-fonts/ttf-indic-fonts.copyright.diff
gzip ./source/x/ttf-indic-fonts/doinst.sh
gzip ./source/x/scim-hangul/scim-hangul.gcc43.diff
gzip ./source/x/xdg-utils/doinst.sh
gzip ./source/x/liberation-fonts-ttf/doinst.sh
gzip ./source/x/scim-anthy/scim-anthy.gcc43.diff
gzip ./source/x/dejavu-fonts-ttf/doinst.sh
gzip ./source/x/fontconfig/fontconfig.dejavu.diff
gzip ./source/x/fontconfig/fontconfig.font.dir.list.diff
gzip ./source/x/scim-pinyin/scim-pinyin.gcc43.diff
gzip ./source/t/transfig/transfig.diff
gzip ./source/t/transfig/transfig.3.2.4-gcc4.patch
gzip ./source/t/tetex/tetex.dvipdfm.mkstemp.diff
gzip ./source/t/tetex/tetex.fontcachedirinhome.diff
gzip ./source/t/tetex/tetex.etex.diff
gzip ./source/t/tetex/tetex.tmp.cleanup.diff
gzip ./source/t/tetex/tetex.amstex.fmtutil.diff
gzip ./source/t/tetex/tetex.browsers.diff
gzip ./source/t/tetex/tetex.scripts.mktemp.diff
gzip ./source/t/tetex/tetex.var.fonts.diff
gzip ./source/t/tetex/tetex.CVE-2005-3193.diff
gzip ./source/t/xfig/xfig.3.2.4-null.diff
gzip ./source/t/xfig/xfig-3.2.4-mkstemp.diff
gzip ./source/t/xfig/xfig.3.2.3d-international-std-fonts.diff
gzip ./source/t/xfig/xfig.3.2.4-quiet.diff
gzip ./source/t/xfig/xfig.no.pdf.ref.diff
gzip ./source/t/xfig/xfig.3.2.3d-xcolor.diff
gzip ./source/t/xfig/xfig.3.2.4-gcc4.diff
gzip ./source/t/xfig/xfig.fig.ad.diff
gzip ./source/t/xfig/xfig.no.xfig_ref_en.pdf.diff
gzip ./source/t/xfig/xfig.docs.location.diff
gzip ./source/t/xfig/xfig.3.2.3d-xim.diff
gzip ./source/t/xfig/xfig.3.2.4-locale.diff
gzip ./source/t/xfig/xfig.3.2.4.diff
gzip ./source/t/xfig/xfig.3.2.4-urw-fonts.diff
gzip ./source/y/bsd-games/bsd-games.ospeed.diff
gzip ./source/y/bsd-games/bsd-games.config.params.diff
gzip ./source/y/bsd-games/bsd-games.strfile.8.diff
gzip ./source/y/bsd-games/bsd-games.phantasia_install_fix.diff
gzip ./source/y/bsd-games/bsd-games.fortlen.diff
gzip ./source/y/bsd-games/bsd-games.trek-gcc4.diff
gzip ./source/y/bsd-games/hangman-words
gzip ./source/y/bsd-games/bsd-games.pom.diff
gzip ./source/y/bsd-games/bsd-games.fortunepath.diff
gzip ./source/kde/kdeutils/doinst.sh
gzip ./source/kde/kdemultimedia/doinst.sh
gzip ./source/kde/kdeadmin/doinst.sh
gzip ./source/kde/k3b/k3b.internal.libsamplerate.diff
gzip ./source/kde/k3b/doinst.sh
gzip ./source/kde/kdeartwork/doinst.sh
gzip ./source/kde/amarok/doinst.sh
gzip ./source/kde/amarok/amarok.qtscript.optional.diff
gzip ./source/kde/ktorrent/doinst.sh
gzip ./source/kde/kaudiocreator/doinst.sh
gzip ./source/kde/kdenetwork/kopete-r986796.diff
gzip ./source/kde/kdenetwork/doinst.sh
gzip ./source/kde/kdebase-runtime/kdebase-runtime-text-render-969192.diff
gzip ./source/kde/kdebase-runtime/doinst.sh
gzip ./source/kde/kdebase-workspace/doinst.sh
gzip ./source/kde/kdetoys/doinst.sh
gzip ./source/kde/kdewebdev/doinst.sh
gzip ./source/kde/kdewebdev/kde4-kdewebdev-findtidy.diff
gzip ./source/kde/kdepim/doinst.sh
gzip ./source/kde/kdeedu/doinst.sh
gzip ./source/kde/kdeaccessibility/doinst.sh
gzip ./source/kde/kdeplasma-addons/doinst.sh
gzip ./source/kde/kdegraphics/doinst.sh
gzip ./source/kde/kdebase/doinst.sh
gzip ./source/kde/skanlite/doinst.sh
gzip ./source/kde/koffice/doinst.sh
gzip ./source/kde/kdegames/doinst.sh
gzip ./source/kde/kdevplatform/doinst.sh
gzip ./source/kde/kdevelop/doinst.sh
gzip ./source/kde/kdelibs/kdesu-allow_NOPASS_in_suauth.patch
gzip ./source/kde/kdelibs/doinst.sh
gzip ./source/kde/kdelibs/fixPopupForPlasmaboard.diff
gzip ./source/kde/kdesdk/doinst.sh
gzip ./source/tcl/tix/tix.soname.patch
gzip ./source/tcl/tix/tix.tcl8.5.patch
gzip ./source/tcl/expect/expect.exp_main_tk.c.version.require.diff
gzip ./source/tcl/hfsutils/hfsutils.errno.diff
gzip ./source/tcl/tclx/tclx-8.4.configure.diff
gzip ./source/tcl/tclx/tclx-8.4.gcc4.diff
gzip ./source/l/hal/patches/ignore_dupe_add_events.diff
gzip ./source/l/hal/patches/allow_uid_gid_ntfs.diff
gzip ./source/l/hal/patches/fix_led_crash.diff
gzip ./source/l/hal/patches/fix_segfault_in_mdraid.diff
gzip ./source/l/hal/patches/fixup_udi_strings.diff
gzip ./source/l/hal/patches/10-keymap.fdi-restore_zap.diff
gzip ./source/l/hal/patches/regen_fdi_cache_if_zero_size.diff
gzip ./source/l/hal/patches/set_X_keymap_properly.diff
gzip ./source/l/hal/patches/hide_more_invalid_partitions.diff
gzip ./source/l/hal/patches/check_udi_properly.diff
gzip ./source/l/hal/patches/use_udevadm_not_udevinfo.patch
gzip ./source/l/hal/patches/fix_md_crash.diff
gzip ./source/l/hal/hal.conf
gzip ./source/l/hal/doinst.sh
gzip ./source/l/hal/rc.hald
gzip ./source/l/ncurses/ncurses.mkhashsize.diff
gzip ./source/l/shared-mime-info/doinst.sh
gzip ./source/l/db42/patch.4.2.52.2
gzip ./source/l/db42/patch.4.2.52.1
gzip ./source/l/db42/patch.4.2.52.4
gzip ./source/l/db42/patch.4.2.52.3
gzip ./source/l/hicolor-icon-theme/doinst.sh
gzip ./source/l/svgalib/svgalib.nohelper.diff
gzip ./source/l/svgalib/svgalib-1.9.25-kernel-2.6.26.diff
gzip ./source/l/svgalib/svgalib.prefix.diff
gzip ./source/l/urwid/LICENSE
gzip ./source/l/djvulibre/doinst.sh
gzip ./source/l/glib2/glib-CVE-2008-4316.diff
gzip ./source/l/glib2/doinst.sh
gzip ./source/l/sdl/SDL_mixer-1.2.8.usrlocal.diff
gzip ./source/l/parted/parted.configure.diff
gzip ./source/l/libtiff/tiff-3.8.2.goo-sec.diff
gzip ./source/l/libtiff/tiff-3.8.2.tiffsplit.commandline.overflow.diff
gzip ./source/l/glibc/glibc-2.10-dns-no-gethostbyname4.diff
gzip ./source/l/glibc/glibc.ru_RU.CP1251.diff
gzip ./source/l/glibc/glibc.nis-netgroups.diff
gzip ./source/l/glibc/glibc.getcwd.max.macro.diff
gzip ./source/l/glibc/is_IS.diff
gzip ./source/l/glibc/glibc.locale.no-archive.diff
gzip ./source/l/glibc/glibc.revert.to.fix.build.breakages.diff
gzip ./source/l/libvisual-plugins/libvisual-plugins.gstreamer.diff
gzip ./source/l/qt/qt.x86.cflags.diff
gzip ./source/l/qt/qt.mysql.h.diff
gzip ./source/l/qt/doinst.sh
gzip ./source/l/librsvg/librsvg_seamonkey-config.diff
gzip ./source/l/netpbm/Makefile.config
gzip ./source/l/esound/doinst.sh
gzip ./source/l/qtscriptgenerator/include-everything.patch
gzip ./source/l/libtermcap/termcap.h.diff
gzip ./source/l/libtermcap/termcap-compat_1.2.3.diff
gzip ./source/l/libtermcap/termcap.bufsize.diff
gzip ./source/l/openexr/openexr.gcc43.diff
gzip ./source/l/lesstif/lesstif.gcc42.diff
gzip ./source/l/lesstif/lesstif.x86_64.patch
gzip ./source/l/lesstif/lesstif.rendertable.check.diff
gzip ./source/l/lesstif/lesstif.Makefile.in.patch
gzip ./source/l/lesstif/doinst.sh
gzip ./source/l/lesstif/lesstif.PutPixel32.patch
gzip ./source/l/imlib/imlib.mitshm.render.diff
gzip ./source/l/libjpeg/jpeg-6b.diff
gzip ./source/l/gtk+2/gtk.nsplugin.diff
gzip ./source/l/gtk+2/gtk.pnglz.diff
gzip ./source/l/gtk+2/doinst.sh
gzip ./source/l/libnl/libnl-include_limits.h.patch
gzip ./source/l/pango/pango.etc.host.location.diff
gzip ./source/l/desktop-file-utils/doinst.sh
gzip ./source/l/db44/patch.4.4.20.2
gzip ./source/l/db44/patch.4.4.20.1
gzip ./source/l/libcap/libcap.capability.h.fix.broken.includes.diff
gzip ./source/l/freetype/freetype.bytecode.interpreter.diff
gzip ./source/l/freetype/freetype.illadvisederror.diff
gzip ./source/l/freetype/freetype.subpixel.rendering.diff
gzip ./source/l/qca-ossl/qca-ossl.nowhirlpool.diff
gzip ./source/l/akonadi/doinst.sh
gzip ./source/l/boost/boost.ifdef_placement.diff
gzip ./source/l/icon-naming-utils/icon-naming-utils.pkgconfigdir.diff
gzip ./source/l/fuse/doinst.sh
gzip ./source/l/gnome-icon-theme/doinst.sh
gzip ./source/l/gnome-icon-theme/gnome-icon-theme.pkgconfig.path.diff
gzip ./source/l/libpng/libpng.libs.diff
gzip ./source/l/libexif/libexif.pc.diff
bzip2 ./source/n/curl/cacert.pem
bzip2 ./source/xap/xv/xv-3.10a-jumbo-enh-patch-20050501.txt
bzip2 ./source/xap/xv/xv-3.10a-jumbo-fix-patch-20050410.txt
bzip2 ./source/x/ttf-indic-fonts/Samyak_Malayalam.ttf
bzip2 ./source/x/ttf-indic-fonts/COPYING
bzip2 ./source/l/gtk+/gtk+1.2_1.2.10-18.diff
bzip2 ./source/l/glib/glib1.2_1.2.10-17.diff
