#!/bin/bash

START="no"

if [ "$XIM" = "ibus" ]; then
  START="yes"
fi

if [ "$XIM_PROGRAM" = "ibus" ]; then
  START="yes"
fi

if [ "$GTK_IM_MODULE" = "ibus" ]; then
  START="yes"
fi

if [ "$QT_IM_MOFULE" = "ibus" ]; then
  START="yes"
fi

if [ "$START" = "yes" ]; then
  if [ "$1" = "--plasma" ]; then
    ibus-daemon -drx --panel=/usr/libLIBDIRSUFFIX/libexec/kimpanel-ibus-panel
  else
    ibus-daemon -drx
  fi
fi
