#!/bin/bash

# Copyright 2008, 2009, 2010, 2012, 2016, 2017, 2018, 2021  Patrick J. Volkerding, Sebeka, Minnesota, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=lynx
PKGVER=2.9.2
DIRVER=2.9.2
BUILD=${BUILD:-1}

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i686 ;;
    arm*) export ARCH=arm ;;
    loongarch64) export ARCH=loong64 ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$PKGVER-$ARCH-$BUILD.txz"
  exit 0
fi

if [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=pentium4 -mtune=generic"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "loong64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

TMP=${TMP:-/tmp}
PKG=$TMP/package-lynx

rm -rf $PKG
mkdir -p $TMP $PKG/usr/lib${LIBDIRSUFFIX}/lynx
cd $TMP
rm -rf lynx$DIRVER
tar xvf $CWD/lynx${PKGVER}.tar.?z* || exit 1
cd lynx$DIRVER || exit 1

find . -name "*~" -exec rm -f {} \+
chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+

zcat $CWD/lynx-CVE-2008-4690.patch.gz | patch -p1 --verbose || exit 1

# Change default colors:
zcat $CWD/lynx.cfg.diff.gz | patch -p1 --verbose --backup || exit 1

find . -name "*.orig" -exec rm "{}" \;

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --libdir=/usr/lib${LIBDIRSUFFIX}/lynx \
  --datadir=/usr/share/lynx \
  --mandir=/usr/man \
  --enable-default-colors \
  --with-screen=ncursesw \
  --enable-widec \
  --enable-gzip-help \
  --with-zlib \
  --enable-read-eta \
  --enable-scrollbar \
  --with-ssl \
  --enable-ipv6 \
  --enable-color-style \
  --enable-prettysrc \
  --enable-source-cache \
  --enable-nsl-fork \
  --enable-nls \
  --enable-persistent-cookies \
  --enable-vertrace \
  --disable-full-paths \
  --enable-addrlist-page \
  --enable-charset-choice \
  --enable-cjk \
  --enable-htmlized-cfg \
  --enable-justify-elts \
  --enable-locale-charset \
  --enable-externs \
  --enable-cgi-links \
  --enable-change-exec \
  --enable-exec-links \
  --enable-exec-scripts \
  --enable-internal-links \
  --with-bzlib \
  --build=loongarch64-slackware-linux

make $NUMJOBS || make || exit 1
make install DESTDIR=$PKG || exit 1
make install-help DESTDIR=$PKG || exit 1
make install-doc DESTDIR=$PKG || exit 1

# Make lynx.cfg a preserved config file:
mv $PKG/etc/lynx.cfg $PKG/etc/lynx.cfg.new

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

# Correct $DESTDIR brokenness:
( cd $PKG/usr/share/lynx/lynx_help
  rm -f COPYHEADER COPYING
  ln -sf ../lynx_doc/COPYHEADER .
  ln -sf ../lynx_doc/COPYING .
)
# Add documentation symlinks:
( mkdir -p $PKG/usr/doc/lynx-$PKGVER
  cd $PKG/usr/doc/lynx-$PKGVER
  ln -sf /usr/share/lynx/lynx_doc .
  ln -sf /usr/share/lynx/lynx_help .
)

# If there's a ChangeLog, installing at least part of the recent history
# is useful, but don't let it get totally out of control:
if [ -r CHANGES ]; then
  DOCSDIR=$(echo $PKG/usr/share/lynx/lynx_doc)
  cat CHANGES | head -n 1000 > $DOCSDIR/CHANGES
  touch -r CHANGES $DOCSDIR/CHANGES
fi

gzip -9 $PKG/usr/man/man?/*.?

mkdir -p $PKG/install
zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $TMP/lynx-$PKGVER-$ARCH-$BUILD.txz

