# Remove data generated by doinst.sh
rm -rf usr/share/texmf-config
rm -rf usr/share/texmf-local
rm -rf usr/share/texmf-var

if [ -x /usr/bin/install-info -a -d usr/info ]; then
  ( cd usr/info
    rm -f dir
    for i in *.info*; do /usr/bin/install-info $i dir 2>/dev/null; done
  )
fi
