#!/bin/sh

# Copyright 2008, 2009, 2010, 2012, 2013, 2014, 2015, 2020  Patrick J. Volkerding, Sebeka, Minnesota, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

VERSION=8.16.1
BUILD=${BUILD:-1}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i586 ;;
    arm*) export ARCH=arm ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp}
PKG=$TMP/package-sendmail

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

# Compile with DANE? Set to some whitespace to not build with DANE.
DANE=${DANE:--DDANE}
SLKCFLAGS="$SLKCFLAGS $DANE"

rm -rf $PKG
mkdir -p $TMP $PKG

# Explode the package framework:
cd $PKG
explodepkg $CWD/_sendmail.tar.gz
[ -n "${LIBDIRSUFFIX}" ] && mv $PKG/usr/lib $PKG/usr/lib${LIBDIRSUFFIX}

echo "+=================+"
echo "| sendmail.$VERSION |"
echo "+=================+"
OSCPU="`uname -srm | tr ' ' '.'`"
cd $TMP
rm -rf sendmail-$VERSION
tar xvf $CWD/sendmail.$VERSION.tar.?z || exit 1
cd sendmail-$VERSION

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

# Add TLS support to the sendmail binary:
cat $CWD/site.config.m4 > devtools/Site/site.config.m4

# Build .cf files for Linux:
cd $TMP/sendmail-$VERSION/cf/cf
cp $CWD/*.mc .
cp linux.uucp.mc config.mc
sh Build config.cf
mv config.cf $PKG/usr/share/sendmail/linux.uucp.cf
cp sendmail-slackware.mc config.mc
sh Build config.cf
mv config.cf $PKG/usr/share/sendmail/sendmail-slackware.cf
cp sendmail-slackware-tls.mc config.mc
sh Build config.cf
mv config.cf $PKG/usr/share/sendmail/sendmail-slackware-tls.cf
cp sendmail-slackware-tls-sasl.mc config.mc
sh Build config.cf
mv config.cf $PKG/usr/share/sendmail/sendmail-slackware-tls-sasl.cf

# Add a sample sendmail.cf:
cat $PKG/usr/share/sendmail/sendmail-slackware.cf > $PKG/etc/mail/sendmail.cf.new
cat submit.cf > $PKG/etc/mail/submit.cf.new

cd $TMP/sendmail-$VERSION
## All "Build" does is call make while screwing up the options  :-)
## sh Build
make O="$SLKCFLAGS"
#O="$SLKCFLAGS" sh Build
cat sendmail/mailq.1 | gzip -9c > $PKG/usr/man/man1/mailq.1.gz
cat sendmail/newaliases.1 | gzip -9c > $PKG/usr/man/man1/newaliases.1.gz
mkdir -p $PKG/usr/doc/sendmail-$VERSION
cp -a \
  FAQ INSTALL KNOWNBUGS LICENSE PGPKEYS README RELEASE_NOTES \
  $PKG/usr/doc/sendmail-$VERSION
( cd doc ; cp -a op $PKG/usr/doc/sendmail-$VERSION )

cd obj.$OSCPU/sendmail
cat sendmail > $PKG/usr/sbin/sendmail.new
cat aliases.5 | gzip -9c > $PKG/usr/man/man5/aliases.5.gz
cat sendmail.8 | gzip -9c > $PKG/usr/man/man8/sendmail.8.gz
cat statistics > $PKG/etc/mail/statistics
cat ../../sendmail/helpfile > $PKG/etc/mail/helpfile
cd ../makemap
cat makemap > $PKG/usr/sbin/makemap
cat makemap.8 | gzip -9c > $PKG/usr/man/man8/makemap.8.gz
cd ../mailstats
cat mailstats > $PKG/usr/sbin/mailstats
cat mailstats.8 | gzip -9c > $PKG/usr/man/man8/mailstats.8.gz
cd ../praliases
cat praliases > $PKG/usr/bin/praliases
chmod 755 $PKG/usr/bin/praliases
cat praliases.8 | gzip -9c > $PKG/usr/man/man8/praliases.8.gz
cd ../rmail
cat rmail > $PKG/usr/bin/rmail
cat rmail.8 | gzip -9c > $PKG/usr/man/man8/rmail.8.gz
cd ../smrsh
cat smrsh > $PKG/usr/sbin/smrsh
cat smrsh.8 | gzip -9c > $PKG/usr/man/man8/smrsh.8.gz
cd ../mail.local
cat mail.local > $PKG/usr/sbin/mail.local
cat mail.local.8 | gzip -9c > $PKG/usr/man/man8/mail.local.8.gz
cd ../vacation
cat vacation > $PKG/usr/bin/vacation
cat vacation.1 | gzip -9c > $PKG/usr/man/man1/vacation.1.gz
cd ../editmap
cat editmap > $PKG/usr/sbin/editmap
cat editmap.8 | gzip -9c > $PKG/usr/man/man8/editmap.8.gz

# Add libmilter:
cd $TMP/sendmail-$VERSION/libmilter
./Build
cd ..
mkdir -p $PKG/usr/include
mkdir -p $PKG/usr/include/libmilter
cp -a include/libmilter/mfapi.h $PKG/usr/include/libmilter
cp -a include/libmilter/mfdef.h $PKG/usr/include/libmilter
cp -a obj.*/libmilter/libmilter.a $PKG/usr/lib${LIBDIRSUFFIX}
strip -g $PKG/usr/lib${LIBDIRSUFFIX}/libmilter.a
chmod 644 $PKG/usr/lib${LIBDIRSUFFIX}/libmilter.a $PKG/usr/include/libmilter/*
mkdir -p $PKG/usr/doc/sendmail-$VERSION/libmilter
cp -a libmilter/README $PKG/usr/doc/sendmail-$VERSION/libmilter

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

cat $CWD/slack-desc.sendmail > $PKG/install/slack-desc

# Build the package:
cd $PKG
/sbin/makepkg -l y -c n $TMP/sendmail-$VERSION-$ARCH-$BUILD.txz

