#!/bin/sh
# Don't like PulseAudio?
# Fine, we're not going to force you to use it.
#
# To eliminate PulseAudio from your system and switch to using pure ALSA,
# first remove the following packages:

removepkg --terse pulseaudio pamixer pavucontrol xfce4-pulseaudio-plugin

# Next, install the packages in this directory:

upgradepkg --install-new --terse *.txz

# Move the new asound.conf into place:

echo "Moving /etc/asound.conf.new to /etc/asound.conf:"
mv --verbose /etc/asound.conf.new /etc/asound.conf

# Make rc.alsa executable so that volume is properly restored:
echo "Making /etc/rc.d/rc.alsa executable."
chmod 755 /etc/rc.d/rc.alsa

# You may need to reboot at this point to make sure there are no running
# PulseAudio processes, or any binaries still mapping the PulseAudio libraries.
# If you use Xfce, you'll probably want to add the xfce4-mixer plugin (named
# "audio mixer" in the menu) to the panel.
#
# If you run this README file as a script, it will do all of these things for
# you except for adding the audio mixer to the Xfce panel:
#
# sh README
#
# Caveats:
# Bluetooth audio will no longer work.
# Third party packages that link to PulseAudio will need to be rebuilt.
#
# Enjoy! :-)
