#!/bin/bash

# Copyright 2008, 2009, 2010, 2017, 2018, 2025  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=adwaita-fonts-ttf
SRCNAM=adwaita-fonts
VERSION=${VERSION:-$(echo $SRCNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
ARCH=noarch
BUILD=${BUILD:-1}

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$(echo $VERSION | tr - _ )-$ARCH-$BUILD.txz"
  exit 0
fi

TMP=${TMP:-/tmp}
PKG=$TMP/package-adwaita-fonts-ttf

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf adwaita-fonts-$VERSION
tar xvf $CWD/adwaita-fonts-$VERSION.tar.?z* || exit 1
cd adwaita-fonts-$VERSION || exit 1

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+

mkdir -p $PKG/usr/share/fonts/TTF/
cp -a mono/*.ttf $PKG/usr/share/fonts/TTF/
cp -a sans/*.ttf $PKG/usr/share/fonts/TTF/

# Add optional config files for making the Adwaita fonts system default:
cp -a $CWD/conf.avail/* $PKG/usr/share/fontconfig/conf.avail
chown root:root $PKG/usr/share/fontconfig/conf.avail/*
chmod 644 $PKG/usr/share/fontconfig/conf.avail/*

mkdir -p $PKG/usr/doc/adwaita-fonts-ttf-$VERSION
cp -a \
  LICENSE README.md \
  $PKG/usr/doc/adwaita-fonts-ttf-$VERSION
cp -a mono/LICENSE.md $PKG/usr/doc/adwaita-fonts-ttf-$VERSION/LICENSE.md.mono
cp -a sans/LICENSE.md $PKG/usr/doc/adwaita-fonts-ttf-$VERSION/LICENSE.md.sans

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $TMP/adwaita-fonts-ttf-$(echo $VERSION | tr - _ )-$ARCH-$BUILD.txz
