#!/bin/sh
#item   ####description                                      ###on off ###
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
cat /dev/null > $TMP/SeTnewtag
dialog --title "SELECTING PACKAGES FROM SERIES XAP (X APPLICATIONS)" \
       --checklist "Please confirm the packages you wish to install \
from series XAP. Use the UP/DOWN keys to scroll through the list, and \
the SPACE key to deselect any items you don't want to install. \
Press ENTER when you are done." \
20 70 10 \
"MPlayer" "Media player" "on" \
"audacious" "A media player of the XMMS lineage" "on" \
"audacious-plugins" "Plugins for Audacious to support media types" "on" \
"blackbox" "Minimalist and fast window manager" "on" \
"blueman" "Graphical Bluetooth manager" "on" \
"ddd" "X frontend for the GNU gdb debugger" "on" \
"easytag" "Tag editor for audio files" "on" \
"electricsheep" "A distributed screensaver program" "on" \
"ffmpegthumbnailer" "A lightweight video thumbnailer" "on" \
"fluxbox" "Window manager based on blackbox" "on" \
"fvwm" "FVWM window manager" "on" \
"geeqie" "A lightweight picture viewing program" "on" \
"gftp" "A multithreaded FTP client" "on" \
"gimp" "GNU Image Manipulation Program" "on" \
"gkrellm" "Graphical system monitor utility" "on" \
"gnuchess" "Chess playing programs" "on" \
"gnuplot" "Gnuplot function plotting utility" "on" \
"gparted" "A graphical partition manipulation program" "on" \
"gucharmap" "Unicode character map" "on" \
"gv" ".ps/.pdf viewer based on Ghostview" "on" \
"hexchat" "IRC client for X" "on" \
"libnma" "NetworkManager GUI client library" "on" \
"mozilla-firefox" "Mozilla Firefox web browser" "on" \
"mozilla-thunderbird" "Mozilla Thunderbird email client" "on" \
"network-manager-applet" "NetworkManager Applet" "on" \
"pan" "Pan newsreader (good for Reading News)" "on" \
"pavucontrol" "PulseAudio Volume Controller" "on" \
"pidgin" "GTK+ based messaging program" "on" \
"rdesktop" "Remote Desktop Protocol client" "on" \
"rxvt-unicode" "Terminal emulator with Unicode support" "on" \
"sane" "Scanner Access Now Easy" "on" \
"seamonkey" "SeaMonkey Application Suite" "on" \
"seyon" "A complete telecommunications package" "on" \
"vim-gvim" "X/GTK+ GUI add-on for the VIM editor" "on" \
"windowmaker" "GNU window manager for X" "on" \
"x11-ssh-askpass" "X11-based SSH passphrase dialog" "on" \
"x3270" "x3270 - IBM host access tool" "on" \
"xaos" "Fast real-time fractal zoomer/viewer" "on" \
"xgames" "A collection of games for X" "on" \
"xine-lib" "Multimedia player libraries" "on" \
"xine-ui" "Multimedia player (user interface)" "on" \
"xlockmore" "A screen saver and locker for X" "on" \
"xmms" "An audio player similar to WinAmp" "on" \
"xpaint" "A color painting/image editing program" "on" \
"xpdf" "Portable Document Format (PDF) viewer" "on" \
"xsane" "X interface to Scanner Access Now Easy" "on" \
"xscreensaver" "A screen saver and locker for X" "on" \
2> $TMP/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/SeTpkgs
 > $TMP/SeTnewtag
 for pkg in \
MPlayer audacious audacious-plugins blackbox blueman ddd easytag electricsheep ffmpegthumbnailer fluxbox fvwm geeqie gftp gimp gkrellm gnuchess gnuplot gparted gucharmap gv hexchat libnma mozilla-firefox mozilla-thunderbird network-manager-applet pan pavucontrol pidgin rdesktop rxvt-unicode sane seamonkey seyon vim-gvim windowmaker x11-ssh-askpass x3270 xaos xgames xine-lib xine-ui xlockmore xmms xpaint xpdf xsane xscreensaver \
  ; do
  echo "$pkg: SKP" >> $TMP/SeTnewtag
 done
 exit
fi
cat /dev/null > $TMP/SeTnewtag
for PACKAGE in \
MPlayer audacious audacious-plugins blackbox blueman ddd easytag electricsheep ffmpegthumbnailer fluxbox fvwm geeqie gftp gimp gkrellm gnuchess gnuplot gparted gucharmap gv hexchat libnma mozilla-firefox mozilla-thunderbird network-manager-applet pan pavucontrol pidgin rdesktop rxvt-unicode sane seamonkey seyon vim-gvim windowmaker x11-ssh-askpass x3270 xaos xgames xine-lib xine-ui xlockmore xmms xpaint xpdf xsane xscreensaver \
 ; do
 if grep "\(^\| \)$PACKAGE\( \|$\)" $TMP/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> $TMP/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> $TMP/SeTnewtag
 fi
done
rm -f $TMP/SeTpkgs
