#!/bin/ash
# Null script, used to prevent error message spew in cases where the system
# has RAID volumes, but the real mdadm is not included on the initrd because
# the root partition is not RAID.
#
# If RAID support is desired on the initrd, please rebuild it using the -R
# option and this script will be replaced with the actual mdadm binary.
