#!/bin/bash

# Copyright 2010 B. Watson (yalhcru@gmail.com)
# Copyright 2010, 2015, 2018, 2020, 2024  Patrick J. Volkerding, Sebeka, Minnesota, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=xaos
SRCNAM=XaoS-release
VERSION=${VERSION:-$(echo $SRCNAM-*.tar.?z | rev | cut -f 3- -d . | rev | cut -f 3 -d -)}
BUILD=${BUILD:-1}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i686 ;;
    arm*) ARCH=arm ;;
    loongarch64) ARCH=loong64 ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

NUMJOBS=${NUMJOBS:-" -j $(expr $(nproc) + 1) "}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=pentium4 -mtune=generic"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "armv7hl" ]; then
  SLKCFLAGS="-O3 -march=armv7-a -mfpu=vfpv3-d16"
  LIBDIRSUFFIX=""
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

TMP=${TMP:-/tmp}
PKG=$TMP/package-$PKGNAM

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $SRCNAM-$VERSION*
tar xvf $CWD/$SRCNAM-$VERSION*.tar.?z || exit 1
cd $SRCNAM-$VERSION* || exit 1

chown -R root:root .
chmod -R a-s,u+w,go+r-w .

# Configure, build, and install:
mkdir cmake-build
cd cmake-build
  cmake \
    -DCMAKE_C_FLAGS="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX="$LIBDIRSUFFIX" \
    -DDOC_INSTALL_DIR="doc" \
    -DMAN_INSTALL_DIR=/usr/man \
    .. || exit 1
  make $NUMJOBS || make || exit 1
  make install DESTDIR=$PKG || exit 1
cd ..

# Stuff gets installed in the wrong place (and isn't currently configurable)
# but the binary knows where it's supposed to be so we'll just move it:
mkdir -p $PKG/usr/share/XaoS
mv $PKG/usr/{catalogs,examples,tutorial} $PKG/usr/share/XaoS
if [ ! -r $PKG/usr/share/XaoS/examples/README ]; then
  cp -a examples/README $PKG/usr/share/XaoS/examples
fi

# Let's link to the old name too:
ln -sf XaoS $PKG/usr/bin/xaos

mkdir -p $PKG/usr/share/pixmaps
cp -a xdg/xaos.png $PKG/usr/share/pixmaps

mkdir -p $PKG/usr/share/applications
cp -a xdg/io.github.xaos_project.XaoS.desktop $PKG/usr/share/applications/xaos.desktop

# Replace bogus manpage:
mkdir -p $PKG/usr/man/man6
zcat $CWD/xaos.6.gz > $PKG/usr/man/man6/xaos.6
gzip -9 $PKG/usr/man/man6/xaos.6

mkdir -p $PKG/usr/doc/xaos-$VERSION
cp -a \
  COPYING* CREDITS* NEWS* README* \
  $PKG/usr/doc/xaos-$VERSION
cp -a doc/XaoS.lsm $PKG/usr/doc/xaos-$VERSION
cp -a doc/README $PKG/usr/doc/xaos-$VERSION/wiki.url

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $TMP/$PKGNAM-$VERSION-$ARCH-$BUILD.txz
