#!/bin/sh
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi

dialog --backtitle "Select Slackware installation source." \
--title "SOURCE MEDIA SELECTION" --menu \
"Please select the media from which to install Slackware Linux:" \
14 70 7 \
"1" "Install from a Slackware CD or DVD" \
"2" "Install from a Slackware USB stick" \
"3" "Install from a hard drive partition" \
"4" "Install from NFS (Network File System)" \
"5" "Install from FTP/HTTP server" \
"6" "Install from Samba share" \
"7" "Install from a pre-mounted directory" \
2> $TMP/media
if [ ! $? = 0 ]; then
 rm $TMP/media
 exit
fi

SOURCE_MEDIA="`cat $TMP/media`"
rm -f $TMP/media
if [ "$SOURCE_MEDIA" = "1" ]; then
 INSCD
elif [ "$SOURCE_MEDIA" = "2" ]; then
 INSUSB
elif [ "$SOURCE_MEDIA" = "3" ]; then
 INShd
elif [ "$SOURCE_MEDIA" = "4" ]; then
 SeTnet
 INSNFS
elif [ "$SOURCE_MEDIA" = "5" ]; then
 SeTnet
 INSURL 
elif [ "$SOURCE_MEDIA" = "6" ]; then
 SeTnet
 INSSMB 
elif [ "$SOURCE_MEDIA" = "7" ]; then
 INSdir
fi

# Sorry, this goes the way of the dinosaur...
#"5" "Install from floppy disks (A and N series only)" 

