#!/bin/sh
#
# /sbin/brc (whatever that means ;)
# This script gets run just before the system is down.
#
cat << EOF


The system is rebooting NOW!

Syncing disks...
EOF
/bin/sync
echo
echo "Unmounting file systems... "
/bin/umount -a 1> /dev/null 2> /dev/null
echo
sleep 2
/sbin/reboot -f
