#!/bin/bash

# Copyright 2005-2024  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=less
VERSION=${VERSION:-$(echo less-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
LESSPIPEVER=$(echo lesspipe-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)
BUILD=${BUILD:-1}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i686 ;;
    arm*) export ARCH=arm ;;
    loongarch64) export ARCH=loong64 ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}

if [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=pentium4 -mtune=generic"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
elif [ "$ARCH" = "loong64" ]; then
  SLKCFLAGS="-O2 -fPIC"
else
  SLKCFLAGS="-O2"
fi

TMP=${TMP:-/tmp}
PKG=$TMP/package-less
rm -rf $PKG
mkdir -p $TMP $PKG

cd $TMP
rm -rf less-$VERSION
tar xvf $CWD/less-$VERSION.tar.?z || exit 1
cd less-$VERSION || exit 1

# Fix path in manpage:
if [ -r less.nro ]; then
  sed -i "s,/usr/local/etc,/etc,g" less.nro
fi

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+

if [ ! -r configure ]; then
  if [ -x ./autogen.sh ]; then
    NOCONFIGURE=1 ./autogen.sh
  else
    autoreconf -vif
  fi
fi

# Prep needed if using the git archive:
for file in funcs.h less.nro lesskey.nro lessecho.nro ; do
  if [ ! -r $file ]; then
    make -f Makefile.aut $file
  fi
done

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --mandir=/usr/man || exit 1

make $NUMJOBS || make || exit 1
make install DESTDIR=$PKG || exit 1

mkdir -p $PKG/usr/man/man1
for page in less.nro lesskey.nro ; do
  cat $page > $PKG/usr/man/man1/`basename $page .nro`.1
done

mkdir -p $PKG/usr/doc/less-$VERSION
cp -a \
  COPYING* LICENSE README NEWS \
  $PKG/usr/doc/less-$VERSION

# Install lesspipe.sh etc:
cd $TMP
rm -r lesspipe-$LESSPIPEVER
tar xf $CWD/lesspipe-${LESSPIPEVER}.tar.?z || exit 1
cd lesspipe-${LESSPIPEVER}
chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \+
# Don't use special handling for .log files:
cat $CWD/lesspipe.log.patch | patch -p1 --verbose || exit 1
./configure --prefix=/usr || exit 1
make
make install DESTDIR=$PKG
mv $PKG/usr/share/man/man1/* $PKG/usr/man/man1
rmdir $PKG/usr/share/man/man1 $PKG/usr/share/man
# wrong directory:
mkdir -p $PKG/usr/share/bash-completion/completions
mv $PKG/usr/share/bash-completion/less_completion $PKG/usr/share/bash-completion/completions/less
mkdir -p $PKG/usr/doc/lesspipe-${LESSPIPEVER}
cp -a COPYING* ChangeLog* INSTALL* README* \
  $PKG/usr/doc/lesspipe-${LESSPIPEVER}

# Install profile scripts:
mkdir -p $PKG/etc/profile.d
cp -a $CWD/less.csh $PKG/etc/profile.d/less.csh.new
cp -a $CWD/less.sh $PKG/etc/profile.d/less.sh.new
chown root:root $PKG/etc/profile.d/*
chmod 755 $PKG/etc/profile.d/*

# Compress and link manpages, if any:
if [ -d $PKG/usr/man ]; then
  ( cd $PKG/usr/man
    for manpagedir in $(find . -type d -name "man*") ; do
      ( cd $manpagedir
        for eachpage in $( find . -type l -maxdepth 1 | grep -v '\.gz$') ; do
          ln -s $( readlink $eachpage ).gz $eachpage.gz
          rm $eachpage
        done
        gzip -9 *.?
      )
    done
  )
fi

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p $PKG/install
cat $CWD/doinst.sh > $PKG/install/doinst.sh
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
/sbin/makepkg -l y -c n $TMP/less-$VERSION-$ARCH-$BUILD.txz
