#!/bin/sh

# Copyright 2008, 2009  Patrick J. Volkerding, Sebeka, Minnesota, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


VERSION=114i
ARCH=${ARCH:-x86_64}
BUILD=${BUILD:-1}

CWD=$(pwd)
TMP=${TMP:-/tmp}
PKG=$TMP/package-lha

rm -rf $PKG
mkdir -p $TMP $PKG

cd $TMP
rm -rf lha-114i
tar xzvf $CWD/lha-114i.tar.gz
cd lha-114i
zcat $CWD/lha_1.14i-10.1.diff.gz | patch -p1 --verbose || exit 1
patch -p0 < debian/patch.paul
patch -p0 < debian/patch.multibyte
patch -p0 < debian/patch.CAN-2004-0234_0235
patch -p0 < debian/patch.header-overflow
patch -p1 < debian/patch.redhat-sec2
patch -p1 < debian/patch.CVE-2006-4335-CVE-2006-4337-CVE-2006-4338
chown -R root:root .
make || exit 1
mkdir -p $PKG/usr/bin
cat src/lha > $PKG/usr/bin/lha
chmod 755 $PKG/usr/bin/lha
mkdir -p $PKG/usr/man/man1
cat debian/lha.1 | gzip -9 > $PKG/usr/man/man1/lha.1.gz
mkdir -p $PKG/usr/man/jp/man1
cat man/lha.man | gzip -9 > $PKG/usr/man/jp/man1/lha.1.gz
mkdir -p $PKG/usr/doc/lha-114i
cp -a \
  change-${VERSION}.txt \
  $PKG/usr/doc/lha-${VERSION}
mkdir -p $PKG/usr/doc/lha-${VERSION}/jp
cp -a *.euc \
  $PKG/usr/doc/lha-${VERSION}/jp
chmod 644 $PKG/usr/man/jp/man1/*

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
makepkg -l y -c n $TMP/lha-$VERSION-$ARCH-$BUILD.txz

