#!/bin/sh
# This is a simple script to update grub from the configuration file.
# Please note that after upgrading to a new grub version, you should
# first use "grub-install" to reinstall the bootloader, similar to this:
# grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Slackware --recheck
# or this:
# grub-install --target=i386-pc --recheck /dev/sdX

set -e
exec grub-mkconfig -o /boot/grub/grub.cfg "$@"
