#!/bin/bash

# Copyright 2007, 2008, 2012 Eric Hameleers, Eindhoven, NL
# Copyright 2007-2008, 2013, 2014, 2017 Heinz Wiesinger, Amsterdam, NL
# Copyright 2008, 2009, 2010, 2013, 2014, 2015, 2017, 2018, 2020, 2021, 2022, 2024  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# bjam-build system mostly taken from SlackBuild by Eric Hameleers
# Script modified by Robby Workman - no copyright claims or added terms
# Modified 2012 by Eric Hameleers <alien at slackware.com> for ARM port.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=boost
VERSION=${VERSION:-$(echo $PKGNAM_*.tar.?z | rev | cut -f 3- -d . | rev | cut -f 2- -d _)}
BUILD=${BUILD:-5}

PKG_VERSION=$(echo $VERSION | tr _ .)	# Leave this alone
NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}

# Automatically determine the architecture we're building on:
MARCH=$( uname -m )
if [ -z "$ARCH" ]; then
  case "$MARCH" in
    i?86)    export ARCH=i686 ;;
    arm*)    export ARCH=arm ;;
    loongarch64)    export ARCH=loong64 ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
    *)       export ARCH=$MARCH ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$PKG_VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

if [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=pentium4 -mtune=generic -DBOOST_STACKTRACE_LIBCXX_RUNTIME_MAY_CAUSE_MEMORY_LEAK=1"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -march=x86-64 -mtune=generic -fPIC"
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "loong64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

PYTHON3_VERSION=$(python3 -c 'import sys; print("{}.{}".format(sys.version_info.major, sys.version_info.minor))') 

TMP=${TMP:-/tmp}
PKG=$TMP/package-boost

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf boost_$VERSION
echo "Extracting $CWD/boost_$VERSION.tar.?z..."
tar xf $CWD/boost_$VERSION.tar.?z || exit 1
cd boost_$VERSION || exit 1

chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \+ -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \+

# Avoid hardcoded /tmp/package-boost/ paths in the cmake files:
cat $CWD/boost-1.73.0-cmakedir.patch | patch -p1 --verbose || exit 1

# Fix hardcorded python:
zcat $CWD/boost.bootstrap.python3.diff.gz | patch -p1 --verbose || exit 1

# First build bjam, the boost build system:
./bootstrap.sh \
  --with-toolset=gcc \
  --with-icu \
  --with-python=/usr/bin/python3 || exit 1

# Next, we build boost using bjam:
./b2 \
  $NUMJOBS \
  --layout=system \
  --build-dir=tmp-build-directory \
  --prefix=/usr \
  --libdir=/usr/lib$LIBDIRSUFFIX \
  --build-type=minimal \
  toolset=gcc \
  variant=release \
  debug-symbols=off \
  link=shared \
  threading=multi \
  runtime-link=shared \
  python=$PYTHON3_VERSION \
  cflags="$SLKCFLAGS" \
  cxxflags="$SLKCFLAGS $EXTRA_CXXFLAGS" \
  stage || exit 1

# And then install boost:
./b2 \
  $NUMJOBS \
  --layout=system \
  --build-dir=tmp-build-directory \
  --prefix=$PKG/usr \
  --libdir=$PKG/usr/lib$LIBDIRSUFFIX \
  --build-type=minimal \
  toolset=gcc \
  variant=release \
  debug-symbols=off \
  link=shared \
  threading=multi \
  runtime-link=shared \
  python=$PYTHON3_VERSION \
  cflags="$SLKCFLAGS" \
  cxxflags="$SLKCFLAGS $EXTRA_CXXFLAGS" \
  install || exit 1

find $PKG | xargs file | grep -e "executable" -e "shared object" \
  | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

mkdir -p $PKG/usr/doc/boost-$PKG_VERSION
# Do not copy 44MB of developer 'doc/html' into our package...
cp -a LICENSE* index.html $PKG/usr/doc/boost-$PKG_VERSION
find $PKG/usr/doc -type f -exec chmod 0644 {} \+

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n /tmp/boost-$PKG_VERSION-$ARCH-$BUILD.txz
