#!/bin/sh
#item   ####description                                      ###on off ###
TMP=/var/log/setup/tmp
if [ ! -d $TMP ]; then
  mkdir -p $TMP
fi
cat /dev/null > $TMP/SeTnewtag
dialog --title "SELECTING PACKAGES FROM SERIES KDE" \
--checklist "Please confirm the packages you wish to install \
from series KDE.  KDE is a network transparent desktop \
environment that seeks to fill the need for an easy to use desktop \
for Unix workstations, similar to the desktop environments found \
under MacOS or Windows.  Use the UP/DOWN keys to scroll through \
the list, and the SPACE key to deselect any items you don't want \
to install.  Press ENTER when you are done." \
22 72 9 \
"amarok" "A media player for KDE" "on" \
"guidance-power-manager" "KDE frontend for HAL's power features" "on" \
"k3b" "CD/DVD burning app for KDE" "on" \
"kaudiocreator" "CD ripper and audio encoder" "on" \
"kdeaccessibility" "KDE accessibility utilities" "on" \
"kdeadmin" "KDE system administration utilities" "on" \
"kdeartwork" "Extra themes, sounds, wallpapers, and styles" "on" \
"kdebase" "The K Desktop Environment base package" "on" \
"kdebase-runtime" "The KDE base rumtime support package" "on" \
"kdebase-workspace" "The KDE base workspace package" "on" \
"kdebindings" "Optional KDE library bindings" "on" \
"kdeedu" "KDE Edutainment programs" "on" \
"kdegames" "A KDE games collection" "on" \
"kdegraphics" "Graphic programs for KDE" "on" \
"kdelibs" "Libraries required for KDE" "on" \
"kdemultimedia" "Multimedia programs for KDE" "on" \
"kdenetwork" "Networking programs for KDE" "on" \
"kdepim" "Personal Information Management tools" "on" \
"kdepimlibs" "KDE Personal Information Management libraries" "on" \
"kdeplasma-addons" "Plasma addons for KDE" "on" \
"kdesdk" "KDE software development kit" "on" \
"kdetoys" "Toys for the KDE desktop" "on" \
"kdeutils" "Utilities for KDE" "on" \
"kdevelop" "KDE Application Development Environment" "on" \
"kdevplatform" "Libraries used by kdevelop" "on" \
"kdewebdev" "Quanta Plus web development environment" "on" \
"koffice" "The KDE office productivity suite" "on" \
"konq-plugins" "Plugins to extend Konqueror" "on" \
"ktorrent" "BitTorrent program for KDE" "on" \
"mplayerthumbs" "Use MPlayer for KDE video thumbnail support" "on" \
"skanlite" "KDE scanning program" "on" \
2> $TMP/SeTpkgs
if [ $? = 1 -o $? = 255 ]; then
 rm -f $TMP/SeTpkgs
 > $TMP/SeTnewtag
 for pkg in \
amarok guidance-power-manager k3b kaudiocreator kdeaccessibility kdeadmin kdeartwork kdebase kdebase-runtime kdebase-workspace kdebindings kdeedu kdegames kdegraphics kdelibs kdemultimedia kdenetwork kdepim kdepimlibs kdeplasma-addons kdesdk kdetoys kdeutils kdevelop kdevplatform kdewebdev koffice konq-plugins ktorrent mplayerthumbs skanlite \
  ; do
  echo "$pkg: SKP" >> $TMP/SeTnewtag
 done
 exit
fi
cat /dev/null > $TMP/SeTnewtag
for PACKAGE in \
amarok guidance-power-manager k3b kaudiocreator kdeaccessibility kdeadmin kdeartwork kdebase kdebase-runtime kdebase-workspace kdebindings kdeedu kdegames kdegraphics kdelibs kdemultimedia kdenetwork kdepim kdepimlibs kdeplasma-addons kdesdk kdetoys kdeutils kdevelop kdevplatform kdewebdev koffice konq-plugins ktorrent mplayerthumbs skanlite \
 ; do
 if fgrep \"$PACKAGE\" $TMP/SeTpkgs 1> /dev/null 2> /dev/null ; then
  echo "$PACKAGE: ADD" >> $TMP/SeTnewtag
 else
  echo "$PACKAGE: SKP" >> $TMP/SeTnewtag
 fi
done
rm -f $TMP/SeTpkgs
