#!/bin/bash

# Copyright 2008, 2009, 2010, 2012, 2018  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PKGNAM=bsd-games
VERSION=${VERSION:-2.17}
BUILD=${BUILD:-6}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i686 ;;
    arm*) export ARCH=arm ;;
    loongarch64) export ARCH=loong64 ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PKGNAM-$VERSION-$ARCH-$BUILD.txz"
  exit 0
fi

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}

TMP=${TMP:-/tmp}
PKG=$TMP/package-bsdgames
rm -rf $PKG
mkdir -p $TMP $PKG

cd $TMP
rm -rf bsd-games-$VERSION
tar xvf $CWD/bsd-games-$VERSION.tar.?z || exit 1
cd bsd-games-$VERSION || exit 1

zcat $CWD/patches/bsd-games.config.params.diff.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0001-Replace-getline-with-get_line.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0002-robots-Refresh-screen.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0003-quiz-Update-presidents-capitals-fix-typos-in-murders.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0004-Define-__dead-for-GNU-GCC.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0005-rain-Update-default-delay.-Closes-579062.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0007-Unsorted-Debian-patches.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0008-quiz-Add-answers-to-adults-babies.-Closes-659528.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0009-hangman-Error-out-on-1000-unsuitable-words.-Closes-6.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0010-Fix-typos-spotted-by-Lintian.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0011-Fix-format-security-compiling-errors.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0012-Fix-include-stdio.h-C-incompatibility.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0013-Update-acronyms.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0015-primes-Update-to-NetBSD-CVS-2018-02-03.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0016-Better-explanation-how-to-read-the-documentation.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/0017-hack-Fix-segv-when-i-inventory-done-after-load-from-.patch.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/bsd-games.factor.no.ubig.diff.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/bsd-games.fortunepath.diff.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1
zcat $CWD/patches/bsd-games.gcc14.diff.gz | patch -p1 --backup --suffix=.orig --verbose || exit 1

./configure || exit 1

## Without the old default (with, of course, a command line switch), and an updated
## man page, even though PJV wrote this, it just doesn't make the cut.  I hope it's
## still of use to somebody though.  It increases the accuracy of pom by two orders
## of magnitude.  Enjoy!
##zcat $CWD/patches/bsd-games.pom.diff.gz | patch -p1 --verbose || exit 1

# Now that Eric took my joke seriously...  heh.  It's a wonder any Work gets done here.
zcat $CWD/patches/bsd-games.pom.diff.gz | patch -p1 --verbose || exit 1

# I'm not in favor of censorship of any kind.  If you are, you'll
# have to be the one to delete these:
for bad in fortunes-o fortunes2-o limerick-o unamerican-o ; do
  cp fortune/datfiles/${bad}.real fortune/datfiles/${bad}.fake
  cp fortune/datfiles/${bad}.real ${bad}
  ( cd fortune/datfiles ; strfile ${bad} ${bad}.dat )
done

make || exit 1

# Does this go to $PKG?  I am perplexed.
make install || exit 1

mkdir -p $PKG/usr/doc/bsd-games-$VERSION
cp -a \
  AUTHORS BUGS INSTALL NEWS PACKAGING README SECURITY THANKS \
  TODO YEAR2000 $PKG/usr/doc/bsd-games-$VERSION
cp -a fortune/README $PKG/usr/doc/bsd-games-$VERSION/README.fortune
cp -a hunt/README $PKG/usr/doc/bsd-games-$VERSION/README.hunt
cp -a phantasia/README $PKG/usr/doc/bsd-games-$VERSION/README.phantasia
chown root.root $PKG/usr/doc/bsd-games-$VERSION/*
mv $PKG/usr/share/doc/bsd-games/* $PKG/usr/doc/bsd-games-$VERSION
rm -rf $PKG/usr/share/doc
chmod 644 $PKG/usr/doc/bsd-games-$VERSION/*

cd $PKG
# Add profile scripts:
mkdir -p etc/profile.d
cat $CWD/bsd-games-login-fortune.sh > etc/profile.d/bsd-games-login-fortune.sh
cat $CWD/bsd-games-login-fortune.csh > etc/profile.d/bsd-games-login-fortune.csh
chmod 755 etc/profile.d/bsd-games-login-fortune.*

# Add some cool Linux related quotes:
tar xvf $CWD/fortunes-linuxcookie.tar.gz || exit 1

# Run strfile on all fortune files:
( cd $PKG/usr/share/games/fortunes
  for file in *.dat ; do
    $PKG/usr/bin/strfile -r $(basename $file .dat)
  done 
  # These ones are rot13:
  for file in *-o.dat ; do
    $PKG/usr/bin/strfile -r -x $(basename $file .dat)
  done
)

# Strip binaries:
strip $PKG/usr/games/* $PKG/usr/bin/* $PKG/usr/sbin/*

# Fix perms:
mkdir -p $PKG/usr/share/dict
zcat $CWD/hangman-words.gz > $PKG/usr/share/dict/words
chmod 644 $PKG/var/lib/bsdgames/phantasia/characs

# OK, I'll try to be nice but the first time you're still $cr3w3d unless you
# installpkg first.
( cd $PKG/var/lib/bsdgames
  find . -type f -exec mv {} {}.new \;
)

mkdir -p $PKG/install
cat << EOF > $PKG/install/doinst.sh
#!/bin/bash
config() {
  NEW="\$1"
  OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
  # If there's no config file by that name, mv it over:
  if [ ! -r \$OLD ]; then
    mv \$NEW \$OLD
  elif [ "\$(cat \$OLD | md5sum)" = "\$(cat \$NEW | md5sum)" ]; then # toss the redundant copy
    rm \$NEW
  fi
  # Otherwise, we leave the .new copy for the admin to consider...
}
config var/lib/bsdgames/atc_score.new
config var/lib/bsdgames/robots_roll.new
config var/lib/bsdgames/hack/perm.new
config var/lib/bsdgames/hack/record.new
config var/lib/bsdgames/phantasia/lastdead.new
config var/lib/bsdgames/phantasia/scoreboard.new
config var/lib/bsdgames/phantasia/monsters.new
config var/lib/bsdgames/phantasia/mess.new
config var/lib/bsdgames/phantasia/characs.new
config var/lib/bsdgames/phantasia/motd.new
config var/lib/bsdgames/phantasia/gold.new
config var/lib/bsdgames/phantasia/void.new
config var/lib/bsdgames/snakerawscores.new
config var/lib/bsdgames/saillog.new
config var/lib/bsdgames/battlestar.log.new
config var/lib/bsdgames/snake.log.new
config var/lib/bsdgames/criblog.new
config var/lib/bsdgames/cfscores.new
( cd var/lib/bsdgames ; find . -name "*.new" -exec rm -f "{}" \; )
EOF
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
/sbin/makepkg -l y -c n $TMP/bsd-games-$VERSION-$ARCH-$BUILD.txz

